// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for reader.
type ReaderComponent struct {
	Contract xdatly.Component[TokenInput, TokenOutput] "component:\"reader,path=/v1/api/agently/user/oauth,method=GET,connector=agently,view=reader,internal=true\" routeName:\"reader\" caseFormat:\"lc\""
}

// ReaderDatlyType returns the public component type.
func ReaderDatlyType() reflect.Type { return reflect.TypeOf((*ReaderComponent)(nil)).Elem() }

// The package-level value keeps this real component type reachable for runtime discovery.
var ReaderDatly = new(ReaderComponent)
var _datlyReachableReaderComponent = reflect.TypeFor[ReaderComponent]()

func (ReaderComponent) EmbedFS() *embed.FS {
	return &ReaderDatlyResources
}

func (ReaderComponent) EmbedNamespace() string {
	return ReaderDatlyResourceNamespace
}
