pipeline:

  info:
    action: print
    message: 'running agently-app host from repoPath: ${repoPath}'

  app:
    stop:
      action: process:stop
      input: agently-app serve

    start:
      action: process:start
      directory: ${repoPath}
      checkError: true
      immuneToHangups: true
      sleepTimeMs: 4000
      env:
        TEST: 1
        AGENTLY_WORKSPACE: ${workspacePath}
      command: ${repoPath}/e2e/bin/agently-app serve --addr ':8585'
