// Code generated by Datly for writer; DO NOT EDIT.

package write

func (input *Input) SetOrphanDelete(value bool) {
	if input == nil {
		return
	}
	input.OrphanDelete = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanDelete = true
}

func (input *Input) SetTrusted(value bool) {
	if input == nil {
		return
	}
	input.Trusted = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Trusted = true
}

func (input *Input) SetClaimMode(value string) {
	if input == nil {
		return
	}
	input.ClaimMode = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ClaimMode = true
}

func (input *Input) SetExpectedTurnID(value string) {
	if input == nil {
		return
	}
	input.ExpectedTurnID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExpectedTurnID = true
}

func (input *Input) SetClaims(value []*Claim) {
	if input == nil {
		return
	}
	input.Claims = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Claims = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
