package toolapprovalqueue

import (
	"context"
	"embed"
	"fmt"
	"github.com/viant/datly"
	"github.com/viant/datly/repository"
	"github.com/viant/datly/repository/contract"
	"github.com/viant/datly/view"
	"github.com/viant/xdatly/handler/response"
	"github.com/viant/xdatly/types/core"
	"github.com/viant/xdatly/types/custom/dependency/checksum"
	"reflect"
	"time"
)

// Code generated by datly. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

func init() {
	core.RegisterType("toolapprovalqueue", "QueueRowsInput", reflect.TypeOf(QueueRowsInput{}), checksum.GeneratedTime)
	core.RegisterType("toolapprovalqueue", "QueueRowsOutput", reflect.TypeOf(QueueRowsOutput{}), checksum.GeneratedTime)
}

//go:embed queue_rows/*.sql
var QueueRowsFS embed.FS

type QueueRowsInput struct {
	UserId         string             `parameter:",kind=query,in=userId" predicate:"equal,group=0,q,user_id"`
	ConversationId string             `parameter:",kind=query,in=conversationId" predicate:"equal,group=0,q,conversation_id"`
	TurnId         string             `parameter:",kind=query,in=turnId" predicate:"equal,group=0,q,turn_id"`
	MessageId      string             `parameter:",kind=query,in=messageId" predicate:"equal,group=0,q,message_id"`
	ToolName       string             `parameter:",kind=query,in=toolName" predicate:"equal,group=0,q,tool_name"`
	QueueStatus    string             `parameter:",kind=query,in=status" predicate:"equal,group=0,q,status" value:"pending"`
	Has            *QueueRowsInputHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-"`
}

type QueueRowsInputHas struct {
	UserId         bool
	ConversationId bool
	TurnId         bool
	MessageId      bool
	ToolName       bool
	QueueStatus    bool
}

type QueueRowsOutput struct {
	response.Status `parameter:",kind=output,in=status" json:",omitempty"`
	Data            []*QueueRowsView `parameter:",kind=output,in=view" view:"queue_rows,batch=10000,relationalConcurrency=1" sql:"uri=queue_rows/queue_rows.sql"`
	Metrics         response.Metrics `parameter:",kind=output,in=metrics"`
}

type QueueRowsView struct {
	ApprovedAt       *time.Time `sqlx:"approved_at"`
	ApprovedByUserId *string    `sqlx:"approved_by_user_id"`
	Arguments        string     `sqlx:"arguments"`
	ConversationId   *string    `sqlx:"conversation_id"`
	CreatedAt        time.Time  `sqlx:"created_at"`
	Decision         *string    `sqlx:"decision"`
	ErrorMessage     *string    `sqlx:"error_message"`
	ExecutedAt       *time.Time `sqlx:"executed_at"`
	Id               string     `sqlx:"id"`
	MessageId        *string    `sqlx:"message_id"`
	Metadata         *string    `sqlx:"metadata"`
	Status           string     `sqlx:"status"`
	Title            *string    `sqlx:"title"`
	ToolName         string     `sqlx:"tool_name"`
	TurnId           *string    `sqlx:"turn_id"`
	UpdatedAt        *time.Time `sqlx:"updated_at"`
	UserId           string     `sqlx:"user_id"`
}

var QueueRowsPathURI = "/v1/api/agently/toolapprovalqueue/pending/pending"

func DefineQueueRowsComponent(ctx context.Context, srv *datly.Service) error {
	aComponent, err := repository.NewComponent(
		contract.NewPath("GET", QueueRowsPathURI),
		repository.WithResource(srv.Resource()),
		repository.WithContract(
			reflect.TypeOf(QueueRowsInput{}),
			reflect.TypeOf(QueueRowsOutput{}), &QueueRowsFS, view.WithConnectorRef("agently")))

	if err != nil {
		return fmt.Errorf("failed to create QueueRows component: %w", err)
	}
	if err := srv.AddComponent(ctx, aComponent); err != nil {
		return fmt.Errorf("failed to add QueueRows component: %w", err)
	}
	return nil
}

func (i *QueueRowsInput) EmbedFS() *embed.FS {
	return &QueueRowsFS
}
