import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { describe, it, expect } from 'vitest';
import { AgentlyClient } from './client';
const path = process.env.AGENTLY_SDK_REPORT_CONTRACT_READY;
const ready = path ? JSON.parse(readFileSync(path, 'utf8')) : undefined;
(ready ? describe : describe.skip)('actual public reporting/export/audit/queue SDK', () => {
    const client = (key: string) => new AgentlyClient({ baseURL: `${ready.url}/v1`, retries: 0, tokenProvider: () => readFileSync(ready[key], 'utf8').trim() });
    it('uses typed report lifecycle and reporting/queue SDK methods', async () => {
        const owner = client('ownerTokenFile'), other = client('otherTokenFile');
        const conversationId = ready.tsConversationId;
        const snapshots = JSON.parse(readFileSync(ready.reportingSnapshotsFile, 'utf8'));
        const input = { uiRunRequestId: `ts-${randomUUID()}`, origin: 'manual' as const };
        const begun = await owner.beginReportRun(input);
        expect((await owner.beginReportRun(input)).run.reportRunId).toBe(begun.run.reportRunId);
        const completed = await owner.completeReportRun(begun.run.reportRunId, { expectedRevision: 1, ...snapshots });
        expect(completed.revision).toBe(2);
        const previous = await owner.getReportContext(conversationId).catch(error => { expect(error).toMatchObject({ status: 404 }); return null; });
        const adoption = { conversationId, expectedRunRevision: completed.revision, expectedContextRevision: previous?.revision ?? 0, source: 'adopt' };
        await expect(other.adoptReportRun(completed.reportRunId, adoption)).rejects.toMatchObject({ status: 404 });
        const adopted = await owner.adoptReportRun(completed.reportRunId, adoption);
        expect(adopted.context?.activeReportRunId).toBe(completed.reportRunId);
        expect((await owner.getReportRun(completed.reportRunId, conversationId)).conversationId).toBe(conversationId);
        const options = { conversationId, exportRequestId: `ts-export-${randomUUID()}` };
        const job = await owner.submitReportRunExport(completed.reportRunId, options);
        expect((await owner.submitReportRunExport(completed.reportRunId, options)).jobId).toBe(job.jobId);
        expect(job.reportRunId).toBe(completed.reportRunId);
        expect((await owner.getReportExportStatus(job.jobId, conversationId)).status).toBe('queued');
        const audit = await owner.recordReportAuditEvent({ eventType: 'report.download', artifactRef: job.artifactRef!, jobId: job.jobId, metadata: { via: 'ts-sdk' } });
        expect(audit.actorId).toBe(job.ownerId);
        const artifact = await owner.getReportArtifact(ready.tsArtifactId);
        expect(artifact.contentType).toBe('application/pdf');
        expect(artifact.data).toBeUndefined();
        await expect(other.getReportArtifact(ready.tsArtifactId)).rejects.toMatchObject({ status: 404 });
        const content = `ts SDK edit ${randomUUID()}`;
        await owner.editQueuedTurn(conversationId, ready.tsTurnId, { content });
        const transcript = await owner.getTranscript({ conversationId });
        expect((transcript as any).conversation.turns.find((turn: any) => turn.turnId === ready.tsTurnId).user.content).toBe(content);
    });
});
