// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetTrusted(value bool) {
	if input == nil {
		return
	}
	input.Trusted = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Trusted = true
}

func (input *Input) SetThreadIDs(value []string) {
	if input == nil {
		return
	}
	input.ThreadIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ThreadIDs = true
}
