package run

import (
	"context"
	"embed"
	"fmt"
	"github.com/viant/datly"
	"github.com/viant/datly/repository"
	"github.com/viant/datly/repository/contract"
	"github.com/viant/datly/view"
	"github.com/viant/xdatly/handler/response"
	"github.com/viant/xdatly/types/core"
	"github.com/viant/xdatly/types/custom/dependency/checksum"
	"reflect"
	"time"
)

// Code generated by datly. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

func init() {
	core.RegisterType("run", "RunStepsInput", reflect.TypeOf(RunStepsInput{}), checksum.GeneratedTime)
	core.RegisterType("run", "RunStepsOutput", reflect.TypeOf(RunStepsOutput{}), checksum.GeneratedTime)
}

//go:embed run_steps/*.sql
var RunStepsFS embed.FS

type RunStepsInput struct {
	RunID        string            `parameter:",kind=query,in=runId" predicate:"equal,group=0,m,run_id" predicate:"equal,group=1,t,run_id"`
	Iteration    int               `parameter:",kind=query,in=iteration" predicate:"equal,group=0,m,iteration" predicate:"equal,group=1,t,iteration"`
	StepTypes    []string          `parameter:",kind=query,in=stepTypes" predicate:"literal_in,group=0,model_call" predicate:"literal_in,group=1,tool_call"`
	CursorBefore string            `parameter:",kind=query,in=cursorBefore" predicate:"expr,group=0,m.message_id < ?" predicate:"expr,group=1,t.message_id < ?"`
	CursorAfter  string            `parameter:",kind=query,in=cursorAfter" predicate:"expr,group=0,m.message_id > ?" predicate:"expr,group=1,t.message_id > ?"`
	Has          *RunStepsInputHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-"`
}

type RunStepsInputHas struct {
	RunID        bool
	Iteration    bool
	StepTypes    bool
	CursorBefore bool
	CursorAfter  bool
}

type RunStepsOutput struct {
	response.Status `parameter:",kind=output,in=status" json:",omitempty"`
	Data            []*RunStepsView  `parameter:",kind=output,in=view" view:"run_steps,batch=10000,relationalConcurrency=1" sql:"uri=run_steps/run_steps.sql"`
	Metrics         response.Metrics `parameter:",kind=output,in=metrics"`
}

type RunStepsView struct {
	StepType       string     `sqlx:"step_type"`
	RunId          *string    `sqlx:"run_id"`
	ConversationId *string    `sqlx:"conversation_id"`
	Iteration      *int       `sqlx:"iteration"`
	MessageId      string     `sqlx:"message_id"`
	Name           string     `sqlx:"name" source:"model"`
	Status         string     `sqlx:"status"`
	StartedAt      *time.Time `sqlx:"started_at"`
	CompletedAt    *time.Time `sqlx:"completed_at"`
	LatencyMs      *int       `sqlx:"latency_ms"`
	ErrorMessage   *string    `sqlx:"error_message"`
}

var RunStepsPathURI = "/v1/api/agently/run/steps/steps"

func DefineRunStepsComponent(ctx context.Context, srv *datly.Service) error {
	aComponent, err := repository.NewComponent(
		contract.NewPath("GET", RunStepsPathURI),
		repository.WithResource(srv.Resource()),
		repository.WithContract(
			reflect.TypeOf(RunStepsInput{}),
			reflect.TypeOf(RunStepsOutput{}), &RunStepsFS, view.WithConnectorRef("agently")))

	if err != nil {
		return fmt.Errorf("failed to create RunSteps component: %w", err)
	}
	if err := srv.AddComponent(ctx, aComponent); err != nil {
		return fmt.Errorf("failed to add RunSteps component: %w", err)
	}
	return nil
}

func (i *RunStepsInput) EmbedFS() *embed.FS {
	return &RunStepsFS
}
