// Code generated by Datly for reader; DO NOT EDIT.

package cube

// ApprovalReportOutput is the generated output scaffold for reader.
type ApprovalReportOutput struct {
	Data []*ApprovalReportView `parameter:"Data,kind=output,in=view,dataType=[]*ApprovalReportView" view:"reader,type=ApprovalReportView,table=tool_approval_queue,groupable=true,selectorProjection=true" sql:"uri=datly_toolapprovalqueue_cube_reader:sql/reader.sql"`
}
