// Code generated by Datly for reader; DO NOT EDIT.

package cube

// ApprovalReportView is generated canonical view metadata for reader.
type ApprovalReportView struct {
	UserId         string  `groupable:"true" sqlx:"user_id,required=true"`
	ConversationId *string `groupable:"true" sqlx:"conversation_id,refTable=conversation,refColumn=id"`
	ToolName       string  `groupable:"true" sqlx:"tool_name,required=true"`
	Status         string  `groupable:"true" sqlx:"status,required=true"`
	Decision       *string `groupable:"true" sqlx:"decision"`
	TotalCount     int     `groupable:"false" sqlx:"total_count"`
	PendingCount   int     `groupable:"false" sqlx:"pending_count"`
	OutcomeCount   int     `groupable:"false" sqlx:"outcome_count"`
	TimedOutCount  int     `groupable:"false" sqlx:"timed_out_count"`
}
