// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

func (input *Input) SetTrusted(value bool) {
	if input == nil {
		return
	}
	input.Trusted = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Trusted = true
}

func (input *Input) SetRetentionDelete(value bool) {
	if input == nil {
		return
	}
	input.RetentionDelete = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.RetentionDelete = true
}

func (input *Input) SetRetentionCutoff(value time.Time) {
	if input == nil {
		return
	}
	input.RetentionCutoff = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.RetentionCutoff = true
}

func (input *Input) SetExpectedJobID(value string) {
	if input == nil {
		return
	}
	input.ExpectedJobID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExpectedJobID = true
}

func (input *Input) SetExpectedArtifactID(value string) {
	if input == nil {
		return
	}
	input.ExpectedArtifactID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExpectedArtifactID = true
}

func (input *Input) SetEvents(value []*AuditEvent) {
	if input == nil {
		return
	}
	input.Events = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Events = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
