// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// AuditEvent is generated canonical view metadata for writer.
type AuditEvent struct {
	ShouldDelete bool           `json:"shouldDelete,omitempty" sqlx:"-" writer:"delete"`
	EventId      string         `sqlx:"event_id,primaryKey=true,required=true"`
	EventType    string         `sqlx:"event_type,required=true"`
	ArtifactRef  string         `sqlx:"artifact_ref,required=true"`
	Version      int64          `sqlx:"version,required=true"`
	JobId        *string        `sqlx:"job_id"`
	ArtifactId   *string        `sqlx:"artifact_id"`
	ActorId      string         `sqlx:"actor_id,required=true"`
	ActorRef     *string        `sqlx:"actor_ref"`
	OccurredAt   *time.Time     `sqlx:"occurred_at,required=true"`
	MetadataJson []byte         `sqlx:"metadata_json"`
	Has          *AuditEventHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"AuditEventHas"`
}

type AuditEventHas struct {
	ShouldDelete bool
	EventId      bool
	EventType    bool
	ArtifactRef  bool
	Version      bool
	JobId        bool
	ArtifactId   bool
	ActorId      bool
	ActorRef     bool
	OccurredAt   bool
	MetadataJson bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	EventId      string     `sqlx:"event_id,primaryKey=true,required=true"`
	EventType    string     `sqlx:"event_type,required=true"`
	ArtifactRef  string     `sqlx:"artifact_ref,required=true"`
	Version      int64      `sqlx:"version,required=true"`
	JobId        *string    `sqlx:"job_id"`
	ArtifactId   *string    `sqlx:"artifact_id"`
	ActorId      string     `sqlx:"actor_id,required=true"`
	ActorRef     *string    `sqlx:"actor_ref"`
	OccurredAt   *time.Time `sqlx:"occurred_at,required=true"`
	MetadataJson []byte     `sqlx:"metadata_json"`
}

type WriterKeysRow struct {
	EventId string `sqlx:"event_id"`
}
