// Code generated by Datly for writer; DO NOT EDIT.

package write

// Output is the generated output scaffold for writer.
type Output struct {
	Data []*Turn `parameter:"Data,kind=output,in=body,dataType=[]*Turn"`
}
