// Code generated by Datly for reader; DO NOT EDIT.

package read

// ModelCallsOutput is the generated output scaffold for reader.
type ModelCallsOutput struct {
	Data []*ModelCallView `parameter:"Data,kind=output,in=view,dataType=[]*ModelCallView" view:"reader,type=ModelCallView,table=model_call,selectorProjection=true,selectorLimit=true,selectorOffset=true" sql:"uri=datly_modelcall_read_reader:sql/reader.sql"`
}
