// Code generated by Datly for reader; DO NOT EDIT.

package base

// ScheduleOutput is the generated output scaffold for reader.
type ScheduleOutput struct {
	Data []*ScheduleBaseView `parameter:"Data,kind=output,in=view,dataType=[]*ScheduleBaseView" view:"reader,type=ScheduleBaseView,rowLock=schedule t,rowLockOrder=t.id,table=schedule" sql:"uri=datly_schedule_base_reader:sql/reader.sql"`
}
