// Code generated by Datly for reader; DO NOT EDIT.

package base

import (
	time "time"
)

// ScheduleBaseView is generated canonical view metadata for reader.
type ScheduleBaseView struct {
	LeaseUntilRaw   *string    `internal:"true" json:"-" sqlx:"lease_until_raw"`
	AgentRef        string     `sqlx:"agent_ref" json:"agentRef"`
	CreatedAt       time.Time  `sqlx:"created_at" json:"createdAt"`
	Visibility      string     `sqlx:"visibility" json:"visibility"`
	Enabled         bool       `sqlx:"enabled" json:"enabled"`
	Id              string     `sqlx:"id" json:"id"`
	Internal        bool       `sqlx:"internal" json:"internal"`
	Name            string     `sqlx:"name" json:"name"`
	ScheduleType    string     `sqlx:"schedule_type" json:"scheduleType"`
	TimeoutSeconds  int        `sqlx:"timeout_seconds" json:"timeoutSeconds"`
	Timezone        string     `sqlx:"timezone" json:"timezone"`
	Description     *string    `sqlx:"description" json:"description"`
	CreatedByUserId *string    `sqlx:"created_by_user_id" json:"createdByUserId"`
	ConversationId  *string    `sqlx:"conversation_id" json:"conversationId"`
	GoalId          *string    `sqlx:"goal_id" json:"goalId"`
	ModelOverride   *string    `sqlx:"model_override" json:"modelOverride"`
	UserCredUrl     *string    `sqlx:"user_cred_url" json:"userCredUrl"`
	StartAt         *time.Time `sqlx:"start_at" json:"startAt"`
	EndAt           *time.Time `sqlx:"end_at" json:"endAt"`
	CronExpr        *string    `sqlx:"cron_expr" json:"cronExpr"`
	IntervalSeconds *int       `sqlx:"interval_seconds" json:"intervalSeconds"`
	TaskPromptUri   *string    `sqlx:"task_prompt_uri" json:"taskPromptUri"`
	TaskPrompt      *string    `sqlx:"task_prompt" json:"taskPrompt"`
	NextRunAt       *time.Time `sqlx:"next_run_at" json:"nextRunAt"`
	LastRunAt       *time.Time `sqlx:"last_run_at" json:"lastRunAt"`
	LastStatus      *string    `sqlx:"last_status" json:"lastStatus"`
	LastError       *string    `sqlx:"last_error" json:"lastError"`
	LeaseOwner      *string    `sqlx:"lease_owner" json:"leaseOwner"`
	UpdatedAt       *time.Time `sqlx:"updated_at" json:"updatedAt"`
}
