// Code generated by Datly for writer; DO NOT EDIT.

package write

func (input *Input) SetOrphanDetach(value bool) {
	if input == nil {
		return
	}
	input.OrphanDetach = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanDetach = true
}

func (input *Input) SetOrphanColumn(value string) {
	if input == nil {
		return
	}
	input.OrphanColumn = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanColumn = true
}

func (input *Input) SetDetachLinks(value bool) {
	if input == nil {
		return
	}
	input.DetachLinks = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.DetachLinks = true
}

func (input *Input) SetTerminalCleanup(value bool) {
	if input == nil {
		return
	}
	input.TerminalCleanup = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.TerminalCleanup = true
}

func (input *Input) SetDetachMessageIDs(value []string) {
	if input == nil {
		return
	}
	input.DetachMessageIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.DetachMessageIDs = true
}

func (input *Input) SetMessages(value []*Message) {
	if input == nil {
		return
	}
	input.Messages = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Messages = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
