// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// Message is generated canonical view metadata for writer.
type Message struct {
	ShouldDelete         bool        `json:",omitempty" sqlx:"-" writer:"delete"`
	Sequence             *int        `sequenceScope:"turn_id" sequenceOnNull:"allocate" json:",omitempty" sqlx:"sequence"`
	Id                   string      `validate:"required" sqlx:"id,primaryKey"`
	Archived             *int        `json:",omitempty" sqlx:"archived"`
	ConversationId       string      `validate:"required" sqlx:"conversation_id,refTable=conversation,refColumn=id,required=true"`
	TurnId               *string     `json:",omitempty" sqlx:"turn_id,refTable=turn,refColumn=id"`
	CreatedAt            *time.Time  `json:",omitempty" sqlx:"created_at,required=true"`
	UpdatedAt            *time.Time  `json:",omitempty" sqlx:"updated_at"`
	CreatedByUserId      *string     `json:",omitempty" sqlx:"created_by_user_id"`
	Mode                 *string     `json:",omitempty" sqlx:"mode"`
	Role                 string      `validate:"required" sqlx:"role,required=true"`
	Status               *string     `sqlx:"status"`
	Type                 string      `validate:"required" sqlx:"type,required=true"`
	Content              *string     `sqlx:"content"`
	RawContent           *string     `json:",omitempty" sqlx:"raw_content"`
	Summary              *string     `json:",omitempty" sqlx:"summary"`
	ContextSummary       *string     `json:",omitempty" sqlx:"context_summary"`
	EmbeddingIndex       *[]byte     `json:",omitempty" sqlx:"embedding_index"`
	Tags                 *string     `json:",omitempty" sqlx:"tags"`
	Interim              *int        `json:",omitempty" sqlx:"interim,required=true"`
	ElicitationId        *string     `json:",omitempty" sqlx:"elicitation_id"`
	ParentMessageId      *string     `json:",omitempty" sqlx:"parent_message_id"`
	SupersededBy         *string     `json:",omitempty" sqlx:"superseded_by"`
	LinkedConversationId *string     `json:",omitempty" sqlx:"linked_conversation_id"`
	ToolName             *string     `json:",omitempty" sqlx:"tool_name"`
	Narration            *string     `json:",omitempty" sqlx:"preamble"`
	Iteration            *int        `json:",omitempty" sqlx:"iteration"`
	Phase                *string     `json:",omitempty" sqlx:"phase"`
	AttachmentPayloadId  *string     `json:",omitempty" sqlx:"attachment_payload_id,refTable=call_payload,refColumn=id"`
	ElicitationPayloadId *string     `json:",omitempty" sqlx:"elicitation_payload_id,refTable=call_payload,refColumn=id"`
	Has                  *MessageHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"MessageHas"`
}

type MessageHas struct {
	ShouldDelete         bool
	Sequence             bool
	Id                   bool
	Archived             bool
	ConversationId       bool
	TurnId               bool
	CreatedAt            bool
	UpdatedAt            bool
	CreatedByUserId      bool
	Mode                 bool
	Role                 bool
	Status               bool
	Type                 bool
	Content              bool
	RawContent           bool
	Summary              bool
	ContextSummary       bool
	EmbeddingIndex       bool
	Tags                 bool
	Interim              bool
	ElicitationId        bool
	ParentMessageId      bool
	SupersededBy         bool
	LinkedConversationId bool
	ToolName             bool
	Narration            bool
	Iteration            bool
	Phase                bool
	AttachmentPayloadId  bool
	ElicitationPayloadId bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	Sequence             *int       `sequenceScope:"turn_id" sequenceOnNull:"allocate" json:",omitempty" sqlx:"sequence"`
	Id                   string     `validate:"required" sqlx:"id,primaryKey"`
	Archived             *int       `json:",omitempty" sqlx:"archived"`
	ConversationId       string     `validate:"required" sqlx:"conversation_id,refTable=conversation,refColumn=id,required=true"`
	TurnId               *string    `json:",omitempty" sqlx:"turn_id,refTable=turn,refColumn=id"`
	CreatedAt            *time.Time `json:",omitempty" sqlx:"created_at,required=true"`
	UpdatedAt            *time.Time `json:",omitempty" sqlx:"updated_at"`
	CreatedByUserId      *string    `json:",omitempty" sqlx:"created_by_user_id"`
	Mode                 *string    `json:",omitempty" sqlx:"mode"`
	Role                 string     `validate:"required" sqlx:"role,required=true"`
	Status               *string    `sqlx:"status"`
	Type                 string     `validate:"required" sqlx:"type,required=true"`
	Content              *string    `sqlx:"content"`
	RawContent           *string    `json:",omitempty" sqlx:"raw_content"`
	Summary              *string    `json:",omitempty" sqlx:"summary"`
	ContextSummary       *string    `json:",omitempty" sqlx:"context_summary"`
	EmbeddingIndex       *[]byte    `json:",omitempty" sqlx:"embedding_index"`
	Tags                 *string    `json:",omitempty" sqlx:"tags"`
	Interim              *int       `json:",omitempty" sqlx:"interim,required=true"`
	ElicitationId        *string    `json:",omitempty" sqlx:"elicitation_id"`
	ParentMessageId      *string    `json:",omitempty" sqlx:"parent_message_id"`
	SupersededBy         *string    `json:",omitempty" sqlx:"superseded_by"`
	LinkedConversationId *string    `json:",omitempty" sqlx:"linked_conversation_id"`
	ToolName             *string    `json:",omitempty" sqlx:"tool_name"`
	Narration            *string    `json:",omitempty" sqlx:"preamble"`
	Iteration            *int       `json:",omitempty" sqlx:"iteration"`
	Phase                *string    `json:",omitempty" sqlx:"phase"`
	AttachmentPayloadId  *string    `json:",omitempty" sqlx:"attachment_payload_id,refTable=call_payload,refColumn=id"`
	ElicitationPayloadId *string    `json:",omitempty" sqlx:"elicitation_payload_id,refTable=call_payload,refColumn=id"`
}

type WriterKeysRow struct {
	Id string `sqlx:"id"`
}
