// Code generated by Datly for writer; DO NOT EDIT.

package write

// Output is the generated output scaffold for writer.
type Output struct {
	Data        []*Schedule `parameter:"Data,kind=output,in=body,dataType=[]*Schedule"`
	LeaseResult bool        `parameter:"LeaseResult,kind=output,in=leaseResult,dataType=bool"`
}
