// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// Schedule is generated canonical view metadata for writer.
type Schedule struct {
	ShouldDelete    bool         `sqlx:"-" writer:"delete" json:"shouldDelete,omitempty"`
	Id              string       `validate:"required" sqlx:"id,primaryKey" json:"id"`
	Name            string       `validate:"required" json:"name" sqlx:"name,required=true"`
	Visibility      string       `json:"visibility" sqlx:"visibility,required=true"`
	Internal        *bool        `sqlx:"internal,required=true" json:"internal,omitempty"`
	AgentRef        string       `validate:"required" json:"agentRef" sqlx:"agent_ref,required=true"`
	Enabled         bool         `json:"enabled" sqlx:"enabled,required=true"`
	ScheduleType    string       `validate:"required" json:"scheduleType" sqlx:"schedule_type,required=true"`
	Timezone        string       `validate:"required" json:"timezone" sqlx:"timezone,required=true"`
	TimeoutSeconds  int          `json:"timeoutSeconds" sqlx:"timeout_seconds,required=true"`
	Description     *string      `sqlx:"description" json:"description,omitempty"`
	CreatedByUserId *string      `sqlx:"created_by_user_id" json:"createdByUserId,omitempty"`
	ConversationId  *string      `sqlx:"conversation_id" json:"conversationId,omitempty"`
	GoalId          *string      `sqlx:"goal_id" json:"goalId,omitempty"`
	ModelOverride   *string      `sqlx:"model_override" json:"modelOverride,omitempty"`
	UserCredUrl     *string      `sqlx:"user_cred_url" json:"userCredUrl,omitempty"`
	StartAt         *time.Time   `sqlx:"start_at" json:"startAt,omitempty"`
	EndAt           *time.Time   `sqlx:"end_at" json:"endAt,omitempty"`
	CronExpr        *string      `sqlx:"cron_expr" json:"cronExpr,omitempty"`
	IntervalSeconds *int         `sqlx:"interval_seconds" json:"intervalSeconds,omitempty"`
	TaskPromptUri   *string      `sqlx:"task_prompt_uri" json:"taskPromptUri,omitempty"`
	TaskPrompt      *string      `sqlx:"task_prompt" json:"taskPrompt,omitempty"`
	NextRunAt       *time.Time   `sqlx:"next_run_at" json:"nextRunAt,omitempty"`
	LastRunAt       *time.Time   `sqlx:"last_run_at" json:"lastRunAt,omitempty"`
	LastStatus      *string      `sqlx:"last_status" json:"lastStatus,omitempty"`
	LastError       *string      `sqlx:"last_error" json:"lastError,omitempty"`
	LeaseOwner      *string      `sqlx:"lease_owner" json:"leaseOwner,omitempty"`
	LeaseUntil      *time.Time   `sqlx:"lease_until" json:"leaseUntil,omitempty"`
	CreatedAt       *time.Time   `sqlx:"created_at,required=true" json:"createdAt,omitempty"`
	UpdatedAt       *time.Time   `sqlx:"updated_at" json:"updatedAt,omitempty"`
	Has             *ScheduleHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"ScheduleHas"`
}

type ScheduleHas struct {
	ShouldDelete    bool
	Id              bool
	Name            bool
	Visibility      bool
	Internal        bool
	AgentRef        bool
	Enabled         bool
	ScheduleType    bool
	Timezone        bool
	TimeoutSeconds  bool
	Description     bool
	CreatedByUserId bool
	ConversationId  bool
	GoalId          bool
	ModelOverride   bool
	UserCredUrl     bool
	StartAt         bool
	EndAt           bool
	CronExpr        bool
	IntervalSeconds bool
	TaskPromptUri   bool
	TaskPrompt      bool
	NextRunAt       bool
	LastRunAt       bool
	LastStatus      bool
	LastError       bool
	LeaseOwner      bool
	LeaseUntil      bool
	CreatedAt       bool
	UpdatedAt       bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	Id              string     `validate:"required" sqlx:"id,primaryKey" json:"id"`
	Name            string     `validate:"required" json:"name" sqlx:"name,required=true"`
	Visibility      string     `json:"visibility" sqlx:"visibility,required=true"`
	Internal        *bool      `sqlx:"internal,required=true" json:"internal,omitempty"`
	AgentRef        string     `validate:"required" json:"agentRef" sqlx:"agent_ref,required=true"`
	Enabled         bool       `json:"enabled" sqlx:"enabled,required=true"`
	ScheduleType    string     `validate:"required" json:"scheduleType" sqlx:"schedule_type,required=true"`
	Timezone        string     `validate:"required" json:"timezone" sqlx:"timezone,required=true"`
	TimeoutSeconds  int        `json:"timeoutSeconds" sqlx:"timeout_seconds,required=true"`
	Description     *string    `sqlx:"description" json:"description,omitempty"`
	CreatedByUserId *string    `sqlx:"created_by_user_id" json:"createdByUserId,omitempty"`
	ConversationId  *string    `sqlx:"conversation_id" json:"conversationId,omitempty"`
	GoalId          *string    `sqlx:"goal_id" json:"goalId,omitempty"`
	ModelOverride   *string    `sqlx:"model_override" json:"modelOverride,omitempty"`
	UserCredUrl     *string    `sqlx:"user_cred_url" json:"userCredUrl,omitempty"`
	StartAt         *time.Time `sqlx:"start_at" json:"startAt,omitempty"`
	EndAt           *time.Time `sqlx:"end_at" json:"endAt,omitempty"`
	CronExpr        *string    `sqlx:"cron_expr" json:"cronExpr,omitempty"`
	IntervalSeconds *int       `sqlx:"interval_seconds" json:"intervalSeconds,omitempty"`
	TaskPromptUri   *string    `sqlx:"task_prompt_uri" json:"taskPromptUri,omitempty"`
	TaskPrompt      *string    `sqlx:"task_prompt" json:"taskPrompt,omitempty"`
	NextRunAt       *time.Time `sqlx:"next_run_at" json:"nextRunAt,omitempty"`
	LastRunAt       *time.Time `sqlx:"last_run_at" json:"lastRunAt,omitempty"`
	LastStatus      *string    `sqlx:"last_status" json:"lastStatus,omitempty"`
	LastError       *string    `sqlx:"last_error" json:"lastError,omitempty"`
	LeaseOwner      *string    `sqlx:"lease_owner" json:"leaseOwner,omitempty"`
	LeaseUntil      *time.Time `sqlx:"lease_until" json:"leaseUntil,omitempty"`
	CreatedAt       *time.Time `sqlx:"created_at,required=true" json:"createdAt,omitempty"`
	UpdatedAt       *time.Time `sqlx:"updated_at" json:"updatedAt,omitempty"`
}

type WriterKeysRow struct {
	Id string `sqlx:"id"`
}
