// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	predicate "github.com/viant/agently-core/internal/datly/predicate"
)

func (input *Input) SetInternal(value bool) {
	if input == nil {
		return
	}
	input.Internal = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Internal = true
}

func (input *Input) SetOwnerSubject(value *string) {
	if input == nil {
		return
	}
	input.OwnerSubject = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OwnerSubject = true
}

func (input *Input) SetJobID(value string) {
	if input == nil {
		return
	}
	input.JobID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.JobID = true
}

func (input *Input) SetJobIDs(value []string) {
	if input == nil {
		return
	}
	input.JobIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.JobIDs = true
}

func (input *Input) SetOwnerID(value string) {
	if input == nil {
		return
	}
	input.OwnerID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OwnerID = true
}

func (input *Input) SetConversationID(value string) {
	if input == nil {
		return
	}
	input.ConversationID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ConversationID = true
}

func (input *Input) SetConversationIDs(value []string) {
	if input == nil {
		return
	}
	input.ConversationIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ConversationIDs = true
}

func (input *Input) SetReportRunID(value string) {
	if input == nil {
		return
	}
	input.ReportRunID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ReportRunID = true
}

func (input *Input) SetReportRunIDs(value []string) {
	if input == nil {
		return
	}
	input.ReportRunIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ReportRunIDs = true
}

func (input *Input) SetExportRequestID(value string) {
	if input == nil {
		return
	}
	input.ExportRequestID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExportRequestID = true
}

func (input *Input) SetArtifactRef(value string) {
	if input == nil {
		return
	}
	input.ArtifactRef = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ArtifactRef = true
}

func (input *Input) SetStatus(value string) {
	if input == nil {
		return
	}
	input.Status = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Status = true
}

func (input *Input) SetTechnicalRetention(value *predicate.TechnicalRetention) {
	if input == nil {
		return
	}
	input.TechnicalRetention = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.TechnicalRetention = true
}

func (input *Input) SetLockRows(value bool) {
	if input == nil {
		return
	}
	input.LockRows = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.LockRows = true
}
