// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	predicate "github.com/viant/agently-core/internal/datly/predicate"
)

// Input is the generated input scaffold for reader.
type Input struct {
	Internal           bool                          `parameter:"Internal,kind=reportaccess,in=internal,dataType=bool,required=true"`
	OwnerSubject       *string                       `parameter:"OwnerSubject,kind=visibility,in=subject,dataType=*string,required=true"`
	JobID              string                        `parameter:"JobID,kind=query,in=jobId,dataType=string,required=false" predicate:"equal,j,job_id"`
	JobIDs             []string                      `parameter:"JobIDs,kind=query,in=jobIds,dataType=[]string,required=false" predicate:"in,j,job_id"`
	OwnerID            string                        `parameter:"OwnerID,kind=query,in=ownerId,dataType=string,required=false" predicate:"equal,j,owner_id"`
	ConversationID     string                        `parameter:"ConversationID,kind=query,in=conversationId,dataType=string,required=false" predicate:"equal,j,conversation_id"`
	ConversationIDs    []string                      `parameter:"ConversationIDs,kind=query,in=conversationIds,dataType=[]string,required=false" predicate:"in,j,conversation_id"`
	ReportRunID        string                        `parameter:"ReportRunID,kind=query,in=reportRunId,dataType=string,required=false" predicate:"equal,j,report_run_id"`
	ReportRunIDs       []string                      `parameter:"ReportRunIDs,kind=query,in=reportRunIds,dataType=[]string,required=false" predicate:"in,j,report_run_id"`
	ExportRequestID    string                        `parameter:"ExportRequestID,kind=query,in=exportRequestId,dataType=string,required=false" predicate:"equal,j,export_request_id"`
	ArtifactRef        string                        `parameter:"ArtifactRef,kind=query,in=artifactRef,dataType=string,required=false" predicate:"equal,j,artifact_ref"`
	Status             string                        `parameter:"Status,kind=query,in=status,dataType=string,required=false" predicate:"equal,j,status"`
	TechnicalRetention *predicate.TechnicalRetention `parameter:"TechnicalRetention,kind=technicalmaintenance,in=policy,dataType=*predicate.TechnicalRetention,required=false" predicate:"handler,github.com/viant/agently-core/internal/datly/predicate.TechnicalReportJobRetention"`
	LockRows           bool                          `parameter:"LockRows,kind=reportaccess,in=lock,dataType=bool,required=false"`
	Has                *InputHas                     `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Internal           bool
	OwnerSubject       bool
	JobID              bool
	JobIDs             bool
	OwnerID            bool
	ConversationID     bool
	ConversationIDs    bool
	ReportRunID        bool
	ReportRunIDs       bool
	ExportRequestID    bool
	ArtifactRef        bool
	Status             bool
	TechnicalRetention bool
	LockRows           bool
}
