// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

// Run is generated canonical view metadata for reader.
type Run struct {
	RunKey     *string    `sqlx:"id,primaryKey=true,required=true" json:"runKey"`
	RunId      string     `sqlx:"protocol_run_id" json:"runId"`
	Revision   int64      `sqlx:"protocol_revision,required=true" json:"revision"`
	LeaseUntil *time.Time `sqlx:"protocol_lease_until" json:"leaseUntil"`
	ThreadId   *string    `sqlx:"conversation_id,refTable=conversation,refColumn=id" json:"threadId"`
	Status     *string    `sqlx:"protocol_status" json:"status"`
}
