// Code generated by Datly for write; DO NOT EDIT.

package write

// LinkState is generated canonical view metadata for write.
type LinkState struct {
	ShouldDelete bool          `json:",omitempty" sqlx:"-" writer:"delete"`
	StateHash    string        `sqlx:"state_hash,primaryKey=false,required=true"`
	FlowHash     string        `sqlx:"flow_hash,primaryKey=true,required=true"`
	UserId       string        `sqlx:"user_id,required=true"`
	SessionHash  string        `sqlx:"session_hash,required=true"`
	Provider     string        `sqlx:"provider,required=true"`
	ExpiresAt    string        `sqlx:"expires_at,required=true"`
	ConsumedAt   *string       `sqlx:"consumed_at"`
	CreatedAt    string        `sqlx:"created_at,required=true"`
	Now          string        `sqlx:"-"`
	Has          *LinkStateHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"LinkStateHas"`
}

type LinkStateHas struct {
	ShouldDelete bool
	StateHash    bool
	FlowHash     bool
	UserId       bool
	SessionHash  bool
	Provider     bool
	ExpiresAt    bool
	ConsumedAt   bool
	CreatedAt    bool
}

// CurrentWriteView is generated canonical view metadata for write.
type CurrentWriteView struct {
	StateHash   string  `sqlx:"state_hash,primaryKey=false,required=true"`
	FlowHash    string  `sqlx:"flow_hash,primaryKey=true,required=true"`
	UserId      string  `sqlx:"user_id,required=true"`
	SessionHash string  `sqlx:"session_hash,required=true"`
	Provider    string  `sqlx:"provider,required=true"`
	ExpiresAt   string  `sqlx:"expires_at,required=true"`
	ConsumedAt  *string `sqlx:"consumed_at"`
	CreatedAt   string  `sqlx:"created_at,required=true"`
	Now         string  `sqlx:"now"`
}

type WriteKeysRow struct {
	FlowHash string `sqlx:"flow_hash"`
}
