package a2a

import (
	"encoding/json"
	"time"
)

// Role represents the sender role in a message.
type Role string

const (
	RoleUser  Role = "user"
	RoleAgent Role = "agent"
)

// TaskState represents the state of a task.
type TaskState string

const (
	TaskStatePending      TaskState = "pending"
	TaskStateRunning      TaskState = "running"
	TaskStateCompleted    TaskState = "completed"
	TaskStateFailed       TaskState = "failed"
	TaskStateCanceled     TaskState = "canceled"
	TaskStateBlocked      TaskState = "blocked"
	TaskStateAuthRequired TaskState = "auth-required"
)

// IsTerminal returns true if the state is a final state.
func (s TaskState) IsTerminal() bool {
	return s == TaskStateCompleted || s == TaskStateFailed || s == TaskStateCanceled
}

// Part represents a content part in a message.
type Part struct {
	Type     string                 `json:"type"`
	Text     string                 `json:"text,omitempty"`
	URI      string                 `json:"uri,omitempty"`
	MimeType string                 `json:"mimeType,omitempty"`
	Data     map[string]interface{} `json:"data,omitempty"`
}

// Message represents a communication turn in A2A.
type Message struct {
	Role  Role            `json:"role"`
	Parts []Part          `json:"parts"`
	Raw   json.RawMessage `json:"-"`
}

// TaskStatus tracks task progress.
type TaskStatus struct {
	State     TaskState `json:"state"`
	Message   *Part     `json:"message,omitempty"`
	Error     *string   `json:"error,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Task is the A2A protocol response envelope. It is not persisted —
// for the server side the conversation is the state, for the client side
// the task is ephemeral (result of a tool call).
type Task struct {
	ID        string     `json:"id"`
	ContextID string     `json:"contextId,omitempty"`
	Status    TaskStatus `json:"status"`
	Artifacts []Artifact `json:"artifacts,omitempty"`
}

// Touch sets the task state and updates the timestamp.
func (t *Task) Touch(state TaskState) {
	t.Status.State = state
	t.Status.UpdatedAt = time.Now().UTC()
}

// Artifact is an output generated by a task.
type Artifact struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	Parts     []Part    `json:"parts"`
}

// AgentCard describes an A2A agent's identity, capabilities, and endpoints.
type AgentCard struct {
	Name           string                 `json:"name"`
	Title          string                 `json:"title,omitempty"`
	Version        string                 `json:"version,omitempty"`
	Description    string                 `json:"description,omitempty"`
	Endpoints      map[string]string      `json:"endpoints,omitempty"`
	Authentication map[string]interface{} `json:"authentication,omitempty"`
	Capabilities   *AgentCapabilities     `json:"capabilities,omitempty"`
}

// AgentCapabilities describes what an A2A agent supports.
type AgentCapabilities struct {
	Streaming              bool `json:"streaming,omitempty"`
	PushNotifications      bool `json:"pushNotifications,omitempty"`
	StateTransitionHistory bool `json:"stateTransitionHistory,omitempty"`
}

// SendMessageRequest is the input for the message/send operation.
// Supports both single Message (legacy) and Messages (batch) fields.
type SendMessageRequest struct {
	Messages  []Message `json:"messages,omitempty"`
	Message   *Message  `json:"message,omitempty"`
	TaskID    string    `json:"taskId,omitempty"`
	ContextID string    `json:"contextId,omitempty"`
}

// EffectiveMessages returns Messages if set, otherwise wraps Message into a slice.
func (r *SendMessageRequest) EffectiveMessages() []Message {
	if len(r.Messages) > 0 {
		return r.Messages
	}
	if r.Message != nil {
		return []Message{*r.Message}
	}
	return nil
}

// SendMessageResponse is the output for the message/send operation.
type SendMessageResponse struct {
	Task Task `json:"task"`
}

// TaskStatusUpdateEvent is a streaming event for task status changes.
type TaskStatusUpdateEvent struct {
	TaskID    string                 `json:"taskId"`
	ContextID string                 `json:"contextId,omitempty"`
	Kind      string                 `json:"kind"` // "status-update"
	Status    TaskStatus             `json:"status"`
	Final     bool                   `json:"final"`
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
}

// TaskArtifactUpdateEvent is a streaming event for task artifact delivery.
type TaskArtifactUpdateEvent struct {
	TaskID    string                 `json:"taskId"`
	ContextID string                 `json:"contextId,omitempty"`
	Kind      string                 `json:"kind"` // "artifact-update"
	Artifact  Artifact               `json:"artifact"`
	Append    bool                   `json:"append,omitempty"`
	LastChunk bool                   `json:"lastChunk,omitempty"`
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
}

// NewStatusEvent creates a TaskStatusUpdateEvent from a task.
func NewStatusEvent(task *Task, final bool) *TaskStatusUpdateEvent {
	return &TaskStatusUpdateEvent{
		TaskID:    task.ID,
		ContextID: task.ContextID,
		Kind:      "status-update",
		Status:    task.Status,
		Final:     final,
	}
}

// NewArtifactEvent creates a TaskArtifactUpdateEvent from a task and artifact.
func NewArtifactEvent(task *Task, art Artifact, appendFlag, lastChunk bool) *TaskArtifactUpdateEvent {
	return &TaskArtifactUpdateEvent{
		TaskID:    task.ID,
		ContextID: task.ContextID,
		Kind:      "artifact-update",
		Artifact:  art,
		Append:    appendFlag,
		LastChunk: lastChunk,
	}
}

// ExternalSpec describes an external A2A agent for client-side calls.
type ExternalSpec struct {
	ID         string            `yaml:"id" json:"id"`
	Enabled    *bool             `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	JSONRPCURL string            `yaml:"jsonrpcURL" json:"jsonrpcURL"`
	StreamURL  string            `yaml:"streamURL,omitempty" json:"streamURL,omitempty"`
	Headers    map[string]string `yaml:"headers,omitempty" json:"headers,omitempty"`
	Directory  ExternalDirectory `yaml:"directory,omitempty" json:"directory,omitempty"`
}

// IsEnabled returns true if the spec is enabled (default true if nil).
func (s *ExternalSpec) IsEnabled() bool {
	return s.Enabled == nil || *s.Enabled
}

// ExternalDirectory holds display metadata for an external A2A agent.
type ExternalDirectory struct {
	Name        string   `yaml:"name,omitempty" json:"name,omitempty"`
	Description string   `yaml:"description,omitempty" json:"description,omitempty"`
	Tags        []string `yaml:"tags,omitempty" json:"tags,omitempty"`
	Priority    int      `yaml:"priority,omitempty" json:"priority,omitempty"`
}

// JSONRPCRequest is a JSON-RPC 2.0 request for A2A.
type JSONRPCRequest struct {
	JSONRPC string          `json:"jsonrpc"`
	Method  string          `json:"method"`
	Params  json.RawMessage `json:"params,omitempty"`
	ID      interface{}     `json:"id,omitempty"`
}

// JSONRPCResponse is a JSON-RPC 2.0 response for A2A.
type JSONRPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *JSONRPCError   `json:"error,omitempty"`
	ID      interface{}     `json:"id,omitempty"`
}

// JSONRPCError is a JSON-RPC 2.0 error object.
type JSONRPCError struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}
