// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

// ConversationRequest is the public transport input projection of reader.
type ConversationRequest struct {
	Id                       string                  `parameter:"Id,kind=path,in=id,dataType=string,required=false" predicate:"equal,t,id" json:"id"`
	Ids                      []string                `parameter:"Ids,kind=query,in=ids,dataType=[]string,required=false" predicate:"in,t,id" json:"ids"`
	Since                    string                  `parameter:"Since,kind=query,in=since,dataType=string,required=false" predicate:"expr,group=1,'EXISTS (SELECT 1 FROM turn a WHERE a.id = ? AND (t.created_at >= a.created_at OR (t.queue_seq IS NOT NULL AND a.queue_seq IS NOT NULL AND t.queue_seq >= a.queue_seq)))'" json:"since"`
	IncludeTranscript        bool                    `parameter:"IncludeTranscript,kind=query,in=includeTranscript,dataType=bool,value=true,required=false" predicate:"expr,group=1,?" json:"includeTranscript"`
	IncludeModelCal          bool                    `parameter:"IncludeModelCal,kind=query,in=includeModelCall,dataType=bool,value=false,required=false" predicate:"expr,group=2,?" json:"includeModelCal"`
	IncludeToolCall          bool                    `parameter:"IncludeToolCall,kind=query,in=includeToolCall,dataType=bool,value=false,required=false" predicate:"expr,group=3,?" json:"includeToolCall"`
	AgentId                  string                  `parameter:"AgentId,kind=query,in=agentId,dataType=string,required=false" predicate:"expr,'t.agent_id = ?'" json:"agentId"`
	ParentId                 string                  `parameter:"ParentId,kind=query,in=parentId,dataType=string,required=false" predicate:"expr,'t.conversation_parent_id = ?'" json:"parentId"`
	ParentTurnId             string                  `parameter:"ParentTurnId,kind=query,in=parentTurnId,dataType=string,required=false" predicate:"expr,'t.conversation_parent_turn_id = ?'" json:"parentTurnId"`
	ParentIds                []string                `parameter:"ParentIds,kind=query,in=parentIds,dataType=[]string,required=false" predicate:"in,t,conversation_parent_id" json:"parentIds"`
	ParentTurnIds            []string                `parameter:"ParentTurnIds,kind=query,in=parentTurnIds,dataType=[]string,required=false" predicate:"in,t,conversation_parent_turn_id" json:"parentTurnIds"`
	ExcludeChildren          bool                    `parameter:"ExcludeChildren,kind=query,in=excludeChildren,dataType=bool,required=false" predicate:"expr,(NOT ? OR t.conversation_parent_id IS NULL)" json:"excludeChildren"`
	ExcludeScheduled         bool                    `parameter:"ExcludeScheduled,kind=query,in=excludeScheduled,dataType=bool,required=false" predicate:"expr,(NOT ? OR t.schedule_id IS NULL)" json:"excludeScheduled"`
	ScheduleId               string                  `parameter:"ScheduleId,kind=query,in=scheduleId,dataType=string,required=false" predicate:"expr,'t.schedule_id = ?'" json:"scheduleId"`
	ScheduleRunId            string                  `parameter:"ScheduleRunId,kind=query,in=scheduleRunId,dataType=string,required=false" predicate:"expr,'t.schedule_run_id = ?'" json:"scheduleRunId"`
	Query                    string                  `parameter:"Query,kind=query,in=q,dataType=string,required=false" predicate:"handler,github.com/viant/agently-core/internal/datly/predicate.ConversationSearch" json:"query"`
	StatusFilter             string                  `parameter:"StatusFilter,kind=query,in=status,dataType=string,required=false" predicate:"expr,'t.status = ?'" json:"statusFilter"`
	HasScheduleId            bool                    `parameter:"HasScheduleId,kind=query,in=hasScheduleId,dataType=bool,required=false" predicate:"expr,(NOT ? OR t.schedule_id IS NOT NULL)" json:"hasScheduleId"`
	CreatedSince             time.Time               `parameter:"CreatedSince,kind=query,in=createdSince,dataType=time.Time,required=false" predicate:"greater_or_equal,t,created_at" json:"createdSince"`
	CreatedBefore            time.Time               `parameter:"CreatedBefore,kind=query,in=createdBefore,dataType=time.Time,required=false" predicate:"less_or_equal,t,created_at" json:"createdBefore"`
	CursorBefore             string                  `parameter:"CursorBefore,kind=query,in=cursorBefore,dataType=string,required=false" predicate:"expr,'EXISTS (SELECT 1 FROM conversation x WHERE x.id = ? AND (COALESCE(t.last_activity,t.updated_at,t.created_at) < COALESCE(x.last_activity,x.updated_at,x.created_at) OR (COALESCE(t.last_activity,t.updated_at,t.created_at) = COALESCE(x.last_activity,x.updated_at,x.created_at) AND t.id < x.id)))'" json:"cursorBefore"`
	CursorAfter              string                  `parameter:"CursorAfter,kind=query,in=cursorAfter,dataType=string,required=false" predicate:"expr,'EXISTS (SELECT 1 FROM conversation x WHERE x.id = ? AND (COALESCE(t.last_activity,t.updated_at,t.created_at) > COALESCE(x.last_activity,x.updated_at,x.created_at) OR (COALESCE(t.last_activity,t.updated_at,t.created_at) = COALESCE(x.last_activity,x.updated_at,x.created_at) AND t.id > x.id)))'" json:"cursorAfter"`
	MaintenanceBefore        time.Time               `parameter:"MaintenanceBefore,kind=query,in=maintenanceBefore,dataType=time.Time,required=false" json:"maintenanceBefore"`
	MaintenanceBeforeSecond  string                  `parameter:"MaintenanceBeforeSecond,kind=query,in=maintenanceBeforeSecond,dataType=string,required=false" json:"maintenanceBeforeSecond"`
	MaintenanceBeforeNano    int64                   `parameter:"MaintenanceBeforeNano,kind=query,in=maintenanceBeforeNano,dataType=int64,required=false" json:"maintenanceBeforeNano"`
	MaintenanceAfterNano     int64                   `parameter:"MaintenanceAfterNano,kind=query,in=maintenanceAfterNano,dataType=int64,required=false" json:"maintenanceAfterNano"`
	MaintenanceAfterActivity string                  `parameter:"MaintenanceAfterActivity,kind=query,in=maintenanceAfterActivity,dataType=string,required=false" json:"maintenanceAfterActivity"`
	MaintenanceAfterRootId   string                  `parameter:"MaintenanceAfterRootId,kind=query,in=maintenanceAfterRootId,dataType=string,required=false" json:"maintenanceAfterRootId"`
	Fields                   []string                `parameter:"Fields,kind=query,in=fields,dataType=[]string,required=false,cacheable=false" querySelector:"view=reader,property=fields" json:"fields"`
	Limit                    int                     `parameter:"Limit,kind=query,in=limit,dataType=int,required=false,cacheable=false" querySelector:"view=reader,property=limit" json:"limit"`
	Has                      *ConversationRequestHas `setMarker:"true" typeName:"ConversationRequestHas" json:"-" sqlx:"-"`
}

type ConversationRequestHas struct {
	Id                       bool
	Ids                      bool
	Since                    bool
	IncludeTranscript        bool
	IncludeModelCal          bool
	IncludeToolCall          bool
	AgentId                  bool
	ParentId                 bool
	ParentTurnId             bool
	ParentIds                bool
	ParentTurnIds            bool
	ExcludeChildren          bool
	ExcludeScheduled         bool
	ScheduleId               bool
	ScheduleRunId            bool
	Query                    bool
	StatusFilter             bool
	HasScheduleId            bool
	CreatedSince             bool
	CreatedBefore            bool
	CursorBefore             bool
	CursorAfter              bool
	MaintenanceBefore        bool
	MaintenanceBeforeSecond  bool
	MaintenanceBeforeNano    bool
	MaintenanceAfterNano     bool
	MaintenanceAfterActivity bool
	MaintenanceAfterRootId   bool
	Fields                   bool
	Limit                    bool
}
