// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	codec "github.com/viant/agently-core/internal/datly/codec"
	time "time"
)

// ConversationView is generated canonical view metadata for reader.
type ConversationView struct {
	CreatedAtRaw             *string           `internal:"true" json:"-" sqlx:"created_at_raw"`
	ActivityRaw              *string           `internal:"true" json:"-" sqlx:"activity_raw"`
	ListMode                 bool              `json:"-" sqlx:"list_mode"`
	LastTurnId               *string           `sqlx:"last_turn_id"`
	Stage                    string            `sqlx:"stage"`
	Id                       string            `sqlx:"id,primaryKey=true"`
	Summary                  *string           `sqlx:"summary"`
	LastActivity             *time.Time        `sqlx:"last_activity"`
	UsageInputTokens         *int              `sqlx:"usage_input_tokens"`
	UsageOutputTokens        *int              `sqlx:"usage_output_tokens"`
	UsageEmbeddingTokens     *int              `sqlx:"usage_embedding_tokens"`
	CreatedAt                time.Time         `sqlx:"created_at,required=true"`
	UpdatedAt                *time.Time        `sqlx:"updated_at"`
	CreatedByUserId          *string           `sqlx:"created_by_user_id"`
	AgentId                  *string           `sqlx:"agent_id"`
	DefaultModelProvider     *string           `sqlx:"default_model_provider"`
	DefaultModel             *string           `sqlx:"default_model"`
	DefaultModelParams       *string           `sqlx:"default_model_params"`
	Title                    *string           `sqlx:"title"`
	ConversationParentId     *string           `sqlx:"conversation_parent_id"`
	ConversationParentTurnId *string           `sqlx:"conversation_parent_turn_id"`
	Metadata                 *string           `sqlx:"metadata"`
	Visibility               string            `sqlx:"visibility,required=true"`
	Shareable                int               `sqlx:"shareable,required=true"`
	Status                   *string           `sqlx:"status"`
	Scheduled                *int              `sqlx:"scheduled"`
	ScheduleId               *string           `sqlx:"schedule_id"`
	ScheduleRunId            *string           `sqlx:"schedule_run_id"`
	ScheduleKind             *string           `sqlx:"schedule_kind"`
	ScheduleTimezone         *string           `sqlx:"schedule_timezone"`
	ScheduleCronExpr         *string           `sqlx:"schedule_cron_expr"`
	ExternalTaskRef          *string           `sqlx:"external_task_ref"`
	Transcript               []*TranscriptView `view:"transcript,type=TranscriptView,table=turn" on:"Id:conversation.id=ConversationId:transcript.conversation_id" json:"transcript" sql:"uri=datly_conversation_read_reader:sql/transcript.sql"`
	Usage                    *UsageView        `view:"usage,type=UsageView,table=model_call" on:"Id:conversation.id=ConversationId:usage.conversation_id" json:"usage" sql:"uri=datly_conversation_read_reader:sql/usage.sql"`
}

// TranscriptView is generated canonical view metadata for reader.
type TranscriptView struct {
	ElapsedInSec          int            `sqlx:"elapsedInSec"`
	Stage                 string         `sqlx:"stage"`
	Id                    string         `sqlx:"id,primaryKey=true"`
	ConversationId        string         `sqlx:"conversation_id,refTable=conversation,refColumn=id,required=true"`
	CreatedAt             time.Time      `sqlx:"created_at,required=true"`
	QueueSeq              *int           `sqlx:"queue_seq"`
	Origin                *string        `sqlx:"origin"`
	GoalId                *string        `sqlx:"goal_id"`
	StatusReason          *string        `sqlx:"status_reason"`
	Status                string         `sqlx:"status,required=true"`
	ErrorMessage          *string        `sqlx:"error_message"`
	StartedByMessageId    *string        `sqlx:"started_by_message_id"`
	RetryOf               *string        `sqlx:"retry_of"`
	AgentIdUsed           *string        `sqlx:"agent_id_used"`
	AgentConfigUsedId     *string        `sqlx:"agent_config_used_id"`
	ModelOverrideProvider *string        `sqlx:"model_override_provider"`
	ModelOverride         *string        `sqlx:"model_override"`
	ModelParamsOverride   *string        `sqlx:"model_params_override"`
	RunId                 *string        `sqlx:"run_id"`
	Message               []*MessageView `view:"message,type=MessageView,table=message" on:"Id:transcript.id=TurnId:message.turn_id" json:"message" sql:"uri=datly_conversation_read_reader:sql/message.sql"`
}

// MessageView is generated canonical view metadata for reader.
type MessageView struct {
	Elicitation          codec.JSON               `sqlx:"ELICITATION"`
	Id                   string                   `sqlx:"id,primaryKey=true"`
	ConversationId       string                   `sqlx:"conversation_id,refTable=conversation,refColumn=id,required=true"`
	TurnId               *string                  `sqlx:"turn_id,refTable=turn,refColumn=id"`
	Archived             *int                     `sqlx:"archived"`
	Sequence             *int                     `sqlx:"sequence"`
	CreatedAt            time.Time                `sqlx:"created_at,required=true"`
	UpdatedAt            *time.Time               `sqlx:"updated_at"`
	CreatedByUserId      *string                  `sqlx:"created_by_user_id"`
	Status               *string                  `sqlx:"status"`
	Mode                 *string                  `sqlx:"mode"`
	Role                 string                   `sqlx:"role,required=true"`
	Type                 string                   `sqlx:"type,required=true"`
	Content              *string                  `sqlx:"content"`
	RawContent           *string                  `sqlx:"raw_content"`
	Summary              *string                  `sqlx:"summary"`
	ContextSummary       *string                  `sqlx:"context_summary"`
	Tags                 *string                  `sqlx:"tags"`
	Interim              int                      `sqlx:"interim,required=true"`
	ElicitationId        *string                  `sqlx:"elicitation_id"`
	ParentMessageId      *string                  `sqlx:"parent_message_id"`
	SupersededBy         *string                  `sqlx:"superseded_by"`
	LinkedConversationId *string                  `sqlx:"linked_conversation_id"`
	AttachmentPayloadId  *string                  `sqlx:"attachment_payload_id,refTable=call_payload,refColumn=id"`
	ElicitationPayloadId *string                  `sqlx:"elicitation_payload_id,refTable=call_payload,refColumn=id"`
	ToolName             *string                  `sqlx:"tool_name"`
	EmbeddingIndex       *string                  `sqlx:"embedding_index"`
	Narration            *string                  `sqlx:"preamble"`
	Iteration            *int                     `sqlx:"iteration"`
	Phase                *string                  `sqlx:"phase"`
	MessageToolCall      *MessageToolCallView     `view:"messageToolCall,type=MessageToolCallView,table=tool_call" on:"Id:message.id=MessageId:messageToolCall.message_id" json:"messageToolCall" sql:"uri=datly_conversation_read_reader:sql/message_tool_call.sql"`
	ToolMessage          []*ToolMessageView       `view:"toolMessage,type=ToolMessageView,table=message" on:"Id:message.id=ParentMessageId:toolMessage.parent_message_id" json:"toolMessage" sql:"uri=datly_conversation_read_reader:sql/tool_message.sql"`
	UserElicitationData  *UserElicitationDataView `view:"userElicitationData,type=UserElicitationDataView,table=message" on:"Id:message.id=MessageId:userElicitationData.message_id" json:"userElicitationData" sql:"uri=datly_conversation_read_reader:sql/user_elicitation_data.sql"`
	LinkedConversation   *LinkedConversationView  `view:"linkedConversation,type=LinkedConversationView,table=conversation" on:"LinkedConversationId:message.linked_conversation_id=Id:linkedConversation.id" json:"linkedConversation" sql:"uri=datly_conversation_read_reader:sql/linked_conversation.sql"`
	Attachment           []*AttachmentView        `view:"attachment,type=AttachmentView,table=message" on:"Id:message.id=ParentMessageId:attachment.parent_message_id" json:"attachment" sql:"uri=datly_conversation_read_reader:sql/attachment.sql"`
	ModelCall            *ModelCallView           `view:"modelCall,type=ModelCallView,table=model_call" on:"Id:message.id=MessageId:modelCall.message_id" json:"modelCall" sql:"uri=datly_conversation_read_reader:sql/model_call.sql"`
}

// MessageToolCallView is generated canonical view metadata for reader.
type MessageToolCallView struct {
	MessageSequence        *int                        `sqlx:"message_sequence"`
	MessageId              string                      `sqlx:"message_id,refTable=message,refColumn=id,primaryKey=true"`
	TurnId                 *string                     `sqlx:"turn_id,refTable=turn,refColumn=id"`
	OpId                   string                      `sqlx:"op_id,required=true"`
	Attempt                int                         `sqlx:"attempt,required=true"`
	ToolName               string                      `sqlx:"tool_name,required=true"`
	ToolKind               string                      `sqlx:"tool_kind,required=true"`
	Status                 string                      `sqlx:"status,required=true"`
	RequestHash            *string                     `sqlx:"request_hash"`
	ErrorCode              *string                     `sqlx:"error_code"`
	ErrorMessage           *string                     `sqlx:"error_message"`
	Retriable              *int                        `sqlx:"retriable"`
	StartedAt              *time.Time                  `sqlx:"started_at"`
	CompletedAt            *time.Time                  `sqlx:"completed_at"`
	LatencyMs              *int                        `sqlx:"latency_ms"`
	Cost                   *float64                    `sqlx:"cost"`
	TraceId                *string                     `sqlx:"trace_id"`
	SpanId                 *string                     `sqlx:"span_id"`
	RequestPayloadId       *string                     `sqlx:"request_payload_id,refTable=call_payload,refColumn=id"`
	ResponsePayloadId      *string                     `sqlx:"response_payload_id,refTable=call_payload,refColumn=id"`
	RunId                  *string                     `sqlx:"run_id"`
	Iteration              *int                        `sqlx:"iteration"`
	MessageRequestPayload  *MessageRequestPayloadView  `view:"messageRequestPayload,type=MessageRequestPayloadView,table=call_payload" on:"RequestPayloadId:messageToolCall.request_payload_id=Id:messageRequestPayload.id" json:"messageRequestPayload" sql:"uri=datly_conversation_read_reader:sql/message_request_payload.sql"`
	MessageResponsePayload *MessageResponsePayloadView `view:"messageResponsePayload,type=MessageResponsePayloadView,table=call_payload" on:"ResponsePayloadId:messageToolCall.response_payload_id=Id:messageResponsePayload.id" json:"messageResponsePayload" sql:"uri=datly_conversation_read_reader:sql/message_response_payload.sql"`
}

// MessageRequestPayloadView is generated canonical view metadata for reader.
type MessageRequestPayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// MessageResponsePayloadView is generated canonical view metadata for reader.
type MessageResponsePayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// ToolMessageView is generated canonical view metadata for reader.
type ToolMessageView struct {
	Id                   string        `sqlx:"id,primaryKey=true"`
	ParentMessageId      *string       `sqlx:"parent_message_id"`
	CreatedAt            time.Time     `sqlx:"created_at,required=true"`
	Sequence             *int          `sqlx:"sequence"`
	Type                 string        `sqlx:"type,required=true"`
	Content              *string       `sqlx:"content"`
	ToolName             *string       `sqlx:"tool_name"`
	Iteration            *int          `sqlx:"iteration"`
	LinkedConversationId *string       `sqlx:"linked_conversation_id"`
	ToolCall             *ToolCallView `view:"toolCall,type=ToolCallView,table=tool_call" on:"Id:toolMessage.id=MessageId:toolCall.message_id" json:"toolCall" sql:"uri=datly_conversation_read_reader:sql/tool_call.sql"`
}

// ToolCallView is generated canonical view metadata for reader.
type ToolCallView struct {
	MessageSequence   *int                 `sqlx:"message_sequence"`
	MessageId         string               `sqlx:"message_id,refTable=message,refColumn=id,primaryKey=true"`
	TurnId            *string              `sqlx:"turn_id,refTable=turn,refColumn=id"`
	OpId              string               `sqlx:"op_id,required=true"`
	Attempt           int                  `sqlx:"attempt,required=true"`
	ToolName          string               `sqlx:"tool_name,required=true"`
	ToolKind          string               `sqlx:"tool_kind,required=true"`
	Status            string               `sqlx:"status,required=true"`
	RequestHash       *string              `sqlx:"request_hash"`
	ErrorCode         *string              `sqlx:"error_code"`
	ErrorMessage      *string              `sqlx:"error_message"`
	Retriable         *int                 `sqlx:"retriable"`
	StartedAt         *time.Time           `sqlx:"started_at"`
	CompletedAt       *time.Time           `sqlx:"completed_at"`
	LatencyMs         *int                 `sqlx:"latency_ms"`
	Cost              *float64             `sqlx:"cost"`
	TraceId           *string              `sqlx:"trace_id"`
	SpanId            *string              `sqlx:"span_id"`
	RequestPayloadId  *string              `sqlx:"request_payload_id,refTable=call_payload,refColumn=id"`
	ResponsePayloadId *string              `sqlx:"response_payload_id,refTable=call_payload,refColumn=id"`
	RunId             *string              `sqlx:"run_id"`
	Iteration         *int                 `sqlx:"iteration"`
	RequestPayload    *RequestPayloadView  `view:"requestPayload,type=RequestPayloadView,table=call_payload" on:"RequestPayloadId:toolCall.request_payload_id=Id:requestPayload.id" json:"requestPayload" sql:"uri=datly_conversation_read_reader:sql/request_payload.sql"`
	ResponsePayload   *ResponsePayloadView `view:"responsePayload,type=ResponsePayloadView,table=call_payload" on:"ResponsePayloadId:toolCall.response_payload_id=Id:responsePayload.id" json:"responsePayload" sql:"uri=datly_conversation_read_reader:sql/response_payload.sql"`
}

// RequestPayloadView is generated canonical view metadata for reader.
type RequestPayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// ResponsePayloadView is generated canonical view metadata for reader.
type ResponsePayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// UserElicitationDataView is generated canonical view metadata for reader.
type UserElicitationDataView struct {
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression"`
	MessageId   string  `sqlx:"id|message_id,primaryKey=true"`
}

// LinkedConversationView is generated canonical view metadata for reader.
type LinkedConversationView struct {
	Id        string     `sqlx:"id,primaryKey=true"`
	Status    *string    `sqlx:"status"`
	CreatedAt time.Time  `sqlx:"created_at,required=true"`
	UpdatedAt *time.Time `sqlx:"updated_at"`
}

// AttachmentView is generated canonical view metadata for reader.
type AttachmentView struct {
	InlineBody      *[]uint8 `sqlx:"inline_body"`
	Compression     string   `sqlx:"compression"`
	Uri             *string  `sqlx:"uri"`
	MimeType        string   `sqlx:"mime_type"`
	ParentMessageId *string  `sqlx:"parent_message_id"`
}

// ModelCallView is generated canonical view metadata for reader.
type ModelCallView struct {
	CompletedAt                        *time.Time                            `sqlx:"completed_at"`
	CompletionAcceptedPredictionTokens *int                                  `sqlx:"completion_accepted_prediction_tokens"`
	CompletionAudioTokens              *int                                  `sqlx:"completion_audio_tokens"`
	CompletionReasoningTokens          *int                                  `sqlx:"completion_reasoning_tokens"`
	CompletionRejectedPredictionTokens *int                                  `sqlx:"completion_rejected_prediction_tokens"`
	CompletionTokens                   *int                                  `sqlx:"completion_tokens"`
	Cost                               *float64                              `sqlx:"cost"`
	ErrorCode                          *string                               `sqlx:"error_code"`
	ErrorMessage                       *string                               `sqlx:"error_message"`
	FinishReason                       *string                               `sqlx:"finish_reason"`
	Iteration                          *int                                  `sqlx:"iteration"`
	LatencyMs                          *int                                  `sqlx:"latency_ms"`
	MessageId                          string                                `sqlx:"message_id,refTable=message,refColumn=id,primaryKey=true"`
	Model                              string                                `sqlx:"model,required=true"`
	ModelKind                          string                                `sqlx:"model_kind,required=true"`
	PromptAudioTokens                  *int                                  `sqlx:"prompt_audio_tokens"`
	PromptCachedTokens                 *int                                  `sqlx:"prompt_cached_tokens"`
	PromptTokens                       *int                                  `sqlx:"prompt_tokens"`
	Provider                           string                                `sqlx:"provider,required=true"`
	ProviderRequestPayloadId           *string                               `sqlx:"provider_request_payload_id,refTable=call_payload,refColumn=id"`
	ProviderResponsePayloadId          *string                               `sqlx:"provider_response_payload_id,refTable=call_payload,refColumn=id"`
	RequestPayloadId                   *string                               `sqlx:"request_payload_id,refTable=call_payload,refColumn=id"`
	ResponsePayloadId                  *string                               `sqlx:"response_payload_id,refTable=call_payload,refColumn=id"`
	RunId                              *string                               `sqlx:"run_id"`
	SpanId                             *string                               `sqlx:"span_id"`
	StartedAt                          *time.Time                            `sqlx:"started_at"`
	Status                             string                                `sqlx:"status,required=true"`
	StreamPayloadId                    *string                               `sqlx:"stream_payload_id,refTable=call_payload,refColumn=id"`
	TotalTokens                        *int                                  `sqlx:"total_tokens"`
	TraceId                            *string                               `sqlx:"trace_id"`
	TurnId                             *string                               `sqlx:"turn_id,refTable=turn,refColumn=id"`
	ModelCallRequestPayload            *ModelCallRequestPayloadView          `view:"modelCallRequestPayload,type=ModelCallRequestPayloadView,table=call_payload" on:"RequestPayloadId:modelCall.request_payload_id=Id:modelCallRequestPayload.id" json:"modelCallRequestPayload" sql:"uri=datly_conversation_read_reader:sql/model_call_request_payload.sql"`
	ModelCallProviderRequestPayload    *ModelCallProviderRequestPayloadView  `view:"modelCallProviderRequestPayload,type=ModelCallProviderRequestPayloadView,table=call_payload" on:"ProviderRequestPayloadId:modelCall.provider_request_payload_id=Id:modelCallProviderRequestPayload.id" json:"modelCallProviderRequestPayload" sql:"uri=datly_conversation_read_reader:sql/model_call_provider_request_payload.sql"`
	ModelCallResponsePayload           *ModelCallResponsePayloadView         `view:"modelCallResponsePayload,type=ModelCallResponsePayloadView,table=call_payload" on:"ResponsePayloadId:modelCall.response_payload_id=Id:modelCallResponsePayload.id" json:"modelCallResponsePayload" sql:"uri=datly_conversation_read_reader:sql/model_call_response_payload.sql"`
	ModelCallProviderResponsePayload   *ModelCallProviderResponsePayloadView `view:"modelCallProviderResponsePayload,type=ModelCallProviderResponsePayloadView,table=call_payload" on:"ProviderResponsePayloadId:modelCall.provider_response_payload_id=Id:modelCallProviderResponsePayload.id" json:"modelCallProviderResponsePayload" sql:"uri=datly_conversation_read_reader:sql/model_call_provider_response_payload.sql"`
	ToolCallLinks                      []*ToolCallLinksView                  `view:"toolCallLinks,type=ToolCallLinksView,table=tool_call" on:"TraceId:modelCall.trace_id=TraceId:toolCallLinks.trace_id" json:"toolCallLinks" sql:"uri=datly_conversation_read_reader:sql/tool_call_links.sql"`
	ModelCallStreamPayload             *ModelCallStreamPayloadView           `view:"modelCallStreamPayload,type=ModelCallStreamPayloadView,table=call_payload" on:"StreamPayloadId:modelCall.stream_payload_id=Id:modelCallStreamPayload.id" json:"modelCallStreamPayload" sql:"uri=datly_conversation_read_reader:sql/model_call_stream_payload.sql"`
}

// ModelCallRequestPayloadView is generated canonical view metadata for reader.
type ModelCallRequestPayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// ModelCallProviderRequestPayloadView is generated canonical view metadata for reader.
type ModelCallProviderRequestPayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// ModelCallResponsePayloadView is generated canonical view metadata for reader.
type ModelCallResponsePayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// ModelCallProviderResponsePayloadView is generated canonical view metadata for reader.
type ModelCallProviderResponsePayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// ToolCallLinksView is generated canonical view metadata for reader.
type ToolCallLinksView struct {
	MessageId string  `sqlx:"message_id,refTable=message,refColumn=id,primaryKey=true"`
	OpId      string  `sqlx:"op_id,required=true"`
	TraceId   *string `sqlx:"trace_id"`
}

// ModelCallStreamPayloadView is generated canonical view metadata for reader.
type ModelCallStreamPayloadView struct {
	Id          string  `sqlx:"id,primaryKey=true"`
	InlineBody  *string `sqlx:"inline_body"`
	Compression string  `sqlx:"compression,required=true"`
}

// UsageView is generated canonical view metadata for reader.
type UsageView struct {
	ConversationId                     string       `sqlx:"conversation_id"`
	Cost                               *float64     `sqlx:"cost"`
	PromptTokens                       *int         `sqlx:"prompt_tokens"`
	PromptCachedTokens                 *int         `sqlx:"prompt_cached_tokens"`
	PromptAudioTokens                  *int         `sqlx:"prompt_audio_tokens"`
	CompletionTokens                   *int         `sqlx:"completion_tokens"`
	CompletionReasoningTokens          *int         `sqlx:"completion_reasoning_tokens"`
	CompletionAudioTokens              *int         `sqlx:"completion_audio_tokens"`
	CompletionAcceptedPredictionTokens *int         `sqlx:"completion_accepted_prediction_tokens"`
	CompletionRejectedPredictionTokens *int         `sqlx:"completion_rejected_prediction_tokens"`
	TotalTokens                        *int         `sqlx:"total_tokens"`
	Model                              []*ModelView `view:"model,type=ModelView,table=model_call" on:"ConversationId:usage.conversation_id=ConversationId:model.conversation_id" json:"model" sql:"uri=datly_conversation_read_reader:sql/model.sql"`
}

// ModelView is generated canonical view metadata for reader.
type ModelView struct {
	ConversationId                     string   `sqlx:"conversation_id"`
	Provider                           string   `sqlx:"provider,required=true"`
	Model                              string   `sqlx:"model,required=true"`
	ExecutionRole                      string   `sqlx:"execution_role"`
	PromptTokens                       *int     `sqlx:"prompt_tokens"`
	PromptCachedTokens                 *int     `sqlx:"prompt_cached_tokens"`
	PromptAudioTokens                  *int     `sqlx:"prompt_audio_tokens"`
	CompletionTokens                   *int     `sqlx:"completion_tokens"`
	CompletionReasoningTokens          *int     `sqlx:"completion_reasoning_tokens"`
	CompletionAudioTokens              *int     `sqlx:"completion_audio_tokens"`
	CompletionAcceptedPredictionTokens *int     `sqlx:"completion_accepted_prediction_tokens"`
	CompletionRejectedPredictionTokens *int     `sqlx:"completion_rejected_prediction_tokens"`
	TotalTokens                        *int     `sqlx:"total_tokens"`
	Cost                               *float64 `sqlx:"cost"`
}
