// Code generated by Datly for writer; DO NOT EDIT.

package claim

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const WriterDatlyResourceNamespace = "datly_toolapprovalqueue_claim_writer"

//go:embed "sql/current_writer.sql" "sql/writer.sql" "sql/writer_keys.sql"
var WriterDatlyResources embed.FS
