// Code generated by Datly for writer; DO NOT EDIT.

package claim

import (
	time "time"
)

// QueueClaim is generated canonical view metadata for writer.
type QueueClaim struct {
	Id               string         `sqlx:"id,primaryKey=true" json:"id,omitempty"`
	UserId           string         `sqlx:"user_id,required=true" json:"userId,omitempty"`
	Status           string         `sqlx:"status,required=true" json:"status,omitempty"`
	Decision         *string        `sqlx:"decision" json:"decision,omitempty"`
	ApprovedByUserId *string        `sqlx:"approved_by_user_id" json:"approvedByUserId,omitempty"`
	ApprovedAt       *time.Time     `sqlx:"approved_at" json:"approvedAt,omitempty"`
	UpdatedAt        *time.Time     `sqlx:"updated_at" json:"updatedAt,omitempty"`
	Metadata         *string        `sqlx:"metadata" json:"metadata,omitempty"`
	ExpiresAt        *time.Time     `sqlx:"expires_at" json:"expiresAt,omitempty"`
	TimedOutAt       *time.Time     `sqlx:"timed_out_at" json:"timedOutAt,omitempty"`
	Has              *QueueClaimHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"QueueClaimHas"`
}

type QueueClaimHas struct {
	Id               bool
	UserId           bool
	Status           bool
	Decision         bool
	ApprovedByUserId bool
	ApprovedAt       bool
	UpdatedAt        bool
	Metadata         bool
	ExpiresAt        bool
	TimedOutAt       bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	Id               string     `sqlx:"id,primaryKey=true" json:"id,omitempty"`
	UserId           string     `sqlx:"user_id,required=true" json:"userId,omitempty"`
	Status           string     `sqlx:"status,required=true" json:"status,omitempty"`
	Decision         *string    `sqlx:"decision" json:"decision,omitempty"`
	ApprovedByUserId *string    `sqlx:"approved_by_user_id" json:"approvedByUserId,omitempty"`
	ApprovedAt       *time.Time `sqlx:"approved_at" json:"approvedAt,omitempty"`
	UpdatedAt        *time.Time `sqlx:"updated_at" json:"updatedAt,omitempty"`
	Metadata         *string    `sqlx:"metadata" json:"metadata,omitempty"`
	ExpiresAt        *time.Time `sqlx:"expires_at" json:"expiresAt,omitempty"`
	TimedOutAt       *time.Time `sqlx:"timed_out_at" json:"timedOutAt,omitempty"`
}

type WriterKeysRow struct {
	Id string `sqlx:"id"`
}
