// Code generated by Datly for reader; DO NOT EDIT.

package read

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ReaderDatlyResourceNamespace = "agui_thread_read_reader"

//go:embed "sql/reader.sql"
var ReaderDatlyResources embed.FS
