// Code generated by Datly for reader; DO NOT EDIT.

package read

// Message is generated canonical view metadata for reader.
type Message struct {
	Id                   string  `sqlx:"id,primaryKey=true" json:"id"`
	ConversationId       string  `sqlx:"conversation_id,refTable=conversation,refColumn=id,required=true" json:"conversationId"`
	LinkedConversationId *string `sqlx:"linked_conversation_id" json:"linkedConversationId"`
	ParentMessageId      *string `sqlx:"parent_message_id" json:"parentMessageId"`
	SupersededBy         *string `sqlx:"superseded_by" json:"supersededBy"`
	AttachmentPayloadId  *string `sqlx:"attachment_payload_id,refTable=call_payload,refColumn=id" json:"attachmentPayloadId"`
	ElicitationPayloadId *string `sqlx:"elicitation_payload_id,refTable=call_payload,refColumn=id" json:"elicitationPayloadId"`
}
