// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

// Execution is generated canonical view metadata for reader.
type Execution struct {
	Id              *string    `sqlx:"id,primaryKey=true" json:"id"`
	ConversationId  *string    `sqlx:"conversation_id,refTable=conversation,refColumn=id" json:"conversationId"`
	TurnId          *string    `sqlx:"turn_id,refTable=turn,refColumn=id" json:"turnId"`
	EffectiveUserId *string    `sqlx:"effective_user_id" json:"effectiveUserId"`
	Status          *string    `sqlx:"status,required=true" json:"status"`
	LeaseOwner      *string    `sqlx:"lease_owner" json:"leaseOwner"`
	LeaseUntil      *time.Time `sqlx:"lease_until" json:"leaseUntil"`
}
