// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

// Input is the generated input scaffold for reader.
type Input struct {
	Trusted       bool      `parameter:"Trusted,kind=maintenanceaccess,in=internal,dataType=bool,required=true"`
	Mode          string    `parameter:"Mode,kind=query,in=mode,dataType=string,value=rows,required=false"`
	LeaseKey      string    `parameter:"LeaseKey,kind=query,in=leaseKey,dataType=string,required=false" predicate:"equal,l,lease_key"`
	ExpiresBefore time.Time `parameter:"ExpiresBefore,kind=query,in=expiresBefore,dataType=time.Time,required=false" predicate:"less_or_equal,l,lease_until"`
	Has           *InputHas `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Trusted       bool
	Mode          bool
	LeaseKey      bool
	ExpiresBefore bool
}
