// Code generated by Datly for reader; DO NOT EDIT.

package read

// Output is the generated output scaffold for reader.
type Output struct {
	Data []*LeaseSnapshot `parameter:"Data,kind=output,in=view,dataType=[]*LeaseSnapshot" view:"reader,type=LeaseSnapshot,table=maintenance_lease" sql:"uri=datly_maintenancelease_read_reader:sql/reader.sql"`
}
