// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

// LeaseSnapshot is generated canonical view metadata for reader.
type LeaseSnapshot struct {
	DbNow      string     `sqlx:"db_now"`
	LeaseKey   *string    `sqlx:"lease_key"`
	OwnerId    *string    `sqlx:"owner_id"`
	LeaseToken *string    `sqlx:"lease_token"`
	LeaseUntil *time.Time `sqlx:"lease_until"`
	CreatedAt  *time.Time `sqlx:"created_at"`
	UpdatedAt  *time.Time `sqlx:"updated_at"`
}
