CREATE TABLE `report_shared_artifact` (
  `artifact_id` varchar(255) NOT NULL,
  `artifact_ref` text NOT NULL,
  `owner_id` varchar(255) NOT NULL,
  `owner_ref` text,
  `kind` varchar(255) NOT NULL,
  `lifecycle` varchar(255) NOT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `report_id` varchar(255) DEFAULT NULL,
  `title` text,
  `source_artifact_id` varchar(255) DEFAULT NULL,
  `base_artifact_ref` text,
  `policy_ref` varchar(255) DEFAULT NULL,
  `document_version` bigint NOT NULL DEFAULT '0',
  `report_document_json` mediumblob,
  `report_spec_json` mediumblob,
  `compile_state_json` mediumblob,
  `report_fill_json` mediumblob,
  `report_print_json` mediumblob,
  `saved_view_overlay_json` mediumblob,
  `metadata_json` mediumblob,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`artifact_id`),
  KEY `idx_report_shared_artifact_owner_artifact_ref` (`owner_id`(191),`artifact_ref`(191)),
  KEY `idx_report_shared_artifact_owner_report_id` (`owner_id`,`report_id`),
  KEY `idx_report_shared_artifact_owner_kind_lifecycle_updated` (`owner_id`,`kind`,`lifecycle`,`updated_at`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `report_run` (
  `report_run_id` varchar(255) NOT NULL,
  `owner_id` varchar(255) NOT NULL,
  `conversation_id` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `materializer` varchar(64) NOT NULL,
  `origin` varchar(64) DEFAULT NULL,
  `builder_ref` varchar(255) DEFAULT NULL,
  `preset_id` varchar(255) DEFAULT NULL,
  `source_kind` varchar(64) DEFAULT NULL,
  `source_id` varchar(255) DEFAULT NULL,
  `requested_params_json` mediumblob,
  `effective_params_json` mediumblob,
  `status` varchar(32) NOT NULL,
  `failure_code` varchar(255) DEFAULT NULL,
  `failure_text` text,
  `started_at` datetime NOT NULL,
  `completed_at` datetime DEFAULT NULL,
  `revision` bigint NOT NULL,
  `ui_run_request_id` varchar(255) NOT NULL,
  `report_spec_json` mediumblob,
  `report_fill_json` mediumblob,
  `report_print_json` mediumblob,
  `activation_source` varchar(64) DEFAULT NULL,
  `adoption_source` varchar(64) DEFAULT NULL,
  `actor_id` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`report_run_id`),
  UNIQUE KEY `ux_report_run_owner_request` (`owner_id`,`ui_run_request_id`),
  UNIQUE KEY `ux_report_run_owner_id` (`owner_id`,`report_run_id`),
  KEY `idx_report_run_owner_conversation_updated` (`owner_id`,`conversation_id`,`updated_at`),
  KEY `idx_report_run_owner_status_updated` (`owner_id`,`status`,`updated_at`),
  KEY `idx_report_run_updated` (`updated_at`,`report_run_id`),
  CONSTRAINT `fk_report_run_conversation` FOREIGN KEY (`conversation_id`) REFERENCES `conversation` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_report_run_status` CHECK ((`status` in (_utf8mb4'running',_utf8mb4'completed',_utf8mb4'failed')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `report_export_job` (
  `job_id` varchar(255) NOT NULL,
  `artifact_ref` text NOT NULL,
  `owner_id` varchar(255) NOT NULL,
  `conversation_id` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `workspace_id` varchar(255) DEFAULT NULL,
  `auth_context_ref` text,
  `format` varchar(64) NOT NULL,
  `scope` varchar(64) NOT NULL,
  `status` varchar(64) NOT NULL,
  `report_spec_json` mediumblob,
  `report_fill_json` mediumblob,
  `report_print_json` mediumblob,
  `metadata_json` mediumblob,
  `artifact_id` varchar(255) DEFAULT NULL,
  `error_text` text,
  `diagnostics_json` mediumblob,
  `submitted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `retention_ttl_sec` bigint NOT NULL DEFAULT '0',
  `report_run_id` varchar(255) DEFAULT NULL,
  `report_run_revision` bigint DEFAULT NULL,
  `export_request_id` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`job_id`),
  UNIQUE KEY `ux_report_export_job_owner_conversation_request` (`owner_id`,`conversation_id`,`export_request_id`),
  KEY `idx_report_export_job_owner_submitted_at` (`owner_id`,`submitted_at`),
  KEY `idx_report_export_job_owner_artifact_ref` (`owner_id`,`artifact_ref`(191)),
  KEY `idx_report_export_job_owner_status` (`owner_id`,`status`),
  KEY `idx_report_export_job_run` (`report_run_id`),
  CONSTRAINT `fk_report_export_job_run` FOREIGN KEY (`report_run_id`) REFERENCES `report_run` (`report_run_id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_report_export_job_status` CHECK ((`status` in (_utf8mb4'queued',_utf8mb4'running',_utf8mb4'succeeded',_utf8mb4'failed'))),
  CONSTRAINT `chk_report_export_job_run_reference` CHECK ((((`report_run_id` is null) and (`report_run_revision` is null) and (`export_request_id` is null)) or ((`report_run_id` is not null) and (`report_run_revision` is not null) and (`report_run_revision` > 0) and (`export_request_id` is not null) and (`conversation_id` is not null)))),
  CONSTRAINT `chk_report_export_job_run_pdf` CHECK (((`report_run_id` is null) or ((`format` = _utf8mb4'pdf') and (`scope` = _utf8mb4'draft'))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `report_export_artifact` (
  `artifact_id` varchar(255) NOT NULL,
  `job_id` varchar(255) NOT NULL,
  `artifact_ref` text NOT NULL,
  `owner_id` varchar(255) NOT NULL,
  `format` varchar(64) NOT NULL,
  `content_type` varchar(255) NOT NULL,
  `inline_data` longblob,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `retention_ttl_sec` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`artifact_id`),
  UNIQUE KEY `ux_report_export_artifact_job` (`job_id`),
  KEY `idx_report_export_artifact_owner_created_at` (`owner_id`,`created_at`),
  KEY `idx_report_export_artifact_owner_artifact_ref` (`owner_id`,`artifact_ref`(191)),
  CONSTRAINT `fk_report_export_artifact_job` FOREIGN KEY (`job_id`) REFERENCES `report_export_job` (`job_id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `report_audit_event` (
  `event_id` varchar(255) NOT NULL,
  `event_type` varchar(255) NOT NULL,
  `artifact_ref` text NOT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  `job_id` varchar(255) DEFAULT NULL,
  `artifact_id` varchar(255) DEFAULT NULL,
  `actor_id` varchar(255) NOT NULL,
  `actor_ref` text,
  `occurred_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `metadata_json` mediumblob,
  PRIMARY KEY (`event_id`),
  KEY `idx_report_audit_event_actor_occurred_at` (`actor_id`,`occurred_at`),
  KEY `idx_report_audit_event_artifact_ref` (`artifact_ref`(191)),
  KEY `idx_report_audit_event_occurred` (`occurred_at`,`event_id`),
  KEY `idx_report_audit_event_job` (`job_id`),
  KEY `idx_report_audit_event_artifact` (`artifact_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `conversation_report_context` (
  `owner_id` varchar(255) NOT NULL,
  `conversation_id` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `active_report_run_id` varchar(255) NOT NULL,
  `revision` bigint NOT NULL,
  `activation_source` varchar(64) NOT NULL DEFAULT '',
  `actor_id` varchar(255) NOT NULL DEFAULT '',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`owner_id`,`conversation_id`),
  KEY `idx_conversation_report_context_active_run` (`owner_id`,`active_report_run_id`),
  CONSTRAINT `fk_conversation_report_context_conversation` FOREIGN KEY (`conversation_id`) REFERENCES `conversation` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_conversation_report_context_run` FOREIGN KEY (`owner_id`, `active_report_run_id`) REFERENCES `report_run` (`owner_id`, `report_run_id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
