// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetPrincipal(value string) {
	if input == nil {
		return
	}
	input.Principal = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Principal = true
}

func (input *Input) SetKey(value string) {
	if input == nil {
		return
	}
	input.Key = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Key = true
}
