// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
	time "time"
)

type WriterHandlerCurrentWriterSlice []*CurrentWriterView

func WriterHandlerCurrentWriterIndexByRevisionKey(value *CurrentWriterView) (int64, bool) {
	var zero int64
	if value == nil {
		return zero, false
	}
	return value.Revision, true
}

type WriterHandlerCurrentWriterIndexedByRevision map[int64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByRevision() (WriterHandlerCurrentWriterIndexedByRevision, error) {
	result := make(WriterHandlerCurrentWriterIndexedByRevision)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByRevision) Has(key int64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByRevision map[int64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByRevision() WriterHandlerCurrentWriterGroupedByRevision {
	result := make(WriterHandlerCurrentWriterGroupedByRevision)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByRevision) Has(key int64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByOwnerIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.OwnerId, true
}

type WriterHandlerCurrentWriterIndexedByOwnerId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByOwnerId() (WriterHandlerCurrentWriterIndexedByOwnerId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByOwnerId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByOwnerIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByOwnerId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByOwnerId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByOwnerId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByOwnerId() WriterHandlerCurrentWriterGroupedByOwnerId {
	result := make(WriterHandlerCurrentWriterGroupedByOwnerId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByOwnerIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByOwnerId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByConversationIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.ConversationId, true
}

type WriterHandlerCurrentWriterIndexedByConversationId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByConversationId() (WriterHandlerCurrentWriterIndexedByConversationId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByConversationId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConversationIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByConversationId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByConversationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByConversationId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByConversationId() WriterHandlerCurrentWriterGroupedByConversationId {
	result := make(WriterHandlerCurrentWriterGroupedByConversationId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConversationIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByConversationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByActiveReportRunIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.ActiveReportRunId, true
}

type WriterHandlerCurrentWriterIndexedByActiveReportRunId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByActiveReportRunId() (WriterHandlerCurrentWriterIndexedByActiveReportRunId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByActiveReportRunId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByActiveReportRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByActiveReportRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByActiveReportRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByActiveReportRunId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByActiveReportRunId() WriterHandlerCurrentWriterGroupedByActiveReportRunId {
	result := make(WriterHandlerCurrentWriterGroupedByActiveReportRunId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByActiveReportRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByActiveReportRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByActivationSourceKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.ActivationSource, true
}

type WriterHandlerCurrentWriterIndexedByActivationSource map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByActivationSource() (WriterHandlerCurrentWriterIndexedByActivationSource, error) {
	result := make(WriterHandlerCurrentWriterIndexedByActivationSource)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByActivationSourceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByActivationSource")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByActivationSource) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByActivationSource map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByActivationSource() WriterHandlerCurrentWriterGroupedByActivationSource {
	result := make(WriterHandlerCurrentWriterGroupedByActivationSource)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByActivationSourceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByActivationSource) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByActorIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.ActorId, true
}

type WriterHandlerCurrentWriterIndexedByActorId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByActorId() (WriterHandlerCurrentWriterIndexedByActorId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByActorId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByActorIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByActorId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByActorId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByActorId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByActorId() WriterHandlerCurrentWriterGroupedByActorId {
	result := make(WriterHandlerCurrentWriterGroupedByActorId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByActorIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByActorId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByUpdatedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	return value.UpdatedAt, true
}

type WriterHandlerCurrentWriterIndexedByUpdatedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByUpdatedAt() (WriterHandlerCurrentWriterIndexedByUpdatedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByUpdatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByUpdatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByUpdatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByUpdatedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByUpdatedAt() WriterHandlerCurrentWriterGroupedByUpdatedAt {
	result := make(WriterHandlerCurrentWriterGroupedByUpdatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByUpdatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterKey struct {
	OwnerId        string
	ConversationId string
}

func WriterHandlerCurrentWriterIndexByKeyKey(value *CurrentWriterView) (WriterHandlerCurrentWriterKey, bool) {
	var zero WriterHandlerCurrentWriterKey
	if value == nil {
		return zero, false
	}
	return WriterHandlerCurrentWriterKey{OwnerId: value.OwnerId, ConversationId: value.ConversationId}, true
}

type WriterHandlerCurrentWriterIndexedByKey map[WriterHandlerCurrentWriterKey]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByKey() (WriterHandlerCurrentWriterIndexedByKey, error) {
	result := make(WriterHandlerCurrentWriterIndexedByKey)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByKey) Has(key WriterHandlerCurrentWriterKey) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByKey map[WriterHandlerCurrentWriterKey][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByKey() WriterHandlerCurrentWriterGroupedByKey {
	result := make(WriterHandlerCurrentWriterGroupedByKey)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByKey) Has(key WriterHandlerCurrentWriterKey) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerReadIndexes struct {
	CurrentWriter      WriterHandlerCurrentWriterSlice
	CurrentWriterByKey WriterHandlerCurrentWriterIndexedByKey
}

func BuildWriterHandlerReadIndexes(ctx context.Context, input *Input) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &WriterHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentWriter")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentWriter")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*Input)(nil)).Elem()).Accessor("CurrentWriter")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentWriterView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentWriterView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentWriterView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("OwnerId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.OwnerId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ConversationId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ConversationId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ActiveReportRunId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ActiveReportRunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ActivationSource") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ActivationSource")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ActorId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ActorId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("UpdatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.UpdatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentWriter = WriterHandlerCurrentWriterSlice(cloned.([]*CurrentWriterView))
		result.CurrentWriterByKey, err = result.CurrentWriter.IndexByKey()
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func (input *Input) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._writerHandlerReadIndexes = nil
	indexes, err := BuildWriterHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._writerHandlerReadIndexes = indexes
	return nil
}
func (input *Input) ReadIndexes(ctx context.Context) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._writerHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._writerHandlerReadIndexes, nil
}
