// Code generated by Datly for writer; DO NOT EDIT.

package delete

func (input *Input) SetExecutionRunOnly(value bool) {
	if input == nil {
		return
	}
	input.ExecutionRunOnly = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExecutionRunOnly = true
}

func (input *Input) SetRuns(value []*RunDelete) {
	if input == nil {
		return
	}
	input.Runs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Runs = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
