// Code generated by Datly for writer; DO NOT EDIT.

package delete

// Input is the generated input scaffold for writer.
type Input struct {
	Runs                      []*RunDelete              `parameter:"Runs,kind=body,in=data,dataType=[]*RunDelete" view:"writer,onDeleteNotFound=ignore,type=RunDelete,table=run" sql:"uri=datly_run_delete_writer:sql/writer.sql"`
	WriterKeys                []WriterKeysRow           `parameter:"WriterKeys,kind=param,in=Runs,cardinality=Many" codec:"structql,'uri=datly_run_delete_writer:sql/writer_keys.sql'"`
	CurrentWriter             []*CurrentWriterView      `parameter:"CurrentWriter,kind=view,in=CurrentWriter,cardinality=Many" view:"CurrentWriter,table=run" sql:"uri=datly_run_delete_writer:sql/current_writer.sql"`
	_writerHandlerReadIndexes *WriterHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                       *InputHas                 `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Runs          bool
	WriterKeys    bool
	CurrentWriter bool
}
