// Code generated by Datly for writer; DO NOT EDIT.

package delete

// Output is the generated output scaffold for writer.
type Output struct {
	Data []*RunDelete `parameter:"Data,kind=output,in=body,dataType=[]*RunDelete"`
}
