// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
	time "time"
)

type WriterHandlerCurrentWriterSlice []*CurrentWriterView

func WriterHandlerCurrentWriterIndexByEncTokenKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.EncToken, true
}

type WriterHandlerCurrentWriterIndexedByEncToken map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByEncToken() (WriterHandlerCurrentWriterIndexedByEncToken, error) {
	result := make(WriterHandlerCurrentWriterIndexedByEncToken)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByEncTokenKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByEncToken")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByEncToken) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByEncToken map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByEncToken() WriterHandlerCurrentWriterGroupedByEncToken {
	result := make(WriterHandlerCurrentWriterGroupedByEncToken)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByEncTokenKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByEncToken) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByUserIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.UserId, true
}

type WriterHandlerCurrentWriterIndexedByUserId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByUserId() (WriterHandlerCurrentWriterIndexedByUserId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByUserId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUserIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByUserId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByUserId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByUserId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByUserId() WriterHandlerCurrentWriterGroupedByUserId {
	result := make(WriterHandlerCurrentWriterGroupedByUserId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUserIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByUserId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByProviderKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.Provider, true
}

type WriterHandlerCurrentWriterIndexedByProvider map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByProvider() (WriterHandlerCurrentWriterIndexedByProvider, error) {
	result := make(WriterHandlerCurrentWriterIndexedByProvider)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByProviderKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByProvider")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByProvider) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByProvider map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByProvider() WriterHandlerCurrentWriterGroupedByProvider {
	result := make(WriterHandlerCurrentWriterGroupedByProvider)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByProviderKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByProvider) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCreatedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	return value.CreatedAt, true
}

type WriterHandlerCurrentWriterIndexedByCreatedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCreatedAt() (WriterHandlerCurrentWriterIndexedByCreatedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCreatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCreatedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCreatedAt() WriterHandlerCurrentWriterGroupedByCreatedAt {
	result := make(WriterHandlerCurrentWriterGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCreatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByUpdatedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.UpdatedAt == nil {
		return zero, false
	}
	return *value.UpdatedAt, true
}

type WriterHandlerCurrentWriterIndexedByUpdatedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByUpdatedAt() (WriterHandlerCurrentWriterIndexedByUpdatedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByUpdatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByUpdatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByUpdatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByUpdatedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByUpdatedAt() WriterHandlerCurrentWriterGroupedByUpdatedAt {
	result := make(WriterHandlerCurrentWriterGroupedByUpdatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByUpdatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByVersionKey(value *CurrentWriterView) (int64, bool) {
	var zero int64
	if value == nil {
		return zero, false
	}
	return value.Version, true
}

type WriterHandlerCurrentWriterIndexedByVersion map[int64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByVersion() (WriterHandlerCurrentWriterIndexedByVersion, error) {
	result := make(WriterHandlerCurrentWriterIndexedByVersion)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByVersionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByVersion")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByVersion) Has(key int64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByVersion map[int64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByVersion() WriterHandlerCurrentWriterGroupedByVersion {
	result := make(WriterHandlerCurrentWriterGroupedByVersion)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByVersionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByVersion) Has(key int64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByRefreshStatusKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.RefreshStatus, true
}

type WriterHandlerCurrentWriterIndexedByRefreshStatus map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByRefreshStatus() (WriterHandlerCurrentWriterIndexedByRefreshStatus, error) {
	result := make(WriterHandlerCurrentWriterIndexedByRefreshStatus)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRefreshStatusKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByRefreshStatus")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByRefreshStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByRefreshStatus map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByRefreshStatus() WriterHandlerCurrentWriterGroupedByRefreshStatus {
	result := make(WriterHandlerCurrentWriterGroupedByRefreshStatus)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRefreshStatusKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByRefreshStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByLeaseOwnerKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.LeaseOwner == nil {
		return zero, false
	}
	return *value.LeaseOwner, true
}

type WriterHandlerCurrentWriterIndexedByLeaseOwner map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByLeaseOwner() (WriterHandlerCurrentWriterIndexedByLeaseOwner, error) {
	result := make(WriterHandlerCurrentWriterIndexedByLeaseOwner)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseOwnerKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByLeaseOwner")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByLeaseOwner) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByLeaseOwner map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByLeaseOwner() WriterHandlerCurrentWriterGroupedByLeaseOwner {
	result := make(WriterHandlerCurrentWriterGroupedByLeaseOwner)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseOwnerKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByLeaseOwner) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByLeaseUntilKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.LeaseUntil == nil {
		return zero, false
	}
	return *value.LeaseUntil, true
}

type WriterHandlerCurrentWriterIndexedByLeaseUntil map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByLeaseUntil() (WriterHandlerCurrentWriterIndexedByLeaseUntil, error) {
	result := make(WriterHandlerCurrentWriterIndexedByLeaseUntil)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseUntilKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByLeaseUntil")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByLeaseUntil) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByLeaseUntil map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByLeaseUntil() WriterHandlerCurrentWriterGroupedByLeaseUntil {
	result := make(WriterHandlerCurrentWriterGroupedByLeaseUntil)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseUntilKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByLeaseUntil) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterKey struct {
	UserId   string
	Provider string
}

func WriterHandlerCurrentWriterIndexByKeyKey(value *CurrentWriterView) (WriterHandlerCurrentWriterKey, bool) {
	var zero WriterHandlerCurrentWriterKey
	if value == nil {
		return zero, false
	}
	return WriterHandlerCurrentWriterKey{UserId: value.UserId, Provider: value.Provider}, true
}

type WriterHandlerCurrentWriterIndexedByKey map[WriterHandlerCurrentWriterKey]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByKey() (WriterHandlerCurrentWriterIndexedByKey, error) {
	result := make(WriterHandlerCurrentWriterIndexedByKey)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByKey) Has(key WriterHandlerCurrentWriterKey) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByKey map[WriterHandlerCurrentWriterKey][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByKey() WriterHandlerCurrentWriterGroupedByKey {
	result := make(WriterHandlerCurrentWriterGroupedByKey)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByKey) Has(key WriterHandlerCurrentWriterKey) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerReadIndexes struct {
	CurrentWriter      WriterHandlerCurrentWriterSlice
	CurrentWriterByKey WriterHandlerCurrentWriterIndexedByKey
}

func BuildWriterHandlerReadIndexes(ctx context.Context, input *Input) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &WriterHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentWriter")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentWriter")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*Input)(nil)).Elem()).Accessor("CurrentWriter")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentWriterView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentWriterView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentWriterView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("EncToken") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.EncToken")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("UserId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.UserId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Provider") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Provider")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("UpdatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.UpdatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Version") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Version")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RefreshStatus") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.RefreshStatus")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("LeaseOwner") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.LeaseOwner")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("LeaseUntil") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.LeaseUntil")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentWriter = WriterHandlerCurrentWriterSlice(cloned.([]*CurrentWriterView))
		result.CurrentWriterByKey, err = result.CurrentWriter.IndexByKey()
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func (input *Input) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._writerHandlerReadIndexes = nil
	indexes, err := BuildWriterHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._writerHandlerReadIndexes = indexes
	return nil
}
func (input *Input) ReadIndexes(ctx context.Context) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._writerHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._writerHandlerReadIndexes, nil
}
