// Code generated by Datly for writer; DO NOT EDIT.

package write

func (input *Input) SetToken(value *Token) {
	if input == nil {
		return
	}
	input.Token = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Token = true
}

func (input *Input) SetMode(value string) {
	if input == nil {
		return
	}
	input.Mode = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Mode = true
}

func (input *Input) SetExpectedVersion(value int64) {
	if input == nil {
		return
	}
	input.ExpectedVersion = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExpectedVersion = true
}

func (input *Input) SetExpectedLeaseOwner(value string) {
	if input == nil {
		return
	}
	input.ExpectedLeaseOwner = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExpectedLeaseOwner = true
}

func (input *Input) SetExpectedEncToken(value string) {
	if input == nil {
		return
	}
	input.ExpectedEncToken = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExpectedEncToken = true
}

func (input *Input) SetLeaseMode(value string) {
	if input == nil {
		return
	}
	input.LeaseMode = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.LeaseMode = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
