// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

func (input *Input) SetAfterKey(value string) {
	if input == nil {
		return
	}
	input.AfterKey = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.AfterKey = true
}

func (input *Input) SetBefore(value time.Time) {
	if input == nil {
		return
	}
	input.Before = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Before = true
}
