// Code generated by Datly for reader; DO NOT EDIT.

package read

// Candidate is generated canonical view metadata for reader.
type Candidate struct {
	RunId           string  `sqlx:"protocol_run_id" json:"runId"`
	ThreadId        string  `sqlx:"protocol_thread_id" json:"threadId"`
	TurnId          string  `sqlx:"protocol_turn_id" json:"turnId"`
	RunKey          *string `sqlx:"protocol_key" json:"runKey"`
	Principal       *string `sqlx:"effective_user_id" json:"principal"`
	ConversationId  *string `sqlx:"conversation_id,refTable=conversation,refColumn=id" json:"conversationId"`
	SecurityContext *string `sqlx:"security_context" json:"securityContext"`
}
