// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// Investigation is generated canonical view metadata for writer.
type Investigation struct {
	ShouldDelete   bool              `json:"shouldDelete,omitempty" sqlx:"-" writer:"delete"`
	Id             string            `sqlx:"id,primaryKey=true,required=true" json:"id,omitempty"`
	Title          *string           `sqlx:"title" json:"title,omitempty"`
	CreatedBy      *string           `sqlx:"created_by" json:"createdBy,omitempty"`
	ConversationId *string           `sqlx:"conversation_id,refTable=conversation,refColumn=id" json:"conversationId,omitempty"`
	Summary        *string           `sqlx:"summary" json:"summary,omitempty"`
	AdOrderId      *int              `sqlx:"ad_order_id" json:"adOrderId,omitempty"`
	Verdict        *string           `sqlx:"verdict" json:"verdict,omitempty"`
	Created        *time.Time        `sqlx:"created,required=true" json:"created,omitempty"`
	Has            *InvestigationHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"InvestigationHas"`
}

type InvestigationHas struct {
	ShouldDelete   bool
	Id             bool
	Title          bool
	CreatedBy      bool
	ConversationId bool
	Summary        bool
	AdOrderId      bool
	Verdict        bool
	Created        bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	Id             string     `sqlx:"id,primaryKey=true,required=true" json:"id,omitempty"`
	Title          *string    `sqlx:"title" json:"title,omitempty"`
	CreatedBy      *string    `sqlx:"created_by" json:"createdBy,omitempty"`
	ConversationId *string    `sqlx:"conversation_id,refTable=conversation,refColumn=id" json:"conversationId,omitempty"`
	Summary        *string    `sqlx:"summary" json:"summary,omitempty"`
	AdOrderId      *int       `sqlx:"ad_order_id" json:"adOrderId,omitempty"`
	Verdict        *string    `sqlx:"verdict" json:"verdict,omitempty"`
	Created        *time.Time `sqlx:"created,required=true" json:"created,omitempty"`
}

type WriterKeysRow struct {
	Id string `sqlx:"id"`
}
