// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

// Run is generated canonical view metadata for reader.
type Run struct {
	MaintenanceObservedAt string     `internal:"true" json:"-" sqlx:"maintenance_observed_at"`
	ReportRunId           string     `sqlx:"report_run_id,primaryKey=true" json:"reportRunId"`
	OwnerId               string     `sqlx:"owner_id,required=true" json:"ownerId"`
	ConversationId        string     `sqlx:"conversation_id" json:"conversationId"`
	Materializer          string     `sqlx:"materializer,required=true" json:"materializer"`
	Origin                string     `sqlx:"origin" json:"origin"`
	BuilderRef            string     `sqlx:"builder_ref" json:"builderRef"`
	PresetId              string     `sqlx:"preset_id" json:"presetId"`
	SourceKind            string     `sqlx:"source_kind" json:"sourceKind"`
	SourceId              string     `sqlx:"source_id" json:"sourceId"`
	RequestedParamsJson   []byte     `sqlx:"requested_params_json" json:"requestedParamsJson"`
	EffectiveParamsJson   []byte     `sqlx:"effective_params_json" json:"effectiveParamsJson"`
	Status                string     `sqlx:"status,required=true" json:"status"`
	FailureCode           string     `sqlx:"failure_code" json:"failureCode"`
	FailureText           string     `sqlx:"failure_text" json:"failureText"`
	StartedAt             time.Time  `sqlx:"started_at,required=true" json:"startedAt"`
	Revision              int64      `sqlx:"revision,required=true" json:"revision"`
	UiRunRequestId        string     `sqlx:"ui_run_request_id,required=true" json:"uiRunRequestId"`
	ReportSpecJson        []byte     `sqlx:"report_spec_json" json:"reportSpecJson"`
	ReportFillJson        []byte     `sqlx:"report_fill_json" json:"reportFillJson"`
	ReportPrintJson       []byte     `sqlx:"report_print_json" json:"reportPrintJson"`
	ActivationSource      string     `sqlx:"activation_source" json:"activationSource"`
	AdoptionSource        string     `sqlx:"adoption_source" json:"adoptionSource"`
	ActorId               string     `sqlx:"actor_id" json:"actorId"`
	CreatedAt             time.Time  `sqlx:"created_at,required=true" json:"createdAt"`
	UpdatedAt             time.Time  `sqlx:"updated_at,required=true" json:"updatedAt"`
	CompletedAt           *time.Time `sqlx:"completed_at" json:"completedAt"`
}
