// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// Lease is generated canonical view metadata for writer.
type Lease struct {
	ShouldDelete bool      `json:"shouldDelete,omitempty" sqlx:"-" writer:"delete"`
	LeaseKey     string    `sqlx:"lease_key,primaryKey=true,required=true"`
	OwnerId      string    `sqlx:"owner_id,required=true"`
	LeaseToken   string    `sqlx:"lease_token,required=true"`
	LeaseUntil   time.Time `sqlx:"lease_until,required=true"`
	CreatedAt    time.Time `sqlx:"created_at,required=true"`
	UpdatedAt    time.Time `sqlx:"updated_at,required=true"`
	Has          *LeaseHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"LeaseHas"`
}

type LeaseHas struct {
	ShouldDelete bool
	LeaseKey     bool
	OwnerId      bool
	LeaseToken   bool
	LeaseUntil   bool
	CreatedAt    bool
	UpdatedAt    bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	LeaseKey   string    `sqlx:"lease_key,primaryKey=true,required=true"`
	OwnerId    string    `sqlx:"owner_id,required=true"`
	LeaseToken string    `sqlx:"lease_token,required=true"`
	LeaseUntil time.Time `sqlx:"lease_until,required=true"`
	CreatedAt  time.Time `sqlx:"created_at,required=true"`
	UpdatedAt  time.Time `sqlx:"updated_at,required=true"`
}

type WriterKeysRow struct {
	LeaseKey string `sqlx:"lease_key"`
}
