// Code generated by Datly for writer; DO NOT EDIT.

package delete

func (input *Input) SetTrusted(value bool) {
	if input == nil {
		return
	}
	input.Trusted = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Trusted = true
}

func (input *Input) SetThreadIDs(value []string) {
	if input == nil {
		return
	}
	input.ThreadIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ThreadIDs = true
}

func (input *Input) SetRunKeys(value []string) {
	if input == nil {
		return
	}
	input.RunKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.RunKeys = true
}

func (input *Input) SetProtocolEventOnly(value bool) {
	if input == nil {
		return
	}
	input.ProtocolEventOnly = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ProtocolEventOnly = true
}

func (input *Input) SetRows(value []*EventDelete) {
	if input == nil {
		return
	}
	input.Rows = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Rows = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
