// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetPrincipal(value string) {
	if input == nil {
		return
	}
	input.Principal = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Principal = true
}

func (input *Input) SetThreadKey(value string) {
	if input == nil {
		return
	}
	input.ThreadKey = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ThreadKey = true
}

func (input *Input) SetAfterKey(value string) {
	if input == nil {
		return
	}
	input.AfterKey = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.AfterKey = true
}

func (input *Input) SetAfterSequence(value int64) {
	if input == nil {
		return
	}
	input.AfterSequence = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.AfterSequence = true
}
