// Code generated by Datly for writer; DO NOT EDIT.

package write

// Input is the generated input scaffold for writer.
type Input struct {
	Internal                  bool                      `parameter:"Internal,kind=reportaccess,in=internal,dataType=bool,required=true"`
	OwnerSubject              *string                   `parameter:"OwnerSubject,kind=visibility,in=subject,dataType=*string,required=true" predicate:"equal,group=8,report_run,owner_id"`
	OrphanDetach              bool                      `parameter:"OrphanDetach,kind=orphandetach,in=enabledDetach,dataType=bool,required=false"`
	OrphanColumn              string                    `parameter:"OrphanColumn,kind=orphandetach,in=column,dataType=string,required=false"`
	Mode                      string                    `parameter:"Mode,kind=query,in=mode,dataType=string,required=true"`
	DesiredRevision           int64                     `parameter:"DesiredRevision,kind=query,in=desiredRevision,dataType=int64,required=false"`
	ExpectedRequestID         string                    `parameter:"ExpectedRequestID,kind=query,in=expectedRequestId,dataType=string,required=false" predicate:"equal,group=8,report_run,ui_run_request_id"`
	Runs                      []*Run                    `parameter:"Runs,kind=body,in=data,dataType=[]*Run" view:"writer,onDeleteNotFound=error,type=Run,entityHooks=Lifecycle,table=report_run,mutationPredicate=8" sql:"uri=reporting_run_write_writer:sql/writer.sql"`
	WriterKeys                []WriterKeysRow           `parameter:"WriterKeys,kind=param,in=Runs,cardinality=Many" codec:"structql,'uri=reporting_run_write_writer:sql/writer_keys.sql'"`
	CurrentWriter             []*CurrentWriterView      `parameter:"CurrentWriter,kind=view,in=CurrentWriter,cardinality=Many" view:"CurrentWriter,table=report_run" sql:"uri=reporting_run_write_writer:sql/current_writer.sql"`
	_writerHandlerReadIndexes *WriterHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                       *InputHas                 `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Internal          bool
	OwnerSubject      bool
	OrphanDetach      bool
	OrphanColumn      bool
	Mode              bool
	DesiredRevision   bool
	ExpectedRequestID bool
	Runs              bool
	WriterKeys        bool
	CurrentWriter     bool
}
