// Code generated by Datly for writer; DO NOT EDIT.

package write

// Input is the generated input scaffold for writer.
type Input struct {
	Rows []*Event  `parameter:"Rows,kind=body,in=data,dataType=[]*Event" view:"writer,type=Event,entityHooks=Lifecycle,table=call_payload" sql:"uri=agui_event_write_writer:sql/writer.sql"`
	Has  *InputHas `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Rows bool
}
