// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetLockRows(value bool) {
	if input == nil {
		return
	}
	input.LockRows = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.LockRows = true
}

func (input *Input) SetTrusted(value bool) {
	if input == nil {
		return
	}
	input.Trusted = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Trusted = true
}

func (input *Input) SetClaimKey(value string) {
	if input == nil {
		return
	}
	input.ClaimKey = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ClaimKey = true
}

func (input *Input) SetTurnID(value string) {
	if input == nil {
		return
	}
	input.TurnID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.TurnID = true
}

func (input *Input) SetRuleID(value string) {
	if input == nil {
		return
	}
	input.RuleID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.RuleID = true
}

func (input *Input) SetState(value string) {
	if input == nil {
		return
	}
	input.State = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.State = true
}

func (input *Input) SetTurnIDs(value []string) {
	if input == nil {
		return
	}
	input.TurnIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.TurnIDs = true
}
