// Code generated by Datly for reader; DO NOT EDIT.

package read

// Input is the generated input scaffold for reader.
type Input struct {
	Trusted  bool      `parameter:"Trusted,kind=claimaccess,in=internal,dataType=bool,required=true"`
	ClaimKey string    `parameter:"ClaimKey,kind=query,in=claimKey,dataType=string,required=false" predicate:"equal,c,claim_key"`
	TurnID   string    `parameter:"TurnID,kind=query,in=turnId,dataType=string,required=false" predicate:"equal,c,turn_id"`
	RuleID   string    `parameter:"RuleID,kind=query,in=ruleId,dataType=string,required=false" predicate:"equal,c,rule_id"`
	State    string    `parameter:"State,kind=query,in=state,dataType=string,required=false" predicate:"equal,c,state"`
	TurnIDs  []string  `parameter:"TurnIDs,kind=query,in=turnIds,dataType=[]string,required=false" predicate:"in,c,turn_id"`
	Has      *InputHas `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Trusted  bool
	ClaimKey bool
	TurnID   bool
	RuleID   bool
	State    bool
	TurnIDs  bool
}
