init:
  - name: projectRoot
    when: $params.projectRoot
    value: $params.projectRoot
    else: $WorkingDirectory(../..)

pipeline:
  snapshot:
    action: exec:run
    checkError: true
    commands:
      - cd $projectRoot
      - rm -rf bin/datly-regeneration-before
      - cp -R internal/datly bin/datly-regeneration-before
  transcribe:
    action: run
    request: '@transcribe'
    params:
      projectRoot: $projectRoot
  compare:
    action: exec:run
    checkError: true
    commands:
      - cd $projectRoot
      - diff -ru bin/datly-regeneration-before internal/datly
