// Code generated by Datly for reader; DO NOT EDIT.

package cube

// ModelCallReportView is generated canonical view metadata for reader.
type ModelCallReportView struct {
	ConversationId                     string   `groupable:"true" sqlx:"conversation_id" json:"conversationId"`
	Provider                           string   `groupable:"true" sqlx:"provider,required=true" json:"provider"`
	Model                              string   `groupable:"true" sqlx:"model,required=true" json:"model"`
	ModelKind                          string   `groupable:"true" sqlx:"model_kind,required=true" json:"modelKind"`
	Status                             string   `groupable:"true" sqlx:"status,required=true" json:"status"`
	ExecutionRole                      string   `groupable:"true" sqlx:"execution_role" json:"executionRole"`
	RecordCount                        int      `groupable:"false" sqlx:"record_count" json:"recordCount"`
	Cost                               *float64 `groupable:"false" sqlx:"cost" json:"cost"`
	PromptTokens                       *int     `groupable:"false" sqlx:"prompt_tokens" json:"promptTokens"`
	PromptCachedTokens                 *int     `groupable:"false" sqlx:"prompt_cached_tokens" json:"promptCachedTokens"`
	PromptAudioTokens                  *int     `groupable:"false" sqlx:"prompt_audio_tokens" json:"promptAudioTokens"`
	CompletionTokens                   *int     `groupable:"false" sqlx:"completion_tokens" json:"completionTokens"`
	CompletionReasoningTokens          *int     `groupable:"false" sqlx:"completion_reasoning_tokens" json:"completionReasoningTokens"`
	CompletionAudioTokens              *int     `groupable:"false" sqlx:"completion_audio_tokens" json:"completionAudioTokens"`
	CompletionAcceptedPredictionTokens *int     `groupable:"false" sqlx:"completion_accepted_prediction_tokens" json:"completionAcceptedPredictionTokens"`
	CompletionRejectedPredictionTokens *int     `groupable:"false" sqlx:"completion_rejected_prediction_tokens" json:"completionRejectedPredictionTokens"`
	TotalTokens                        *int     `groupable:"false" sqlx:"total_tokens" json:"totalTokens"`
}
