// Code generated by Datly for reader; DO NOT EDIT.

package read

// Input is the generated input scaffold for reader.
type Input struct {
	Trusted       bool      `parameter:"Trusted,kind=conversationtreescope,in=internal,dataType=bool,required=true"`
	IDs           []string  `parameter:"IDs,kind=query,in=ids,dataType=[]string,required=false" predicate:"in,c,id"`
	ParentIDs     []string  `parameter:"ParentIDs,kind=query,in=parentIds,dataType=[]string,required=false" predicate:"in,c,conversation_parent_id"`
	ParentTurnIDs []string  `parameter:"ParentTurnIDs,kind=query,in=parentTurnIds,dataType=[]string,required=false" predicate:"in,c,conversation_parent_turn_id"`
	Has           *InputHas `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Trusted       bool
	IDs           bool
	ParentIDs     bool
	ParentTurnIDs bool
}
