// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	response "github.com/viant/xdatly/response"
)

// UserOutput is the generated output scaffold for reader.
type UserOutput struct {
	response.Status `parameter:",kind=output,in=status"`
	Metrics         response.Metrics `parameter:",kind=output,in=metrics"`
	Data            []*UserView      `parameter:"Data,kind=output,in=view,dataType=[]*UserView" view:"reader,type=UserView,table=users" sql:"uri=datly_user_read_reader:sql/reader.sql"`
}
