package run

import (
	"context"
	"embed"
	"fmt"
	"github.com/viant/datly"
	"github.com/viant/datly/repository"
	"github.com/viant/datly/repository/contract"
	"github.com/viant/datly/view"
	"github.com/viant/xdatly/handler/response"
	"github.com/viant/xdatly/types/core"
	"github.com/viant/xdatly/types/custom/dependency/checksum"
	"reflect"
	"time"
)

// Code generated by datly. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

func init() {
	core.RegisterType("run", "StaleRunsInput", reflect.TypeOf(StaleRunsInput{}), checksum.GeneratedTime)
	core.RegisterType("run", "StaleRunsOutput", reflect.TypeOf(StaleRunsOutput{}), checksum.GeneratedTime)
}

//go:embed stale_runs/*.sql
var StaleRunsFS embed.FS

type StaleRunsInput struct {
	HeartbeatBefore time.Time          `parameter:",kind=query,in=heartbeatBefore" predicate:"expr,group=0,(t.last_heartbeat_at IS NULL OR t.last_heartbeat_at < ?)"`
	WorkerHost      string             `parameter:",kind=query,in=workerHost" predicate:"equal,group=0,t,worker_host"`
	Has             *StaleRunsInputHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-"`
}

type StaleRunsInputHas struct {
	HeartbeatBefore bool
	WorkerHost      bool
}

type StaleRunsOutput struct {
	response.Status `parameter:",kind=output,in=status" json:",omitempty"`
	Data            []*StaleRunsView `parameter:",kind=output,in=view" view:"stale_runs,batch=10000,relationalConcurrency=1" sql:"uri=stale_runs/stale_runs.sql"`
	Metrics         response.Metrics `parameter:",kind=output,in=metrics"`
}

type StaleRunsView struct {
	AgentId               *string    `sqlx:"agent_id"`
	Attempt               int        `sqlx:"attempt"`
	AuthAudience          *string    `sqlx:"auth_audience"`
	AuthAuthority         *string    `sqlx:"auth_authority"`
	CheckpointData        *string    `sqlx:"checkpoint_data"`
	CheckpointMessageId   *string    `sqlx:"checkpoint_message_id"`
	CheckpointResponseId  *string    `sqlx:"checkpoint_response_id"`
	CompletedAt           *time.Time `sqlx:"completed_at"`
	ConversationId        *string    `sqlx:"conversation_id"`
	ConversationKind      string     `sqlx:"conversation_kind"`
	CreatedAt             time.Time  `sqlx:"created_at"`
	EffectiveUserId       *string    `sqlx:"effective_user_id"`
	ErrorCode             *string    `sqlx:"error_code"`
	ErrorMessage          *string    `sqlx:"error_message"`
	HeartbeatIntervalSec  *int       `sqlx:"heartbeat_interval_sec"`
	Id                    string     `sqlx:"id"`
	Iteration             int        `sqlx:"iteration"`
	LastHeartbeatAt       *time.Time `sqlx:"last_heartbeat_at"`
	LeaseOwner            *string    `sqlx:"lease_owner"`
	LeaseUntil            *time.Time `sqlx:"lease_until"`
	MaxIterations         *int       `sqlx:"max_iterations"`
	Model                 *string    `sqlx:"model"`
	ModelProvider         *string    `sqlx:"model_provider"`
	PreconditionPassed    *int       `sqlx:"precondition_passed"`
	PreconditionRanAt     *time.Time `sqlx:"precondition_ran_at"`
	PreconditionResult    *string    `sqlx:"precondition_result"`
	ResumedFromRunId      *string    `sqlx:"resumed_from_run_id"`
	ScheduleId            *string    `sqlx:"schedule_id"`
	ScheduledFor          *time.Time `sqlx:"scheduled_for"`
	SecurityContext       *string    `sqlx:"security_context"`
	StartedAt             *time.Time `sqlx:"started_at"`
	Status                string     `sqlx:"status"`
	TurnId                *string    `sqlx:"turn_id"`
	UpdatedAt             *time.Time `sqlx:"updated_at"`
	UsageCompletionTokens *int       `sqlx:"usage_completion_tokens"`
	UsageCost             *float64   `sqlx:"usage_cost"`
	UsagePromptTokens     *int       `sqlx:"usage_prompt_tokens"`
	UsageTotalTokens      *int       `sqlx:"usage_total_tokens"`
	UserCredUrl           *string    `sqlx:"user_cred_url"`
	WorkerHost            *string    `sqlx:"worker_host"`
	WorkerId              *string    `sqlx:"worker_id"`
	WorkerPid             *int       `sqlx:"worker_pid"`
}

var StaleRunsPathURI = "/v1/api/agently/run/stale/stale"

func DefineStaleRunsComponent(ctx context.Context, srv *datly.Service) error {
	aComponent, err := repository.NewComponent(
		contract.NewPath("GET", StaleRunsPathURI),
		repository.WithResource(srv.Resource()),
		repository.WithContract(
			reflect.TypeOf(StaleRunsInput{}),
			reflect.TypeOf(StaleRunsOutput{}), &StaleRunsFS, view.WithConnectorRef("agently")))

	if err != nil {
		return fmt.Errorf("failed to create StaleRuns component: %w", err)
	}
	if err := srv.AddComponent(ctx, aComponent); err != nil {
		return fmt.Errorf("failed to add StaleRuns component: %w", err)
	}
	return nil
}

func (i *StaleRunsInput) EmbedFS() *embed.FS {
	return &StaleRunsFS
}
