// Code generated by Datly for writer; DO NOT EDIT.

package write

func (entity *Document) GetId() *string {
	return entity.Id
}
func (entity *Document) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.Id = true
}
func (entity *Document) GetInlineBody() []byte {
	return entity.InlineBody
}
func (entity *Document) SetInlineBody(value []byte) {
	entity.InlineBody = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.InlineBody = true
}
func (entity *Document) GetRunId() *string {
	return entity.RunId
}
func (entity *Document) SetRunId(value *string) {
	entity.RunId = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.RunId = true
}
func (entity *Document) GetKind() *string {
	return entity.Kind
}
func (entity *Document) SetKind(value *string) {
	entity.Kind = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.Kind = true
}
func (entity *Document) GetSubtype() *string {
	return entity.Subtype
}
func (entity *Document) SetSubtype(value *string) {
	entity.Subtype = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.Subtype = true
}
func (entity *Document) GetSchemaRef() *string {
	return entity.SchemaRef
}
func (entity *Document) SetSchemaRef(value *string) {
	entity.SchemaRef = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.SchemaRef = true
}
func (entity *Document) GetMimeType() *string {
	return entity.MimeType
}
func (entity *Document) SetMimeType(value *string) {
	entity.MimeType = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.MimeType = true
}
func (entity *Document) GetStorage() *string {
	return entity.Storage
}
func (entity *Document) SetStorage(value *string) {
	entity.Storage = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.Storage = true
}
func (entity *Document) GetCompression() *string {
	return entity.Compression
}
func (entity *Document) SetCompression(value *string) {
	entity.Compression = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.Compression = true
}
func (entity *Document) GetDigest() *string {
	return entity.Digest
}
func (entity *Document) SetDigest(value *string) {
	entity.Digest = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.Digest = true
}
func (entity *Document) GetSizeBytes() *int {
	return entity.SizeBytes
}
func (entity *Document) SetSizeBytes(value *int) {
	entity.SizeBytes = value
	if entity.Has == nil {
		entity.Has = &DocumentHas{}
	}
	entity.Has.SizeBytes = true
}
