// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetTrusted(value bool) {
	if input == nil {
		return
	}
	input.Trusted = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Trusted = true
}

func (input *Input) SetIDs(value []string) {
	if input == nil {
		return
	}
	input.IDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.IDs = true
}

func (input *Input) SetConversationIDs(value []string) {
	if input == nil {
		return
	}
	input.ConversationIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ConversationIDs = true
}

func (input *Input) SetTurnIDs(value []string) {
	if input == nil {
		return
	}
	input.TurnIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.TurnIDs = true
}

func (input *Input) SetScheduleIDs(value []string) {
	if input == nil {
		return
	}
	input.ScheduleIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ScheduleIDs = true
}

func (input *Input) SetResumedFromRunIDs(value []string) {
	if input == nil {
		return
	}
	input.ResumedFromRunIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ResumedFromRunIDs = true
}
