// Code generated by Datly for reader; DO NOT EDIT.

package read

// Run is generated canonical view metadata for reader.
type Run struct {
	Id                   string  `sqlx:"id,primaryKey=true" json:"id"`
	Status               string  `sqlx:"status,required=true" json:"status"`
	ConversationKind     string  `sqlx:"conversation_kind,required=true" json:"conversationKind"`
	ConversationId       *string `sqlx:"conversation_id,refTable=conversation,refColumn=id" json:"conversationId"`
	TurnId               *string `sqlx:"turn_id,refTable=turn,refColumn=id" json:"turnId"`
	ScheduleId           *string `sqlx:"schedule_id,refTable=schedule,refColumn=id" json:"scheduleId"`
	ResumedFromRunId     *string `sqlx:"resumed_from_run_id" json:"resumedFromRunId"`
	LeaseUntilRaw        *string `sqlx:"lease_until_raw" json:"leaseUntilRaw"`
	HeartbeatRaw         *string `sqlx:"heartbeat_raw" json:"heartbeatRaw"`
	HeartbeatIntervalSec *int    `sqlx:"heartbeat_interval_sec" json:"heartbeatIntervalSec"`
	ActivityRaw          *string `sqlx:"activity_raw" json:"activityRaw"`
}
