// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// ToolCall is generated canonical view metadata for writer.
type ToolCall struct {
	ShouldDelete      bool         `sqlx:"-" writer:"delete" json:"shouldDelete,omitempty"`
	ResponseOverflow  bool         `sqlx:"-" json:"responseOverflow,omitempty"`
	MessageId         string       `validate:"required" sqlx:"message_id,primaryKey,refTable=message,refColumn=id" json:"messageId"`
	OpId              string       `validate:"required" json:"opId" sqlx:"op_id,required=true"`
	Attempt           int          `json:"attempt" sqlx:"attempt,required=true"`
	ToolName          string       `validate:"required" json:"toolName" sqlx:"tool_name,required=true"`
	ToolKind          string       `validate:"required" json:"toolKind" sqlx:"tool_kind,required=true"`
	Status            string       `validate:"required" json:"status" sqlx:"status,required=true"`
	Cost              *float64     `sqlx:"cost" json:"cost,omitempty"`
	RequestPayloadId  *string      `json:"requestPayloadId" sqlx:"request_payload_id,refTable=call_payload,refColumn=id"`
	ResponsePayloadId *string      `json:"responsePayloadId" sqlx:"response_payload_id,refTable=call_payload,refColumn=id"`
	TurnId            *string      `sqlx:"turn_id,refTable=turn,refColumn=id" json:"turnId,omitempty"`
	RequestHash       *string      `sqlx:"request_hash" json:"requestHash,omitempty"`
	ErrorCode         *string      `sqlx:"error_code" json:"errorCode,omitempty"`
	ErrorMessage      *string      `sqlx:"error_message" json:"errorMessage,omitempty"`
	Retriable         *int         `sqlx:"retriable" json:"retriable,omitempty"`
	StartedAt         *time.Time   `sqlx:"started_at" json:"startedAt,omitempty"`
	CompletedAt       *time.Time   `sqlx:"completed_at" json:"completedAt,omitempty"`
	LatencyMs         *int         `sqlx:"latency_ms" json:"latencyMs,omitempty"`
	TraceId           *string      `sqlx:"trace_id" json:"traceId,omitempty"`
	SpanId            *string      `sqlx:"span_id" json:"spanId,omitempty"`
	RunId             *string      `sqlx:"run_id" json:"runId,omitempty"`
	Iteration         *int         `sqlx:"iteration" json:"iteration,omitempty"`
	Has               *ToolCallHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"ToolCallHas"`
}

type ToolCallHas struct {
	ShouldDelete      bool
	MessageId         bool
	OpId              bool
	Attempt           bool
	ToolName          bool
	ToolKind          bool
	Status            bool
	Cost              bool
	RequestPayloadId  bool
	ResponsePayloadId bool
	TurnId            bool
	RequestHash       bool
	ErrorCode         bool
	ErrorMessage      bool
	Retriable         bool
	StartedAt         bool
	CompletedAt       bool
	LatencyMs         bool
	TraceId           bool
	SpanId            bool
	RunId             bool
	Iteration         bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	ResponseOverflow  bool       `sqlx:"response_overflow" json:"responseOverflow,omitempty"`
	MessageId         string     `validate:"required" sqlx:"message_id,primaryKey,refTable=message,refColumn=id" json:"messageId"`
	OpId              string     `validate:"required" json:"opId" sqlx:"op_id,required=true"`
	Attempt           int        `json:"attempt" sqlx:"attempt,required=true"`
	ToolName          string     `validate:"required" json:"toolName" sqlx:"tool_name,required=true"`
	ToolKind          string     `validate:"required" json:"toolKind" sqlx:"tool_kind,required=true"`
	Status            string     `validate:"required" json:"status" sqlx:"status,required=true"`
	Cost              *float64   `sqlx:"cost" json:"cost,omitempty"`
	RequestPayloadId  *string    `json:"requestPayloadId" sqlx:"request_payload_id,refTable=call_payload,refColumn=id"`
	ResponsePayloadId *string    `json:"responsePayloadId" sqlx:"response_payload_id,refTable=call_payload,refColumn=id"`
	TurnId            *string    `sqlx:"turn_id,refTable=turn,refColumn=id" json:"turnId,omitempty"`
	RequestHash       *string    `sqlx:"request_hash" json:"requestHash,omitempty"`
	ErrorCode         *string    `sqlx:"error_code" json:"errorCode,omitempty"`
	ErrorMessage      *string    `sqlx:"error_message" json:"errorMessage,omitempty"`
	Retriable         *int       `sqlx:"retriable" json:"retriable,omitempty"`
	StartedAt         *time.Time `sqlx:"started_at" json:"startedAt,omitempty"`
	CompletedAt       *time.Time `sqlx:"completed_at" json:"completedAt,omitempty"`
	LatencyMs         *int       `sqlx:"latency_ms" json:"latencyMs,omitempty"`
	TraceId           *string    `sqlx:"trace_id" json:"traceId,omitempty"`
	SpanId            *string    `sqlx:"span_id" json:"spanId,omitempty"`
	RunId             *string    `sqlx:"run_id" json:"runId,omitempty"`
	Iteration         *int       `sqlx:"iteration" json:"iteration,omitempty"`
}

type WriterKeysRow struct {
	MessageId string `sqlx:"message_id"`
}
