// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetPrincipal(value string) {
	if input == nil {
		return
	}
	input.Principal = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Principal = true
}

func (input *Input) SetConversationID(value string) {
	if input == nil {
		return
	}
	input.ConversationID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ConversationID = true
}

func (input *Input) SetActive(value bool) {
	if input == nil {
		return
	}
	input.Active = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Active = true
}
