SELECT message.ELICITATION, message.id, message.conversation_id, message.turn_id, message.archived, message.sequence, message.created_at, message.updated_at, message.created_by_user_id, message.status, message.mode, message.role, message.type, message.content, message.raw_content, message.summary, message.context_summary, message.tags, message.interim, message.elicitation_id, message.parent_message_id, message.superseded_by, message.linked_conversation_id, message.attachment_payload_id, message.elicitation_payload_id, message.tool_name, message.embedding_index, message.preamble, message.iteration, message.phase FROM (
SELECT
    m.id,
    m.conversation_id,
    m.turn_id,
    m.archived,
    m.sequence,
    m.created_at,
    m.updated_at,
    m.created_by_user_id,
    m.status,
    m.mode,
    m.role,
    m.type,
    m.content,
    m.raw_content,
    m.summary,
    m.context_summary,
    m.tags,
    m.interim,
    m.elicitation_id,
    m.parent_message_id,
    m.superseded_by,
    NULLIF(m.linked_conversation_id, '') AS linked_conversation_id,
    m.attachment_payload_id,
    m.elicitation_payload_id,
    m.tool_name,
    m.embedding_index,
    m.preamble,
    m.iteration,
    m.phase,
    NULL AS ELICITATION
FROM message m
${predicate.Builder().CombineOr($predicate.FilterGroup(4, "AND")).Build("WHERE")}
) message