// Code generated by Datly for reader; DO NOT EDIT.

package read

// RunStepsInput is the generated input scaffold for reader.
type RunStepsInput struct {
	InternalMode      bool              `parameter:"InternalMode,kind=runaccess,in=internal,dataType=bool,required=true"`
	VisibilitySubject *string           `parameter:"VisibilitySubject,kind=visibility,in=subject,dataType=*string,required=true"`
	RunID             string            `parameter:"RunID,kind=query,in=runId,dataType=string,required=false" predicate:"equal,run_steps,run_id"`
	Iteration         int               `parameter:"Iteration,kind=query,in=iteration,dataType=int,required=false" predicate:"equal,run_steps,iteration"`
	StepTypes         []string          `parameter:"StepTypes,kind=query,in=stepTypes,dataType=[]string,required=false" predicate:"in,run_steps,step_type"`
	CursorBefore      string            `parameter:"CursorBefore,kind=query,in=cursorBefore,dataType=string,required=false" predicate:"expr,run_steps.message_id < ?"`
	CursorAfter       string            `parameter:"CursorAfter,kind=query,in=cursorAfter,dataType=string,required=false" predicate:"expr,run_steps.message_id > ?"`
	Fields            []string          `parameter:"Fields,kind=query,in=fields,dataType=[]string,required=false,cacheable=false" querySelector:"view=reader,property=fields"`
	Limit             int               `parameter:"Limit,kind=query,in=limit,dataType=int,required=false,cacheable=false" querySelector:"view=reader,property=limit"`
	Offset            int               `parameter:"Offset,kind=query,in=offset,dataType=int,required=false,cacheable=false" querySelector:"view=reader,property=offset"`
	OrderBy           string            `parameter:"OrderBy,kind=query,in=orderBy,dataType=string,required=false,cacheable=false" querySelector:"view=reader,property=orderBy"`
	Has               *RunStepsInputHas `setMarker:"true" typeName:"RunStepsInputHas" json:"-" sqlx:"-"`
}

type RunStepsInputHas struct {
	InternalMode      bool
	VisibilitySubject bool
	RunID             bool
	Iteration         bool
	StepTypes         bool
	CursorBefore      bool
	CursorAfter       bool
	Fields            bool
	Limit             bool
	Offset            bool
	OrderBy           bool
}
