// Code generated by Datly for reader; DO NOT EDIT.

package read

// Input is the generated input scaffold for reader.
type Input struct {
	LockRows        bool      `parameter:"LockRows,kind=investigationaccess,in=lock,dataType=bool,required=false"`
	Trusted         bool      `parameter:"Trusted,kind=investigationaccess,in=internal,dataType=bool,required=true"`
	ID              string    `parameter:"ID,kind=query,in=id,dataType=string,required=false" predicate:"equal,i,id"`
	ConversationID  string    `parameter:"ConversationID,kind=query,in=conversationId,dataType=string,required=false" predicate:"equal,i,conversation_id"`
	CreatedBy       string    `parameter:"CreatedBy,kind=query,in=createdBy,dataType=string,required=false" predicate:"equal,i,created_by"`
	ConversationIDs []string  `parameter:"ConversationIDs,kind=query,in=conversationIds,dataType=[]string,required=false" predicate:"in,i,conversation_id"`
	Has             *InputHas `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	LockRows        bool
	Trusted         bool
	ID              bool
	ConversationID  bool
	CreatedBy       bool
	ConversationIDs bool
}
