// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

// Investigation is generated canonical view metadata for reader.
type Investigation struct {
	Id             string    `sqlx:"id,primaryKey=true" json:"id"`
	Created        time.Time `sqlx:"created,required=true" json:"created"`
	Title          *string   `sqlx:"title" json:"title"`
	CreatedBy      *string   `sqlx:"created_by" json:"createdBy"`
	ConversationId *string   `sqlx:"conversation_id,refTable=conversation,refColumn=id" json:"conversationId"`
	Summary        *string   `sqlx:"summary" json:"summary"`
	AdOrderId      *int      `sqlx:"ad_order_id" json:"adOrderId"`
	Verdict        *string   `sqlx:"verdict" json:"verdict"`
}
