// Code generated by Datly for reader; DO NOT EDIT.

package read

// Output is the generated output scaffold for reader.
type Output struct {
	Data []*LegacyRun `parameter:"Data,kind=output,in=view,dataType=[]*LegacyRun" view:"reader,type=LegacyRun,rowLock=schedule_run r,rowLockOrder=r.id,table=schedule_run,selectorProjection=true,selectorLimit=true" sql:"uri=datly_legacyrun_read_reader:sql/reader.sql"`
}
