// Code generated by Datly for reader; DO NOT EDIT.

package read

// GoalInput is the generated input scaffold for reader.
type GoalInput struct {
	LockRows        bool          `parameter:"LockRows,kind=goalaccess,in=lock,dataType=bool,required=false"`
	ConversationID  string        `parameter:"ConversationID,kind=path,in=conversationId,dataType=string,required=false" predicate:"equal,t,conversation_id"`
	ConversationIDs []string      `parameter:"ConversationIDs,kind=query,in=conversationIds,dataType=[]string,required=false" predicate:"in,t,conversation_id"`
	GraphMode       bool          `parameter:"GraphMode,kind=goalaccess,in=graph,dataType=bool,required=false"`
	Ids             []string      `parameter:"Ids,kind=query,in=ids,dataType=[]string,required=false" predicate:"in,t,id"`
	Has             *GoalInputHas `setMarker:"true" typeName:"GoalInputHas" json:"-" sqlx:"-"`
}

type GoalInputHas struct {
	LockRows        bool
	ConversationID  bool
	ConversationIDs bool
	GraphMode       bool
	Ids             bool
}
