// Code generated by Datly for writer; DO NOT EDIT.

package write

// Input is the generated input scaffold for writer.
type Input struct {
	Internal                  bool                      `parameter:"Internal,kind=reportaccess,in=internal,dataType=bool,required=true"`
	OwnerSubject              *string                   `parameter:"OwnerSubject,kind=visibility,in=subject,dataType=*string,required=true" predicate:"equal,group=8,report_export_artifact,owner_id"`
	OrphanDelete              bool                      `parameter:"OrphanDelete,kind=orphandelete,in=enabledDelete,dataType=bool,required=false"`
	Mode                      string                    `parameter:"Mode,kind=query,in=mode,dataType=string,required=true"`
	ExpectedJobID             string                    `parameter:"ExpectedJobID,kind=query,in=expectedJobId,dataType=string,required=false" predicate:"equal,group=8,report_export_artifact,job_id"`
	Artifacts                 []*Artifact               `parameter:"Artifacts,kind=body,in=data,dataType=[]*Artifact" view:"writer,onDeleteNotFound=error,type=Artifact,entityHooks=Lifecycle,table=report_export_artifact,mutationPredicate=8" sql:"uri=reporting_artifact_write_writer:sql/writer.sql"`
	WriterKeys                []WriterKeysRow           `parameter:"WriterKeys,kind=param,in=Artifacts,cardinality=Many" codec:"structql,'uri=reporting_artifact_write_writer:sql/writer_keys.sql'"`
	CurrentWriter             []*CurrentWriterView      `parameter:"CurrentWriter,kind=view,in=CurrentWriter,cardinality=Many" view:"CurrentWriter,table=report_export_artifact" sql:"uri=reporting_artifact_write_writer:sql/current_writer.sql"`
	_writerHandlerReadIndexes *WriterHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                       *InputHas                 `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Internal      bool
	OwnerSubject  bool
	OrphanDelete  bool
	Mode          bool
	ExpectedJobID bool
	Artifacts     bool
	WriterKeys    bool
	CurrentWriter bool
}
