// Code generated by Datly for writer; DO NOT EDIT.

package write

func (input *Input) SetInternal(value bool) {
	if input == nil {
		return
	}
	input.Internal = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Internal = true
}

func (input *Input) SetOwnerSubject(value *string) {
	if input == nil {
		return
	}
	input.OwnerSubject = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OwnerSubject = true
}

func (input *Input) SetOrphanDelete(value bool) {
	if input == nil {
		return
	}
	input.OrphanDelete = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanDelete = true
}

func (input *Input) SetMode(value string) {
	if input == nil {
		return
	}
	input.Mode = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Mode = true
}

func (input *Input) SetExpectedJobID(value string) {
	if input == nil {
		return
	}
	input.ExpectedJobID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExpectedJobID = true
}

func (input *Input) SetArtifacts(value []*Artifact) {
	if input == nil {
		return
	}
	input.Artifacts = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Artifacts = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
