// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// Artifact is generated canonical view metadata for writer.
type Artifact struct {
	ShouldDelete    bool         `json:"shouldDelete,omitempty" sqlx:"-" writer:"delete"`
	ArtifactId      string       `sqlx:"artifact_id,primaryKey=true,required=true"`
	JobId           string       `sqlx:"job_id,required=true,refTable=report_export_job,refColumn=job_id"`
	ArtifactRef     string       `sqlx:"artifact_ref,required=true"`
	OwnerId         string       `sqlx:"owner_id,required=true"`
	Format          string       `sqlx:"format,required=true"`
	ContentType     string       `sqlx:"content_type,required=true"`
	InlineData      []byte       `sqlx:"inline_data"`
	CreatedAt       time.Time    `sqlx:"created_at,required=true"`
	RetentionTtlSec int64        `sqlx:"retention_ttl_sec,required=true"`
	Has             *ArtifactHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"ArtifactHas"`
}

type ArtifactHas struct {
	ShouldDelete    bool
	ArtifactId      bool
	JobId           bool
	ArtifactRef     bool
	OwnerId         bool
	Format          bool
	ContentType     bool
	InlineData      bool
	CreatedAt       bool
	RetentionTtlSec bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	ArtifactId      string    `sqlx:"artifact_id,primaryKey=true,required=true"`
	JobId           string    `sqlx:"job_id,required=true,refTable=report_export_job,refColumn=job_id"`
	ArtifactRef     string    `sqlx:"artifact_ref,required=true"`
	OwnerId         string    `sqlx:"owner_id,required=true"`
	Format          string    `sqlx:"format,required=true"`
	ContentType     string    `sqlx:"content_type,required=true"`
	InlineData      []byte    `sqlx:"inline_data"`
	CreatedAt       time.Time `sqlx:"created_at,required=true"`
	RetentionTtlSec int64     `sqlx:"retention_ttl_sec,required=true"`
}

type WriterKeysRow struct {
	ArtifactId string `sqlx:"artifact_id"`
}
