// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetInternal(value bool) {
	if input == nil {
		return
	}
	input.Internal = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Internal = true
}

func (input *Input) SetOwnerSubject(value *string) {
	if input == nil {
		return
	}
	input.OwnerSubject = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OwnerSubject = true
}

func (input *Input) SetOwnerID(value string) {
	if input == nil {
		return
	}
	input.OwnerID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OwnerID = true
}

func (input *Input) SetConversationID(value string) {
	if input == nil {
		return
	}
	input.ConversationID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ConversationID = true
}

func (input *Input) SetConversationIDs(value []string) {
	if input == nil {
		return
	}
	input.ConversationIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ConversationIDs = true
}

func (input *Input) SetActiveReportRunID(value string) {
	if input == nil {
		return
	}
	input.ActiveReportRunID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ActiveReportRunID = true
}

func (input *Input) SetActiveReportRunIDs(value []string) {
	if input == nil {
		return
	}
	input.ActiveReportRunIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ActiveReportRunIDs = true
}
