// Code generated by Datly for reader; DO NOT EDIT.

package read

// Input is the generated input scaffold for reader.
type Input struct {
	Internal           bool      `parameter:"Internal,kind=reportaccess,in=internal,dataType=bool,required=true"`
	OwnerSubject       *string   `parameter:"OwnerSubject,kind=visibility,in=subject,dataType=*string,required=true"`
	OwnerID            string    `parameter:"OwnerID,kind=query,in=ownerId,dataType=string,required=false" predicate:"equal,c,owner_id"`
	ConversationID     string    `parameter:"ConversationID,kind=query,in=conversationId,dataType=string,required=false" predicate:"equal,c,conversation_id"`
	ConversationIDs    []string  `parameter:"ConversationIDs,kind=query,in=conversationIds,dataType=[]string,required=false" predicate:"in,c,conversation_id"`
	ActiveReportRunID  string    `parameter:"ActiveReportRunID,kind=query,in=activeReportRunId,dataType=string,required=false" predicate:"equal,c,active_report_run_id"`
	ActiveReportRunIDs []string  `parameter:"ActiveReportRunIDs,kind=query,in=activeReportRunIds,dataType=[]string,required=false" predicate:"in,c,active_report_run_id"`
	LockRows           bool      `parameter:"LockRows,kind=reportaccess,in=lock,dataType=bool,required=false"`
	Has                *InputHas `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Internal           bool
	OwnerSubject       bool
	OwnerID            bool
	ConversationID     bool
	ConversationIDs    bool
	ActiveReportRunID  bool
	ActiveReportRunIDs bool
	LockRows           bool
}
