// Code generated by Datly for reader; DO NOT EDIT.

package read

// Input is the generated input scaffold for reader.
type Input struct {
	Trusted    bool      `parameter:"Trusted,kind=modelcallcleanupscope,in=internal,dataType=bool,required=true"`
	MessageIDs []string  `parameter:"MessageIDs,kind=query,in=messageIDs,dataType=[]string,required=false" predicate:"in,t,message_id"`
	TurnIDs    []string  `parameter:"TurnIDs,kind=query,in=turnIDs,dataType=[]string,required=false" predicate:"in,t,turn_id"`
	Has        *InputHas `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Trusted    bool
	MessageIDs bool
	TurnIDs    bool
}
