// Code generated by Datly for reader; DO NOT EDIT.

package cube

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ReaderDatlyResourceNamespace = "datly_toolcall_cube_reader"

//go:embed "sql/reader.sql"
var ReaderDatlyResources embed.FS
