// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetThreadID(value string) {
	if input == nil {
		return
	}
	input.ThreadID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ThreadID = true
}

func (input *Input) SetTurnID(value string) {
	if input == nil {
		return
	}
	input.TurnID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.TurnID = true
}
