// Code generated by Datly for writer; DO NOT EDIT.

package write

func (input *Input) SetSession(value []*Session) {
	if input == nil {
		return
	}
	input.Session = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Session = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
