pipeline:
  translate:
    action: exec:run
    TimeoutMs: 120000
    checkError: true
    commands:
      - cd $repoPath
      - $repoPath/e2e/bin/datly gen -o=get -u=agently/toolcall/byOp      -s='dql/agently/toolcall/toolcall_by_op.dql' $datlyOptions
