// Code generated by Datly for reader; DO NOT EDIT.

package read

// Input is the generated input scaffold for reader.
type Input struct {
	Principal string    `parameter:"Principal,kind=query,in=principal,dataType=string,required=true"`
	SourceKey string    `parameter:"SourceKey,kind=query,in=sourceKey,dataType=string,required=true"`
	Has       *InputHas `setMarker:"true" typeName:"InputHas" json:"-" sqlx:"-"`
}

type InputHas struct {
	Principal bool
	SourceKey bool
}
