// Code generated by Datly for writer; DO NOT EDIT.

package write

func (input *Input) SetUsers(value []*User) {
	if input == nil {
		return
	}
	input.Users = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Users = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
