// Code generated by Datly for reader; DO NOT EDIT.

package read

// QueueRowsInput is the generated input scaffold for reader.
type QueueRowsInput struct {
	Id              string             `parameter:"Id,kind=query,in=id,dataType=string,required=false" predicate:"equal,q,id"`
	ConversationId  string             `parameter:"ConversationId,kind=query,in=conversationId,dataType=string,required=false" predicate:"equal,q,conversation_id"`
	ConversationIds []string           `parameter:"ConversationIds,kind=query,in=conversationIds,dataType=[]string,required=false" predicate:"in,q,conversation_id"`
	TurnId          string             `parameter:"TurnId,kind=query,in=turnId,dataType=string,required=false" predicate:"equal,q,turn_id"`
	MessageId       string             `parameter:"MessageId,kind=query,in=messageId,dataType=string,required=false" predicate:"equal,q,message_id"`
	QueueStatus     string             `parameter:"QueueStatus,kind=query,in=status,dataType=string,required=false" predicate:"equal,q,status"`
	Has             *QueueRowsInputHas `setMarker:"true" typeName:"QueueRowsInputHas" json:"-" sqlx:"-"`
}

type QueueRowsInputHas struct {
	Id              bool
	ConversationId  bool
	ConversationIds bool
	TurnId          bool
	MessageId       bool
	QueueStatus     bool
}
