// Code generated by Datly for reader; DO NOT EDIT.

package read

// ReportOutput is the generated output scaffold for reader.
type ReportOutput struct {
	Data []*OrphanRow `parameter:"Data,kind=output,in=view,dataType=[]*OrphanRow" view:"reader,type=OrphanRow,selectorLimit=true" sql:"uri=datly_orphanmaintenance_read_reader:sql/reader.sql"`
}
