package tool

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	authctx "github.com/viant/agently-core/internal/auth"
	mcpcfg "github.com/viant/agently-core/protocol/mcp/config"
	scratchpad "github.com/viant/agently-core/protocol/tool/service/scratchpad"
	schema "github.com/viant/mcp-protocol/schema"
)

func TestOutputArtifactDeclarativePointersAndDefaults(t *testing.T) {
	t.Setenv(scratchpad.EnvScratchpadURI, "file://"+filepath.Join(t.TempDir(), "${userID}"))
	ctx := authctx.WithUserInfo(context.Background(), &authctx.UserInfo{Subject: "owner"})
	data := []byte("owned generated file bytes")
	encoded := base64.StdEncoding.EncodeToString(data)
	policy := mcpcfg.OutputArtifact{NamePath: "/structuredContent/files/0/name", Name: "fallback.xlsx", MimeTypePath: "/structuredContent/files/0/mime", MimeType: "application/octet-stream", BytesPath: "/structuredContent/files/0/data", Encoding: "base64"}
	for _, fallback := range []bool{false, true} {
		file := map[string]interface{}{"data": encoded, "name": "generated.xlsx", "mime": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}
		if fallback {
			delete(file, "name")
			file["mime"] = ""
		}
		result := &schema.CallToolResult{StructuredContent: map[string]interface{}{"files": []interface{}{file}, "duplicate": encoded}, Content: []schema.CallToolResultContentElem{schema.TextContent{Type: "text", Text: encoded}}}
		before, err := json.Marshal(result)
		require.NoError(t, err)
		captured, err := captureOutputArtifacts(ctx, result, &policy)
		require.NoError(t, err)
		metadata := captured.StructuredContent.(map[string]interface{})["resources"].([]map[string]interface{})[0]
		if fallback {
			require.Equal(t, "fallback.xlsx", metadata["name"])
			require.Equal(t, "application/octet-stream", metadata["mimeType"])
		} else {
			require.Equal(t, "generated.xlsx", metadata["name"])
		}
		payload, err := scratchpad.New().ReadArtifactPayload(ctx, metadata["uri"].(string))
		require.NoError(t, err)
		require.Equal(t, data, payload)
		after, err := json.Marshal(result)
		require.NoError(t, err)
		require.Equal(t, before, after, "source result is immutable")
		public, err := json.Marshal(captured)
		require.NoError(t, err)
		require.NotContains(t, string(public), encoded)
		require.NotContains(t, string(public), "duplicate")
	}
	type typedFile struct {
		Name string `json:"name"`
		Data string `json:"data"`
		Mime string `json:"mime"`
	}
	typed := &schema.CallToolResult{StructuredContent: &struct {
		Files []typedFile `json:"files"`
	}{Files: []typedFile{{Name: "typed.xlsx", Data: encoded, Mime: "application/octet-stream"}}}}
	_, err := captureOutputArtifacts(ctx, typed, &policy)
	require.NoError(t, err)
	escaped := &schema.CallToolResult{StructuredContent: map[string]interface{}{"a/b": map[string]string{"~bytes": encoded}}}
	_, err = captureOutputArtifacts(ctx, escaped, &mcpcfg.OutputArtifact{BytesPath: "/structuredContent/a~1b/~0bytes", Encoding: "base64"})
	require.NoError(t, err)
}

func TestOutputArtifactPathsRejectMalformedAndEchoMetadata(t *testing.T) {
	t.Setenv(scratchpad.EnvScratchpadURI, "file://"+filepath.Join(t.TempDir(), "${userID}"))
	ctx := authctx.WithUserInfo(context.Background(), &authctx.UserInfo{Subject: "owner"})
	encoded := base64.StdEncoding.EncodeToString([]byte("private workbook bytes"))
	policy := mcpcfg.OutputArtifact{NamePath: "/structuredContent/name", BytesPath: "/structuredContent/data", MimeTypePath: "/structuredContent/mime", Encoding: "base64"}
	for _, file := range []map[string]interface{}{
		{"name": "file.xlsx"},
		{"data": 7},
		{"data": "malformed base64"},
		{"data": encoded, "name": 7},
		{"data": encoded, "mime": true},
		{"data": encoded, "name": "../file.xlsx"},
		{"data": encoded, "name": encoded + ".xlsx"},
		{"data": encoded, "name": strings.Repeat("A", 80) + ".xlsx"},
		{"data": encoded, "mime": "application/" + encoded},
		{"data": encoded, "mime": "bad MIME"},
	} {
		_, err := captureOutputArtifacts(ctx, &schema.CallToolResult{StructuredContent: file}, &policy)
		require.EqualError(t, err, "output artifact capture failed")
	}
	policy.Encoding = "hex"
	_, err := captureOutputArtifacts(ctx, &schema.CallToolResult{StructuredContent: map[string]string{"data": encoded}}, &policy)
	require.Error(t, err)
}

func TestOutputArtifactContentPointerRetainsWireMIME(t *testing.T) {
	t.Setenv(scratchpad.EnvScratchpadURI, "file://"+filepath.Join(t.TempDir(), "${userID}"))
	ctx := authctx.WithUserInfo(context.Background(), &authctx.UserInfo{Subject: "owner"})
	result := binaryOutput([]byte("generated bytes"))
	policy := mcpcfg.OutputArtifact{Name: "file.xlsx", MimeType: "application/octet-stream", BytesPath: "/content/0/resource/blob", Encoding: "base64", MimeTypePath: "/content/0/resource/mimeType"}
	_, err := captureOutputArtifacts(ctx, result, &policy)
	require.NoError(t, err)
	policy.BytesPath = ""
	policy.Encoding = ""
	policy.MimeTypePath = ""
	captured, err := captureOutputArtifacts(ctx, result, &policy)
	require.NoError(t, err)
	resource := captured.StructuredContent.(map[string]interface{})["resources"].([]map[string]interface{})[0]
	require.Equal(t, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", resource["mimeType"])
}
