// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

func (entity *LegacyRun) GetShouldDelete() bool {
	return entity.ShouldDelete
}
func (entity *LegacyRun) SetShouldDelete(value bool) {
	entity.ShouldDelete = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.ShouldDelete = true
}
func (entity *LegacyRun) GetId() string {
	return entity.Id
}
func (entity *LegacyRun) SetId(value string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.Id = true
}
func (entity *LegacyRun) GetScheduleId() string {
	return entity.ScheduleId
}
func (entity *LegacyRun) SetScheduleId(value string) {
	entity.ScheduleId = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.ScheduleId = true
}
func (entity *LegacyRun) GetStatus() string {
	return entity.Status
}
func (entity *LegacyRun) SetStatus(value string) {
	entity.Status = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.Status = true
}
func (entity *LegacyRun) GetConversationKind() string {
	return entity.ConversationKind
}
func (entity *LegacyRun) SetConversationKind(value string) {
	entity.ConversationKind = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.ConversationKind = true
}
func (entity *LegacyRun) GetCreatedAt() *time.Time {
	return entity.CreatedAt
}
func (entity *LegacyRun) SetCreatedAt(value *time.Time) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *LegacyRun) GetUpdatedAt() *time.Time {
	return entity.UpdatedAt
}
func (entity *LegacyRun) SetUpdatedAt(value *time.Time) {
	entity.UpdatedAt = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.UpdatedAt = true
}
func (entity *LegacyRun) GetErrorMessage() *string {
	return entity.ErrorMessage
}
func (entity *LegacyRun) SetErrorMessage(value *string) {
	entity.ErrorMessage = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.ErrorMessage = true
}
func (entity *LegacyRun) GetLeaseOwner() *string {
	return entity.LeaseOwner
}
func (entity *LegacyRun) SetLeaseOwner(value *string) {
	entity.LeaseOwner = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.LeaseOwner = true
}
func (entity *LegacyRun) GetLeaseUntil() *time.Time {
	return entity.LeaseUntil
}
func (entity *LegacyRun) SetLeaseUntil(value *time.Time) {
	entity.LeaseUntil = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.LeaseUntil = true
}
func (entity *LegacyRun) GetPreconditionRanAt() *time.Time {
	return entity.PreconditionRanAt
}
func (entity *LegacyRun) SetPreconditionRanAt(value *time.Time) {
	entity.PreconditionRanAt = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.PreconditionRanAt = true
}
func (entity *LegacyRun) GetPreconditionPassed() *int {
	return entity.PreconditionPassed
}
func (entity *LegacyRun) SetPreconditionPassed(value *int) {
	entity.PreconditionPassed = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.PreconditionPassed = true
}
func (entity *LegacyRun) GetPreconditionResult() *string {
	return entity.PreconditionResult
}
func (entity *LegacyRun) SetPreconditionResult(value *string) {
	entity.PreconditionResult = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.PreconditionResult = true
}
func (entity *LegacyRun) GetConversationId() *string {
	return entity.ConversationId
}
func (entity *LegacyRun) SetConversationId(value *string) {
	entity.ConversationId = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.ConversationId = true
}
func (entity *LegacyRun) GetScheduledFor() *time.Time {
	return entity.ScheduledFor
}
func (entity *LegacyRun) SetScheduledFor(value *time.Time) {
	entity.ScheduledFor = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.ScheduledFor = true
}
func (entity *LegacyRun) GetStartedAt() *time.Time {
	return entity.StartedAt
}
func (entity *LegacyRun) SetStartedAt(value *time.Time) {
	entity.StartedAt = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.StartedAt = true
}
func (entity *LegacyRun) GetCompletedAt() *time.Time {
	return entity.CompletedAt
}
func (entity *LegacyRun) SetCompletedAt(value *time.Time) {
	entity.CompletedAt = value
	if entity.Has == nil {
		entity.Has = &LegacyRunHas{}
	}
	entity.Has.CompletedAt = true
}
