// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
	time "time"
)

type WriterHandlerCurrentWriterSlice []*CurrentWriterView

func WriterHandlerCurrentWriterIndexByIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.Id, true
}

type WriterHandlerCurrentWriterIndexedById map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexById() (WriterHandlerCurrentWriterIndexedById, error) {
	result := make(WriterHandlerCurrentWriterIndexedById)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedById map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupById() WriterHandlerCurrentWriterGroupedById {
	result := make(WriterHandlerCurrentWriterGroupedById)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByScheduleIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.ScheduleId, true
}

type WriterHandlerCurrentWriterIndexedByScheduleId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByScheduleId() (WriterHandlerCurrentWriterIndexedByScheduleId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByScheduleId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByScheduleIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByScheduleId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByScheduleId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByScheduleId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByScheduleId() WriterHandlerCurrentWriterGroupedByScheduleId {
	result := make(WriterHandlerCurrentWriterGroupedByScheduleId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByScheduleIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByScheduleId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByStatusKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.Status, true
}

type WriterHandlerCurrentWriterIndexedByStatus map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByStatus() (WriterHandlerCurrentWriterIndexedByStatus, error) {
	result := make(WriterHandlerCurrentWriterIndexedByStatus)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStatusKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByStatus")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByStatus map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByStatus() WriterHandlerCurrentWriterGroupedByStatus {
	result := make(WriterHandlerCurrentWriterGroupedByStatus)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStatusKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByConversationKindKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.ConversationKind, true
}

type WriterHandlerCurrentWriterIndexedByConversationKind map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByConversationKind() (WriterHandlerCurrentWriterIndexedByConversationKind, error) {
	result := make(WriterHandlerCurrentWriterIndexedByConversationKind)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConversationKindKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByConversationKind")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByConversationKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByConversationKind map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByConversationKind() WriterHandlerCurrentWriterGroupedByConversationKind {
	result := make(WriterHandlerCurrentWriterGroupedByConversationKind)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConversationKindKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByConversationKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCreatedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type WriterHandlerCurrentWriterIndexedByCreatedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCreatedAt() (WriterHandlerCurrentWriterIndexedByCreatedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCreatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCreatedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCreatedAt() WriterHandlerCurrentWriterGroupedByCreatedAt {
	result := make(WriterHandlerCurrentWriterGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCreatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByUpdatedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.UpdatedAt == nil {
		return zero, false
	}
	return *value.UpdatedAt, true
}

type WriterHandlerCurrentWriterIndexedByUpdatedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByUpdatedAt() (WriterHandlerCurrentWriterIndexedByUpdatedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByUpdatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByUpdatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByUpdatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByUpdatedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByUpdatedAt() WriterHandlerCurrentWriterGroupedByUpdatedAt {
	result := make(WriterHandlerCurrentWriterGroupedByUpdatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByUpdatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByErrorMessageKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ErrorMessage == nil {
		return zero, false
	}
	return *value.ErrorMessage, true
}

type WriterHandlerCurrentWriterIndexedByErrorMessage map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByErrorMessage() (WriterHandlerCurrentWriterIndexedByErrorMessage, error) {
	result := make(WriterHandlerCurrentWriterIndexedByErrorMessage)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByErrorMessageKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByErrorMessage")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByErrorMessage) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByErrorMessage map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByErrorMessage() WriterHandlerCurrentWriterGroupedByErrorMessage {
	result := make(WriterHandlerCurrentWriterGroupedByErrorMessage)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByErrorMessageKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByErrorMessage) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByLeaseOwnerKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.LeaseOwner == nil {
		return zero, false
	}
	return *value.LeaseOwner, true
}

type WriterHandlerCurrentWriterIndexedByLeaseOwner map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByLeaseOwner() (WriterHandlerCurrentWriterIndexedByLeaseOwner, error) {
	result := make(WriterHandlerCurrentWriterIndexedByLeaseOwner)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseOwnerKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByLeaseOwner")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByLeaseOwner) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByLeaseOwner map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByLeaseOwner() WriterHandlerCurrentWriterGroupedByLeaseOwner {
	result := make(WriterHandlerCurrentWriterGroupedByLeaseOwner)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseOwnerKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByLeaseOwner) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByLeaseUntilKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.LeaseUntil == nil {
		return zero, false
	}
	return *value.LeaseUntil, true
}

type WriterHandlerCurrentWriterIndexedByLeaseUntil map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByLeaseUntil() (WriterHandlerCurrentWriterIndexedByLeaseUntil, error) {
	result := make(WriterHandlerCurrentWriterIndexedByLeaseUntil)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseUntilKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByLeaseUntil")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByLeaseUntil) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByLeaseUntil map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByLeaseUntil() WriterHandlerCurrentWriterGroupedByLeaseUntil {
	result := make(WriterHandlerCurrentWriterGroupedByLeaseUntil)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseUntilKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByLeaseUntil) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByPreconditionRanAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.PreconditionRanAt == nil {
		return zero, false
	}
	return *value.PreconditionRanAt, true
}

type WriterHandlerCurrentWriterIndexedByPreconditionRanAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByPreconditionRanAt() (WriterHandlerCurrentWriterIndexedByPreconditionRanAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByPreconditionRanAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPreconditionRanAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByPreconditionRanAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByPreconditionRanAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByPreconditionRanAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByPreconditionRanAt() WriterHandlerCurrentWriterGroupedByPreconditionRanAt {
	result := make(WriterHandlerCurrentWriterGroupedByPreconditionRanAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPreconditionRanAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByPreconditionRanAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByPreconditionPassedKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.PreconditionPassed == nil {
		return zero, false
	}
	return *value.PreconditionPassed, true
}

type WriterHandlerCurrentWriterIndexedByPreconditionPassed map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByPreconditionPassed() (WriterHandlerCurrentWriterIndexedByPreconditionPassed, error) {
	result := make(WriterHandlerCurrentWriterIndexedByPreconditionPassed)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPreconditionPassedKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByPreconditionPassed")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByPreconditionPassed) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByPreconditionPassed map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByPreconditionPassed() WriterHandlerCurrentWriterGroupedByPreconditionPassed {
	result := make(WriterHandlerCurrentWriterGroupedByPreconditionPassed)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPreconditionPassedKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByPreconditionPassed) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByPreconditionResultKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PreconditionResult == nil {
		return zero, false
	}
	return *value.PreconditionResult, true
}

type WriterHandlerCurrentWriterIndexedByPreconditionResult map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByPreconditionResult() (WriterHandlerCurrentWriterIndexedByPreconditionResult, error) {
	result := make(WriterHandlerCurrentWriterIndexedByPreconditionResult)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPreconditionResultKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByPreconditionResult")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByPreconditionResult) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByPreconditionResult map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByPreconditionResult() WriterHandlerCurrentWriterGroupedByPreconditionResult {
	result := make(WriterHandlerCurrentWriterGroupedByPreconditionResult)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPreconditionResultKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByPreconditionResult) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByConversationIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ConversationId == nil {
		return zero, false
	}
	return *value.ConversationId, true
}

type WriterHandlerCurrentWriterIndexedByConversationId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByConversationId() (WriterHandlerCurrentWriterIndexedByConversationId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByConversationId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConversationIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByConversationId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByConversationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByConversationId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByConversationId() WriterHandlerCurrentWriterGroupedByConversationId {
	result := make(WriterHandlerCurrentWriterGroupedByConversationId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConversationIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByConversationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByScheduledForKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.ScheduledFor == nil {
		return zero, false
	}
	return *value.ScheduledFor, true
}

type WriterHandlerCurrentWriterIndexedByScheduledFor map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByScheduledFor() (WriterHandlerCurrentWriterIndexedByScheduledFor, error) {
	result := make(WriterHandlerCurrentWriterIndexedByScheduledFor)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByScheduledForKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByScheduledFor")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByScheduledFor) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByScheduledFor map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByScheduledFor() WriterHandlerCurrentWriterGroupedByScheduledFor {
	result := make(WriterHandlerCurrentWriterGroupedByScheduledFor)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByScheduledForKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByScheduledFor) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByStartedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.StartedAt == nil {
		return zero, false
	}
	return *value.StartedAt, true
}

type WriterHandlerCurrentWriterIndexedByStartedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByStartedAt() (WriterHandlerCurrentWriterIndexedByStartedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByStartedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStartedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByStartedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByStartedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByStartedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByStartedAt() WriterHandlerCurrentWriterGroupedByStartedAt {
	result := make(WriterHandlerCurrentWriterGroupedByStartedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStartedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByStartedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCompletedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.CompletedAt == nil {
		return zero, false
	}
	return *value.CompletedAt, true
}

type WriterHandlerCurrentWriterIndexedByCompletedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCompletedAt() (WriterHandlerCurrentWriterIndexedByCompletedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCompletedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCompletedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCompletedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCompletedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCompletedAt() WriterHandlerCurrentWriterGroupedByCompletedAt {
	result := make(WriterHandlerCurrentWriterGroupedByCompletedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCompletedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerReadIndexes struct {
	CurrentWriter     WriterHandlerCurrentWriterSlice
	CurrentWriterById WriterHandlerCurrentWriterIndexedById
}

func BuildWriterHandlerReadIndexes(ctx context.Context, input *Input) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &WriterHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentWriter")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentWriter")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*Input)(nil)).Elem()).Accessor("CurrentWriter")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentWriterView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentWriterView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentWriterView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ScheduleId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ScheduleId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Status") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Status")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ConversationKind") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ConversationKind")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("UpdatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.UpdatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ErrorMessage") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ErrorMessage")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("LeaseOwner") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.LeaseOwner")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("LeaseUntil") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.LeaseUntil")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PreconditionRanAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.PreconditionRanAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PreconditionPassed") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.PreconditionPassed")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PreconditionResult") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.PreconditionResult")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ConversationId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ConversationId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ScheduledFor") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ScheduledFor")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("StartedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.StartedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CompletedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CompletedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentWriter = WriterHandlerCurrentWriterSlice(cloned.([]*CurrentWriterView))
		result.CurrentWriterById, err = result.CurrentWriter.IndexById()
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func (input *Input) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._writerHandlerReadIndexes = nil
	indexes, err := BuildWriterHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._writerHandlerReadIndexes = indexes
	return nil
}
func (input *Input) ReadIndexes(ctx context.Context) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._writerHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._writerHandlerReadIndexes, nil
}
