// Code generated by Datly for writer; DO NOT EDIT.

package write

func (input *Input) SetOrphanDelete(value bool) {
	if input == nil {
		return
	}
	input.OrphanDelete = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanDelete = true
}

func (input *Input) SetOrphanDetach(value bool) {
	if input == nil {
		return
	}
	input.OrphanDetach = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanDetach = true
}

func (input *Input) SetOrphanColumn(value string) {
	if input == nil {
		return
	}
	input.OrphanColumn = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanColumn = true
}

func (input *Input) SetTrusted(value bool) {
	if input == nil {
		return
	}
	input.Trusted = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Trusted = true
}

func (input *Input) SetExpectedScheduleID(value string) {
	if input == nil {
		return
	}
	input.ExpectedScheduleID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExpectedScheduleID = true
}

func (input *Input) SetRuns(value []*LegacyRun) {
	if input == nil {
		return
	}
	input.Runs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Runs = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
