// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// LegacyRun is generated canonical view metadata for writer.
type LegacyRun struct {
	ShouldDelete       bool          `json:"shouldDelete,omitempty" sqlx:"-" writer:"delete"`
	Id                 string        `sqlx:"id,primaryKey=true,required=true"`
	ScheduleId         string        `sqlx:"schedule_id,required=true,refTable=schedule,refColumn=id"`
	CreatedAt          *time.Time    `sqlx:"created_at,required=true"`
	UpdatedAt          *time.Time    `sqlx:"updated_at"`
	Status             string        `sqlx:"status,required=true"`
	ErrorMessage       *string       `sqlx:"error_message"`
	LeaseOwner         *string       `sqlx:"lease_owner"`
	LeaseUntil         *time.Time    `sqlx:"lease_until"`
	PreconditionRanAt  *time.Time    `sqlx:"precondition_ran_at"`
	PreconditionPassed *int          `sqlx:"precondition_passed"`
	PreconditionResult *string       `sqlx:"precondition_result"`
	ConversationId     *string       `sqlx:"conversation_id,refTable=conversation,refColumn=id"`
	ConversationKind   string        `sqlx:"conversation_kind,required=true"`
	ScheduledFor       *time.Time    `sqlx:"scheduled_for"`
	StartedAt          *time.Time    `sqlx:"started_at"`
	CompletedAt        *time.Time    `sqlx:"completed_at"`
	Has                *LegacyRunHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"LegacyRunHas"`
}

type LegacyRunHas struct {
	ShouldDelete       bool
	Id                 bool
	ScheduleId         bool
	CreatedAt          bool
	UpdatedAt          bool
	Status             bool
	ErrorMessage       bool
	LeaseOwner         bool
	LeaseUntil         bool
	PreconditionRanAt  bool
	PreconditionPassed bool
	PreconditionResult bool
	ConversationId     bool
	ConversationKind   bool
	ScheduledFor       bool
	StartedAt          bool
	CompletedAt        bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	Id                 string     `sqlx:"id,primaryKey=true,required=true"`
	ScheduleId         string     `sqlx:"schedule_id,required=true,refTable=schedule,refColumn=id"`
	CreatedAt          *time.Time `sqlx:"created_at,required=true"`
	UpdatedAt          *time.Time `sqlx:"updated_at"`
	Status             string     `sqlx:"status,required=true"`
	ErrorMessage       *string    `sqlx:"error_message"`
	LeaseOwner         *string    `sqlx:"lease_owner"`
	LeaseUntil         *time.Time `sqlx:"lease_until"`
	PreconditionRanAt  *time.Time `sqlx:"precondition_ran_at"`
	PreconditionPassed *int       `sqlx:"precondition_passed"`
	PreconditionResult *string    `sqlx:"precondition_result"`
	ConversationId     *string    `sqlx:"conversation_id,refTable=conversation,refColumn=id"`
	ConversationKind   string     `sqlx:"conversation_kind,required=true"`
	ScheduledFor       *time.Time `sqlx:"scheduled_for"`
	StartedAt          *time.Time `sqlx:"started_at"`
	CompletedAt        *time.Time `sqlx:"completed_at"`
}

type WriterKeysRow struct {
	Id string `sqlx:"id"`
}
