// Code generated by Datly for reader; DO NOT EDIT.

package cube

// TurnReportInput is the generated input scaffold for reader.
type TurnReportInput struct {
	Trusted        bool                `parameter:"Trusted,kind=turnaccess,in=internal,dataType=bool,required=true"`
	ConversationId string              `parameter:"ConversationId,kind=query,in=conversationId,dataType=string,required=false" predicate:"equal,t,conversation_id"`
	Statuses       []string            `parameter:"Statuses,kind=query,in=statuses,dataType=[]string,required=false" predicate:"in,t,status"`
	Origin         string              `parameter:"Origin,kind=query,in=origin,dataType=string,required=false" predicate:"equal,t,origin"`
	Fields         []string            `parameter:"Fields,kind=query,in=fields,dataType=[]string,required=false,cacheable=false" querySelector:"view=reader,property=fields"`
	Has            *TurnReportInputHas `setMarker:"true" typeName:"TurnReportInputHas" json:"-" sqlx:"-"`
}

type TurnReportInputHas struct {
	Trusted        bool
	ConversationId bool
	Statuses       bool
	Origin         bool
	Fields         bool
}
