// Code generated by Datly for reader; DO NOT EDIT.

package read

func (input *Input) SetOwner(value string) {
	if input == nil {
		return
	}
	input.Owner = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Owner = true
}

func (input *Input) SetConversationID(value string) {
	if input == nil {
		return
	}
	input.ConversationID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ConversationID = true
}

func (input *Input) SetTurnID(value string) {
	if input == nil {
		return
	}
	input.TurnID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.TurnID = true
}

func (input *Input) SetID(value string) {
	if input == nil {
		return
	}
	input.ID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ID = true
}

func (input *Input) SetRunID(value string) {
	if input == nil {
		return
	}
	input.RunID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.RunID = true
}

func (input *Input) SetSubtype(value string) {
	if input == nil {
		return
	}
	input.Subtype = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Subtype = true
}
