// Code generated by Datly for reader; DO NOT EDIT.

package read

// Document is generated canonical view metadata for reader.
type Document struct {
	InlineBody  []byte  `sqlx:"inline_body" json:"inlineBody"`
	Id          *string `sqlx:"id,primaryKey=true" json:"id"`
	RunId       *string `sqlx:"run_id,refTable=run,refColumn=id" json:"runId"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	Subtype     *string `sqlx:"subtype" json:"subtype"`
	SchemaRef   *string `sqlx:"schema_ref" json:"schemaRef"`
	MimeType    *string `sqlx:"mime_type,required=true" json:"mimeType"`
	Storage     *string `sqlx:"storage,required=true" json:"storage"`
	Compression *string `sqlx:"compression,required=true" json:"compression"`
	Digest      *string `sqlx:"digest" json:"digest"`
	SizeBytes   *int    `sqlx:"size_bytes,required=true" json:"sizeBytes"`
}
