// Code generated by Datly for reader; DO NOT EDIT.

package cube

// MessageReportInput is the generated input scaffold for reader.
type MessageReportInput struct {
	Internal          bool                   `parameter:"Internal,kind=messageaccess,in=internal,dataType=bool,required=true"`
	VisibilitySubject *string                `parameter:"VisibilitySubject,kind=visibility,in=subject,dataType=*string,required=true"`
	ConversationId    string                 `parameter:"ConversationId,kind=query,in=conversationId,dataType=string,required=false" predicate:"equal,m,conversation_id"`
	TurnId            string                 `parameter:"TurnId,kind=query,in=turnId,dataType=string,required=false" predicate:"equal,m,turn_id"`
	Roles             []string               `parameter:"Roles,kind=query,in=roles,dataType=[]string,required=false" predicate:"in,m,role"`
	Statuses          []string               `parameter:"Statuses,kind=query,in=statuses,dataType=[]string,required=false" predicate:"in,m,status"`
	Fields            []string               `parameter:"Fields,kind=query,in=fields,dataType=[]string,required=false,cacheable=false" querySelector:"view=reader,property=fields"`
	Has               *MessageReportInputHas `setMarker:"true" typeName:"MessageReportInputHas" json:"-" sqlx:"-"`
}

type MessageReportInputHas struct {
	Internal          bool
	VisibilitySubject bool
	ConversationId    bool
	TurnId            bool
	Roles             bool
	Statuses          bool
	Fields            bool
}
