// Code generated by Datly for reader; DO NOT EDIT.

package cube

// MessageReportView is generated canonical view metadata for reader.
type MessageReportView struct {
	ConversationId string  `groupable:"true" sqlx:"conversation_id,refTable=conversation,refColumn=id,required=true" docTable:"message" docColumn:"conversation_id" json:"conversationId"`
	Role           string  `groupable:"true" docTable:"message" docColumn:"role" sqlx:"role,required=true" json:"role"`
	Type           string  `groupable:"true" docTable:"message" docColumn:"type" sqlx:"type,required=true" json:"type"`
	Status         *string `groupable:"true" docTable:"message" docColumn:"status" sqlx:"status" json:"status"`
	Phase          *string `groupable:"true" docTable:"message" docColumn:"phase" sqlx:"phase" json:"phase"`
	Iteration      *int    `groupable:"true" docTable:"message" docColumn:"iteration" sqlx:"iteration" json:"iteration"`
	RecordCount    int     `groupable:"false" docTable:"-" sqlx:"record_count" json:"recordCount"`
	PendingCount   int     `groupable:"false" docTable:"-" sqlx:"pending_count" json:"pendingCount"`
	UserCount      int     `groupable:"false" docTable:"-" sqlx:"user_count" json:"userCount"`
	AssistantCount int     `groupable:"false" docTable:"-" sqlx:"assistant_count" json:"assistantCount"`
}
