// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	time "time"
)

// RunRowsView is generated canonical view metadata for reader.
type RunRowsView struct {
	LeaseUntilRaw         *string    `internal:"true" json:"-" sqlx:"lease_until_raw"`
	HeartbeatRaw          *string    `internal:"true" json:"-" sqlx:"heartbeat_raw"`
	ActivityRaw           *string    `internal:"true" json:"-" sqlx:"activity_raw"`
	MaintenanceOwnerId    string     `internal:"true" json:"-" sqlx:"maintenance_owner_id"`
	AgentId               *string    `sqlx:"agent_id"`
	Attempt               int        `sqlx:"attempt,required=true"`
	AuthAudience          *string    `sqlx:"auth_audience"`
	AuthAuthority         *string    `sqlx:"auth_authority"`
	CheckpointData        *string    `sqlx:"checkpoint_data"`
	CheckpointMessageId   *string    `sqlx:"checkpoint_message_id"`
	CheckpointResponseId  *string    `sqlx:"checkpoint_response_id"`
	CompletedAt           *time.Time `sqlx:"completed_at"`
	ConversationId        *string    `sqlx:"conversation_id,refTable=conversation,refColumn=id"`
	ConversationKind      string     `sqlx:"conversation_kind,required=true"`
	CreatedAt             time.Time  `sqlx:"created_at,required=true"`
	EffectiveUserId       *string    `sqlx:"effective_user_id"`
	ErrorCode             *string    `sqlx:"error_code"`
	ErrorMessage          *string    `sqlx:"error_message"`
	HeartbeatIntervalSec  *int       `sqlx:"heartbeat_interval_sec"`
	Id                    string     `sqlx:"id,primaryKey=true"`
	Iteration             int        `sqlx:"iteration,required=true"`
	LastHeartbeatAt       *time.Time `sqlx:"last_heartbeat_at"`
	LeaseOwner            *string    `sqlx:"lease_owner"`
	LeaseUntil            *time.Time `sqlx:"lease_until"`
	MaxIterations         *int       `sqlx:"max_iterations"`
	Model                 *string    `sqlx:"model"`
	ModelProvider         *string    `sqlx:"model_provider"`
	PreconditionPassed    *int       `sqlx:"precondition_passed"`
	PreconditionRanAt     *time.Time `sqlx:"precondition_ran_at"`
	PreconditionResult    *string    `sqlx:"precondition_result"`
	ResumedFromRunId      *string    `sqlx:"resumed_from_run_id"`
	ScheduleId            *string    `sqlx:"schedule_id,refTable=schedule,refColumn=id"`
	ScheduledFor          *time.Time `sqlx:"scheduled_for"`
	SecurityContext       *string    `sqlx:"security_context"`
	StartedAt             *time.Time `sqlx:"started_at"`
	Status                string     `sqlx:"status,required=true"`
	TurnId                *string    `sqlx:"turn_id,refTable=turn,refColumn=id"`
	UpdatedAt             *time.Time `sqlx:"updated_at"`
	UsageCompletionTokens *int       `sqlx:"usage_completion_tokens"`
	UsageCost             *float64   `sqlx:"usage_cost"`
	UsagePromptTokens     *int       `sqlx:"usage_prompt_tokens"`
	UsageTotalTokens      *int       `sqlx:"usage_total_tokens"`
	UserCredUrl           *string    `sqlx:"user_cred_url"`
	WorkerHost            *string    `sqlx:"worker_host"`
	WorkerId              *string    `sqlx:"worker_id"`
	WorkerPid             *int       `sqlx:"worker_pid"`
}
