// Code generated by Datly for writer; DO NOT EDIT.

package write

// Output is the generated output scaffold for writer.
type Output struct {
	Data []*TurnQueue `parameter:"Data,kind=output,in=body,dataType=[]*TurnQueue"`
}
