package window

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/viant/afs"
	dsproto "github.com/viant/agently-core/protocol/datasource"
	identity "github.com/viant/agently-core/protocol/resource"
	wsmeta "github.com/viant/agently-core/workspace/service/meta"
	forgeTypes "github.com/viant/forge/backend/types"
)

// ResourceBinding assigns a logical namespace/name to a local workspace window.
// File keys and provider transport aliases never become URI authorities.
type ResourceBinding struct {
	CatalogID string                    `json:"catalogId,omitempty"`
	WindowKey string                    `json:"windowKey"`
	URI       string                    `json:"uri"`
	Targets   []forgeTypes.WindowTarget `json:"targets,omitempty"`
}

type WorkspaceResourceSource struct {
	root    string
	windows map[string]string
	uris    map[string]string
	enrich  WorkspaceWindowEnricher
	legacy  bool
	targets map[string][]forgeTypes.WindowTarget
}

// NewLegacyWorkspaceResourceSource retains exact singleton bytes exclusively
// for importing/comparing pre-bundle working drafts; it supplies no variants.
func NewLegacyWorkspaceResourceSource(root string, bindings []ResourceBinding, enrich WorkspaceWindowEnricher) (*WorkspaceResourceSource, error) {
	source, err := NewWorkspaceResourceSource(root, bindings, enrich)
	if err == nil {
		source.legacy = true
	}
	return source, err
}

func NewWorkspaceResourceSource(root string, bindings []ResourceBinding, enrich WorkspaceWindowEnricher) (*WorkspaceResourceSource, error) {
	if strings.TrimSpace(root) == "" {
		return nil, fmt.Errorf("workspace root required")
	}
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	result := &WorkspaceResourceSource{root: absolute, windows: map[string]string{}, uris: map[string]string{}, enrich: enrich, targets: map[string][]forgeTypes.WindowTarget{}}
	for _, binding := range bindings {
		uri, err := identity.ParseResourceURI(binding.URI)
		if err != nil || uri.Kind != "window" || !validBoundWindowPath(binding.WindowKey) {
			return nil, fmt.Errorf("invalid workspace resource binding")
		}
		if result.windows[binding.URI] != "" || result.uris[binding.WindowKey] != "" {
			return nil, fmt.Errorf("duplicate workspace resource binding")
		}
		result.windows[binding.URI] = binding.WindowKey
		for _, target := range binding.Targets {
			normalized, e := target.Normalize()
			if e != nil || len(normalized.Capabilities) > 0 || normalized.SelectionToken != "" || len(normalized.DependencyPins) > 0 {
				return nil, fmt.Errorf("invalid declared window target")
			}
			result.targets[binding.URI] = append(result.targets[binding.URI], normalized)
		}
		result.uris[binding.WindowKey] = binding.URI
		if binding.CatalogID != "" && binding.CatalogID != binding.WindowKey {
			if strings.TrimSpace(binding.CatalogID) != binding.CatalogID || result.uris[binding.CatalogID] != "" {
				return nil, fmt.Errorf("duplicate or invalid catalog identity")
			}
			result.uris[binding.CatalogID] = binding.URI
		}
	}
	return result, nil
}
func validBoundWindowPath(value string) bool {
	if value == "" || len(value) > 512 || strings.TrimSpace(value) != value || strings.ContainsAny(value, "\\:\x00?#%") {
		return false
	}
	for _, segment := range strings.Split(value, "/") {
		if segment == "" || segment == "." || segment == ".." || len(segment) > 64 {
			return false
		}
	}
	return true
}

func (s *WorkspaceResourceSource) Reference(key string) (identity.ResourceRef, error) {
	if s == nil {
		return identity.ResourceRef{}, identity.ErrResourceDenied
	}
	if s.windows[key] != "" {
		return identity.ResourceRef{URI: key}, nil
	}
	if uri := s.uris[key]; uri != "" {
		return identity.ResourceRef{URI: uri}, nil
	}
	return identity.ResourceRef{}, identity.ErrResourceDenied
}

func (s *WorkspaceResourceSource) load(ctx context.Context, uri identity.ResourceURI) (json.RawMessage, error) {
	if !s.legacy {
		return s.loadBundle(ctx, uri)
	}
	return s.loadLegacy(ctx, uri)
}
func (s *WorkspaceResourceSource) loadLegacy(ctx context.Context, uri identity.ResourceURI) (json.RawMessage, error) {
	if s == nil || ctx == nil || ctx.Err() != nil || !uri.Valid() {
		return nil, identity.ErrResourceDenied
	}
	key := s.windows[uri.String()]
	if key == "" {
		return nil, identity.ErrResourceDenied
	}
	window, err := LoadWorkspaceWindowWithEnricherAt(ctx, s.root, key, nil, s.enrich)
	if err != nil {
		return nil, err
	}
	if window == nil {
		return nil, identity.ErrResourceDenied
	}
	// Resolution metadata is generated by the trusted resolver, not file content.
	window.Resource = nil
	window.ResourceDependencies = nil
	svc := wsmeta.New(afs.New(), s.root)
	_, paths, err := loadWorkspaceDataSources(ctx, svc)
	if err != nil {
		return nil, err
	}
	for id := range window.DataSource {
		path := paths[id]
		if path == "" {
			continue
		} // Inline/host-owned sources are already in window bytes.
		var descriptor dsproto.DataSource
		if err := svc.Load(ctx, path, &descriptor); err != nil {
			return nil, err
		}
		if descriptor.ID == "" {
			descriptor.ID = id
		}
		raw, err := json.Marshal(descriptor)
		if err != nil {
			return nil, err
		}
		if window.ResourceDependencies == nil {
			window.ResourceDependencies = map[string]string{}
		}
		window.ResourceDependencies[id] = identity.ContentFingerprint(raw)
	}
	return json.Marshal(window)
}
func (s *WorkspaceResourceSource) Candidates(ctx context.Context, uri identity.ResourceURI) ([]identity.ResourceCandidate, error) {
	raw, err := s.load(ctx, uri)
	if err != nil {
		return nil, err
	}
	return []identity.ResourceCandidate{{Kind: identity.WorkingCandidate, ContentFingerprint: identity.ContentFingerprint(raw)}}, nil
}
func (s *WorkspaceResourceSource) ReadCandidate(ctx context.Context, uri identity.ResourceURI, c identity.ResourceCandidate) (json.RawMessage, error) {
	if c.Kind != identity.WorkingCandidate || !c.Valid() {
		return nil, identity.ErrResourceDenied
	}
	return s.load(ctx, uri)
}

// LoadWorkspaceDatasourceDescriptorsAt materializes the complete declarative
// dependencies of a trusted builder window. It performs no datasource calls and
// never inserts credentials; backend identity is carried by execution context.
// Report envelopes pin these same descriptors before compilation/execution.
func LoadWorkspaceDatasourceDescriptorsAt(ctx context.Context, root, key string, enrich WorkspaceWindowEnricher) (map[string]json.RawMessage, error) {
	return LoadWorkspaceDatasourceDescriptorsWithOptionsAt(ctx, root, key, enrich, LoaderOptions{})
}

// LoadWorkspaceDatasourceDescriptorsWithOptionsAt preserves native descriptor/import
// semantics through a host-owned confined filesystem.
func LoadWorkspaceDatasourceDescriptorsWithOptionsAt(ctx context.Context, root, key string, enrich WorkspaceWindowEnricher, options LoaderOptions) (result map[string]json.RawMessage, failure error) {
	defer func() {
		if err := options.check(); err != nil {
			result = nil
			failure = err
		}
	}()
	window, err := LoadWorkspaceWindowWithOptionsAt(ctx, root, key, nil, enrich, options)
	if err != nil {
		return nil, err
	}
	if window == nil {
		return nil, identity.ErrResourceDenied
	}
	svc := wsmeta.New(options.filesystem(), root)
	_, paths, err := loadWorkspaceDataSources(ctx, svc)
	if err != nil {
		return nil, err
	}
	result = make(map[string]json.RawMessage, len(window.DataSource))
	for id, inline := range window.DataSource {
		descriptor := dsproto.DataSource{DataSource: inline, ID: id}
		if path := paths[id]; path != "" {
			descriptor = dsproto.DataSource{}
			if err := svc.Load(ctx, path, &descriptor); err != nil {
				return nil, err
			}
			if descriptor.ID == "" {
				descriptor.ID = id
			}
			descriptor.DataSource = inline
		}
		raw, err := json.Marshal(descriptor)
		if err != nil {
			return nil, err
		}
		result[id] = raw
	}
	return result, nil
}
