// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
	time "time"
)

type WriterHandlerCurrentWriterSlice []*CurrentWriterView

func WriterHandlerCurrentWriterIndexByIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.Id, true
}

type WriterHandlerCurrentWriterIndexedById map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexById() (WriterHandlerCurrentWriterIndexedById, error) {
	result := make(WriterHandlerCurrentWriterIndexedById)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedById map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupById() WriterHandlerCurrentWriterGroupedById {
	result := make(WriterHandlerCurrentWriterGroupedById)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByConversationIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ConversationId == nil {
		return zero, false
	}
	return *value.ConversationId, true
}

type WriterHandlerCurrentWriterIndexedByConversationId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByConversationId() (WriterHandlerCurrentWriterIndexedByConversationId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByConversationId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConversationIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByConversationId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByConversationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByConversationId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByConversationId() WriterHandlerCurrentWriterGroupedByConversationId {
	result := make(WriterHandlerCurrentWriterGroupedByConversationId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConversationIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByConversationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByObjectiveKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Objective == nil {
		return zero, false
	}
	return *value.Objective, true
}

type WriterHandlerCurrentWriterIndexedByObjective map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByObjective() (WriterHandlerCurrentWriterIndexedByObjective, error) {
	result := make(WriterHandlerCurrentWriterIndexedByObjective)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByObjectiveKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByObjective")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByObjective) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByObjective map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByObjective() WriterHandlerCurrentWriterGroupedByObjective {
	result := make(WriterHandlerCurrentWriterGroupedByObjective)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByObjectiveKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByObjective) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByStatusKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Status == nil {
		return zero, false
	}
	return *value.Status, true
}

type WriterHandlerCurrentWriterIndexedByStatus map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByStatus() (WriterHandlerCurrentWriterIndexedByStatus, error) {
	result := make(WriterHandlerCurrentWriterIndexedByStatus)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStatusKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByStatus")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByStatus map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByStatus() WriterHandlerCurrentWriterGroupedByStatus {
	result := make(WriterHandlerCurrentWriterGroupedByStatus)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStatusKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByStatusReasonKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.StatusReason == nil {
		return zero, false
	}
	return *value.StatusReason, true
}

type WriterHandlerCurrentWriterIndexedByStatusReason map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByStatusReason() (WriterHandlerCurrentWriterIndexedByStatusReason, error) {
	result := make(WriterHandlerCurrentWriterIndexedByStatusReason)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStatusReasonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByStatusReason")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByStatusReason) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByStatusReason map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByStatusReason() WriterHandlerCurrentWriterGroupedByStatusReason {
	result := make(WriterHandlerCurrentWriterGroupedByStatusReason)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStatusReasonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByStatusReason) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByPauseReasonKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PauseReason == nil {
		return zero, false
	}
	return *value.PauseReason, true
}

type WriterHandlerCurrentWriterIndexedByPauseReason map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByPauseReason() (WriterHandlerCurrentWriterIndexedByPauseReason, error) {
	result := make(WriterHandlerCurrentWriterIndexedByPauseReason)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPauseReasonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByPauseReason")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByPauseReason) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByPauseReason map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByPauseReason() WriterHandlerCurrentWriterGroupedByPauseReason {
	result := make(WriterHandlerCurrentWriterGroupedByPauseReason)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPauseReasonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByPauseReason) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByControllerSpecKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ControllerSpec == nil {
		return zero, false
	}
	return *value.ControllerSpec, true
}

type WriterHandlerCurrentWriterIndexedByControllerSpec map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByControllerSpec() (WriterHandlerCurrentWriterIndexedByControllerSpec, error) {
	result := make(WriterHandlerCurrentWriterIndexedByControllerSpec)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByControllerSpecKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByControllerSpec")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByControllerSpec) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByControllerSpec map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByControllerSpec() WriterHandlerCurrentWriterGroupedByControllerSpec {
	result := make(WriterHandlerCurrentWriterGroupedByControllerSpec)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByControllerSpecKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByControllerSpec) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByTokenBudgetKey(value *CurrentWriterView) (int64, bool) {
	var zero int64
	if value == nil {
		return zero, false
	}
	if value.TokenBudget == nil {
		return zero, false
	}
	return *value.TokenBudget, true
}

type WriterHandlerCurrentWriterIndexedByTokenBudget map[int64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByTokenBudget() (WriterHandlerCurrentWriterIndexedByTokenBudget, error) {
	result := make(WriterHandlerCurrentWriterIndexedByTokenBudget)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTokenBudgetKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByTokenBudget")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByTokenBudget) Has(key int64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByTokenBudget map[int64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByTokenBudget() WriterHandlerCurrentWriterGroupedByTokenBudget {
	result := make(WriterHandlerCurrentWriterGroupedByTokenBudget)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTokenBudgetKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByTokenBudget) Has(key int64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByTokensUsedKey(value *CurrentWriterView) (int64, bool) {
	var zero int64
	if value == nil {
		return zero, false
	}
	if value.TokensUsed == nil {
		return zero, false
	}
	return *value.TokensUsed, true
}

type WriterHandlerCurrentWriterIndexedByTokensUsed map[int64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByTokensUsed() (WriterHandlerCurrentWriterIndexedByTokensUsed, error) {
	result := make(WriterHandlerCurrentWriterIndexedByTokensUsed)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTokensUsedKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByTokensUsed")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByTokensUsed) Has(key int64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByTokensUsed map[int64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByTokensUsed() WriterHandlerCurrentWriterGroupedByTokensUsed {
	result := make(WriterHandlerCurrentWriterGroupedByTokensUsed)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTokensUsedKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByTokensUsed) Has(key int64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByTimeUsedSecondsKey(value *CurrentWriterView) (int64, bool) {
	var zero int64
	if value == nil {
		return zero, false
	}
	if value.TimeUsedSeconds == nil {
		return zero, false
	}
	return *value.TimeUsedSeconds, true
}

type WriterHandlerCurrentWriterIndexedByTimeUsedSeconds map[int64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByTimeUsedSeconds() (WriterHandlerCurrentWriterIndexedByTimeUsedSeconds, error) {
	result := make(WriterHandlerCurrentWriterIndexedByTimeUsedSeconds)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTimeUsedSecondsKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByTimeUsedSeconds")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByTimeUsedSeconds) Has(key int64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByTimeUsedSeconds map[int64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByTimeUsedSeconds() WriterHandlerCurrentWriterGroupedByTimeUsedSeconds {
	result := make(WriterHandlerCurrentWriterGroupedByTimeUsedSeconds)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTimeUsedSecondsKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByTimeUsedSeconds) Has(key int64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByAutonomousTurnsUsedKey(value *CurrentWriterView) (int64, bool) {
	var zero int64
	if value == nil {
		return zero, false
	}
	if value.AutonomousTurnsUsed == nil {
		return zero, false
	}
	return *value.AutonomousTurnsUsed, true
}

type WriterHandlerCurrentWriterIndexedByAutonomousTurnsUsed map[int64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByAutonomousTurnsUsed() (WriterHandlerCurrentWriterIndexedByAutonomousTurnsUsed, error) {
	result := make(WriterHandlerCurrentWriterIndexedByAutonomousTurnsUsed)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByAutonomousTurnsUsedKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByAutonomousTurnsUsed")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByAutonomousTurnsUsed) Has(key int64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByAutonomousTurnsUsed map[int64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByAutonomousTurnsUsed() WriterHandlerCurrentWriterGroupedByAutonomousTurnsUsed {
	result := make(WriterHandlerCurrentWriterGroupedByAutonomousTurnsUsed)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByAutonomousTurnsUsedKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByAutonomousTurnsUsed) Has(key int64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByConsecutiveNoProgressKey(value *CurrentWriterView) (int64, bool) {
	var zero int64
	if value == nil {
		return zero, false
	}
	if value.ConsecutiveNoProgress == nil {
		return zero, false
	}
	return *value.ConsecutiveNoProgress, true
}

type WriterHandlerCurrentWriterIndexedByConsecutiveNoProgress map[int64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByConsecutiveNoProgress() (WriterHandlerCurrentWriterIndexedByConsecutiveNoProgress, error) {
	result := make(WriterHandlerCurrentWriterIndexedByConsecutiveNoProgress)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConsecutiveNoProgressKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByConsecutiveNoProgress")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByConsecutiveNoProgress) Has(key int64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByConsecutiveNoProgress map[int64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByConsecutiveNoProgress() WriterHandlerCurrentWriterGroupedByConsecutiveNoProgress {
	result := make(WriterHandlerCurrentWriterGroupedByConsecutiveNoProgress)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByConsecutiveNoProgressKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByConsecutiveNoProgress) Has(key int64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByLastContinuationFingerprintKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.LastContinuationFingerprint == nil {
		return zero, false
	}
	return *value.LastContinuationFingerprint, true
}

type WriterHandlerCurrentWriterIndexedByLastContinuationFingerprint map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByLastContinuationFingerprint() (WriterHandlerCurrentWriterIndexedByLastContinuationFingerprint, error) {
	result := make(WriterHandlerCurrentWriterIndexedByLastContinuationFingerprint)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLastContinuationFingerprintKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByLastContinuationFingerprint")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByLastContinuationFingerprint) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByLastContinuationFingerprint map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByLastContinuationFingerprint() WriterHandlerCurrentWriterGroupedByLastContinuationFingerprint {
	result := make(WriterHandlerCurrentWriterGroupedByLastContinuationFingerprint)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLastContinuationFingerprintKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByLastContinuationFingerprint) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCreatedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type WriterHandlerCurrentWriterIndexedByCreatedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCreatedAt() (WriterHandlerCurrentWriterIndexedByCreatedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCreatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCreatedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCreatedAt() WriterHandlerCurrentWriterGroupedByCreatedAt {
	result := make(WriterHandlerCurrentWriterGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCreatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByUpdatedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.UpdatedAt == nil {
		return zero, false
	}
	return *value.UpdatedAt, true
}

type WriterHandlerCurrentWriterIndexedByUpdatedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByUpdatedAt() (WriterHandlerCurrentWriterIndexedByUpdatedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByUpdatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByUpdatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByUpdatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByUpdatedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByUpdatedAt() WriterHandlerCurrentWriterGroupedByUpdatedAt {
	result := make(WriterHandlerCurrentWriterGroupedByUpdatedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByUpdatedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerReadIndexes struct {
	CurrentWriter     WriterHandlerCurrentWriterSlice
	CurrentWriterById WriterHandlerCurrentWriterIndexedById
}

func BuildWriterHandlerReadIndexes(ctx context.Context, input *Input) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &WriterHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentWriter")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentWriter")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*Input)(nil)).Elem()).Accessor("CurrentWriter")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentWriterView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentWriterView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentWriterView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ConversationId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ConversationId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Objective") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Objective")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Status") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Status")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("StatusReason") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.StatusReason")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PauseReason") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.PauseReason")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ControllerSpec") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ControllerSpec")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("TokenBudget") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.TokenBudget")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("TokensUsed") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.TokensUsed")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("TimeUsedSeconds") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.TimeUsedSeconds")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("AutonomousTurnsUsed") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.AutonomousTurnsUsed")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ConsecutiveNoProgress") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ConsecutiveNoProgress")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("LastContinuationFingerprint") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.LastContinuationFingerprint")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("UpdatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.UpdatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentWriter = WriterHandlerCurrentWriterSlice(cloned.([]*CurrentWriterView))
		result.CurrentWriterById, err = result.CurrentWriter.IndexById()
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func (input *Input) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._writerHandlerReadIndexes = nil
	indexes, err := BuildWriterHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._writerHandlerReadIndexes = indexes
	return nil
}
func (input *Input) ReadIndexes(ctx context.Context) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._writerHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._writerHandlerReadIndexes, nil
}
