// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// Goal is generated canonical view metadata for writer.
type Goal struct {
	ShouldDelete                bool       `json:",omitempty" sqlx:"-" writer:"delete"`
	Id                          string     `validate:"required" sqlx:"id,primaryKey"`
	ConversationId              *string    `json:",omitempty" sqlx:"conversation_id,refTable=conversation,refColumn=id,required=true"`
	Objective                   *string    `json:",omitempty" sqlx:"objective,required=true"`
	Status                      *string    `json:",omitempty" sqlx:"status,required=true"`
	StatusReason                *string    `json:",omitempty" sqlx:"status_reason"`
	PauseReason                 *string    `json:",omitempty" sqlx:"pause_reason"`
	ControllerSpec              *string    `json:",omitempty" sqlx:"controller_spec"`
	TokenBudget                 *int64     `json:",omitempty" sqlx:"token_budget"`
	TokensUsed                  *int64     `json:",omitempty" sqlx:"tokens_used,required=true"`
	TimeUsedSeconds             *int64     `json:",omitempty" sqlx:"time_used_seconds,required=true"`
	AutonomousTurnsUsed         *int64     `json:",omitempty" sqlx:"autonomous_turns_used,required=true"`
	ConsecutiveNoProgress       *int64     `json:",omitempty" sqlx:"consecutive_no_progress,required=true"`
	LastContinuationFingerprint *string    `json:",omitempty" sqlx:"last_continuation_fingerprint"`
	CreatedAt                   *time.Time `json:",omitempty" sqlx:"created_at,required=true"`
	UpdatedAt                   *time.Time `json:",omitempty" sqlx:"updated_at"`
	Has                         *GoalHas   `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"GoalHas"`
}

type GoalHas struct {
	ShouldDelete                bool
	Id                          bool
	ConversationId              bool
	Objective                   bool
	Status                      bool
	StatusReason                bool
	PauseReason                 bool
	ControllerSpec              bool
	TokenBudget                 bool
	TokensUsed                  bool
	TimeUsedSeconds             bool
	AutonomousTurnsUsed         bool
	ConsecutiveNoProgress       bool
	LastContinuationFingerprint bool
	CreatedAt                   bool
	UpdatedAt                   bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	Id                          string     `validate:"required" sqlx:"id,primaryKey"`
	ConversationId              *string    `json:",omitempty" sqlx:"conversation_id,refTable=conversation,refColumn=id,required=true"`
	Objective                   *string    `json:",omitempty" sqlx:"objective,required=true"`
	Status                      *string    `json:",omitempty" sqlx:"status,required=true"`
	StatusReason                *string    `json:",omitempty" sqlx:"status_reason"`
	PauseReason                 *string    `json:",omitempty" sqlx:"pause_reason"`
	ControllerSpec              *string    `json:",omitempty" sqlx:"controller_spec"`
	TokenBudget                 *int64     `json:",omitempty" sqlx:"token_budget"`
	TokensUsed                  *int64     `json:",omitempty" sqlx:"tokens_used,required=true"`
	TimeUsedSeconds             *int64     `json:",omitempty" sqlx:"time_used_seconds,required=true"`
	AutonomousTurnsUsed         *int64     `json:",omitempty" sqlx:"autonomous_turns_used,required=true"`
	ConsecutiveNoProgress       *int64     `json:",omitempty" sqlx:"consecutive_no_progress,required=true"`
	LastContinuationFingerprint *string    `json:",omitempty" sqlx:"last_continuation_fingerprint"`
	CreatedAt                   *time.Time `json:",omitempty" sqlx:"created_at,required=true"`
	UpdatedAt                   *time.Time `json:",omitempty" sqlx:"updated_at"`
}

type WriterKeysRow struct {
	Id string `sqlx:"id"`
}
