// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
	time "time"
)

type WriterHandlerCurrentWriterSlice []*CurrentWriterView

func WriterHandlerCurrentWriterIndexByMessageIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.MessageId, true
}

type WriterHandlerCurrentWriterIndexedByMessageId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByMessageId() (WriterHandlerCurrentWriterIndexedByMessageId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByMessageId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByMessageIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByMessageId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByMessageId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByMessageId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByMessageId() WriterHandlerCurrentWriterGroupedByMessageId {
	result := make(WriterHandlerCurrentWriterGroupedByMessageId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByMessageIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByMessageId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByProviderKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.Provider, true
}

type WriterHandlerCurrentWriterIndexedByProvider map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByProvider() (WriterHandlerCurrentWriterIndexedByProvider, error) {
	result := make(WriterHandlerCurrentWriterIndexedByProvider)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByProviderKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByProvider")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByProvider) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByProvider map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByProvider() WriterHandlerCurrentWriterGroupedByProvider {
	result := make(WriterHandlerCurrentWriterGroupedByProvider)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByProviderKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByProvider) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByModelKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.Model, true
}

type WriterHandlerCurrentWriterIndexedByModel map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByModel() (WriterHandlerCurrentWriterIndexedByModel, error) {
	result := make(WriterHandlerCurrentWriterIndexedByModel)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByModelKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByModel")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByModel) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByModel map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByModel() WriterHandlerCurrentWriterGroupedByModel {
	result := make(WriterHandlerCurrentWriterGroupedByModel)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByModelKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByModel) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByModelKindKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.ModelKind, true
}

type WriterHandlerCurrentWriterIndexedByModelKind map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByModelKind() (WriterHandlerCurrentWriterIndexedByModelKind, error) {
	result := make(WriterHandlerCurrentWriterIndexedByModelKind)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByModelKindKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByModelKind")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByModelKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByModelKind map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByModelKind() WriterHandlerCurrentWriterGroupedByModelKind {
	result := make(WriterHandlerCurrentWriterGroupedByModelKind)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByModelKindKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByModelKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByStatusKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	return value.Status, true
}

type WriterHandlerCurrentWriterIndexedByStatus map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByStatus() (WriterHandlerCurrentWriterIndexedByStatus, error) {
	result := make(WriterHandlerCurrentWriterIndexedByStatus)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStatusKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByStatus")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByStatus map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByStatus() WriterHandlerCurrentWriterGroupedByStatus {
	result := make(WriterHandlerCurrentWriterGroupedByStatus)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStatusKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCostKey(value *CurrentWriterView) (float64, bool) {
	var zero float64
	if value == nil {
		return zero, false
	}
	if value.Cost == nil {
		return zero, false
	}
	return *value.Cost, true
}

type WriterHandlerCurrentWriterIndexedByCost map[float64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCost() (WriterHandlerCurrentWriterIndexedByCost, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCost)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCostKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCost")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCost) Has(key float64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCost map[float64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCost() WriterHandlerCurrentWriterGroupedByCost {
	result := make(WriterHandlerCurrentWriterGroupedByCost)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCostKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCost) Has(key float64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByTurnIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.TurnId == nil {
		return zero, false
	}
	return *value.TurnId, true
}

type WriterHandlerCurrentWriterIndexedByTurnId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByTurnId() (WriterHandlerCurrentWriterIndexedByTurnId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByTurnId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTurnIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByTurnId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByTurnId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByTurnId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByTurnId() WriterHandlerCurrentWriterGroupedByTurnId {
	result := make(WriterHandlerCurrentWriterGroupedByTurnId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTurnIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByTurnId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByErrorCodeKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ErrorCode == nil {
		return zero, false
	}
	return *value.ErrorCode, true
}

type WriterHandlerCurrentWriterIndexedByErrorCode map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByErrorCode() (WriterHandlerCurrentWriterIndexedByErrorCode, error) {
	result := make(WriterHandlerCurrentWriterIndexedByErrorCode)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByErrorCodeKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByErrorCode")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByErrorCode) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByErrorCode map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByErrorCode() WriterHandlerCurrentWriterGroupedByErrorCode {
	result := make(WriterHandlerCurrentWriterGroupedByErrorCode)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByErrorCodeKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByErrorCode) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByErrorMessageKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ErrorMessage == nil {
		return zero, false
	}
	return *value.ErrorMessage, true
}

type WriterHandlerCurrentWriterIndexedByErrorMessage map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByErrorMessage() (WriterHandlerCurrentWriterIndexedByErrorMessage, error) {
	result := make(WriterHandlerCurrentWriterIndexedByErrorMessage)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByErrorMessageKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByErrorMessage")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByErrorMessage) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByErrorMessage map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByErrorMessage() WriterHandlerCurrentWriterGroupedByErrorMessage {
	result := make(WriterHandlerCurrentWriterGroupedByErrorMessage)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByErrorMessageKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByErrorMessage) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByFinishReasonKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.FinishReason == nil {
		return zero, false
	}
	return *value.FinishReason, true
}

type WriterHandlerCurrentWriterIndexedByFinishReason map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByFinishReason() (WriterHandlerCurrentWriterIndexedByFinishReason, error) {
	result := make(WriterHandlerCurrentWriterIndexedByFinishReason)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByFinishReasonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByFinishReason")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByFinishReason) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByFinishReason map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByFinishReason() WriterHandlerCurrentWriterGroupedByFinishReason {
	result := make(WriterHandlerCurrentWriterGroupedByFinishReason)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByFinishReasonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByFinishReason) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByPromptTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.PromptTokens == nil {
		return zero, false
	}
	return *value.PromptTokens, true
}

type WriterHandlerCurrentWriterIndexedByPromptTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByPromptTokens() (WriterHandlerCurrentWriterIndexedByPromptTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByPromptTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPromptTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByPromptTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByPromptTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByPromptTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByPromptTokens() WriterHandlerCurrentWriterGroupedByPromptTokens {
	result := make(WriterHandlerCurrentWriterGroupedByPromptTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPromptTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByPromptTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByPromptCachedTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.PromptCachedTokens == nil {
		return zero, false
	}
	return *value.PromptCachedTokens, true
}

type WriterHandlerCurrentWriterIndexedByPromptCachedTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByPromptCachedTokens() (WriterHandlerCurrentWriterIndexedByPromptCachedTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByPromptCachedTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPromptCachedTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByPromptCachedTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByPromptCachedTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByPromptCachedTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByPromptCachedTokens() WriterHandlerCurrentWriterGroupedByPromptCachedTokens {
	result := make(WriterHandlerCurrentWriterGroupedByPromptCachedTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPromptCachedTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByPromptCachedTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCompletionTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.CompletionTokens == nil {
		return zero, false
	}
	return *value.CompletionTokens, true
}

type WriterHandlerCurrentWriterIndexedByCompletionTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCompletionTokens() (WriterHandlerCurrentWriterIndexedByCompletionTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCompletionTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCompletionTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCompletionTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCompletionTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCompletionTokens() WriterHandlerCurrentWriterGroupedByCompletionTokens {
	result := make(WriterHandlerCurrentWriterGroupedByCompletionTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCompletionTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByTotalTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.TotalTokens == nil {
		return zero, false
	}
	return *value.TotalTokens, true
}

type WriterHandlerCurrentWriterIndexedByTotalTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByTotalTokens() (WriterHandlerCurrentWriterIndexedByTotalTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByTotalTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTotalTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByTotalTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByTotalTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByTotalTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByTotalTokens() WriterHandlerCurrentWriterGroupedByTotalTokens {
	result := make(WriterHandlerCurrentWriterGroupedByTotalTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTotalTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByTotalTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByPromptAudioTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.PromptAudioTokens == nil {
		return zero, false
	}
	return *value.PromptAudioTokens, true
}

type WriterHandlerCurrentWriterIndexedByPromptAudioTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByPromptAudioTokens() (WriterHandlerCurrentWriterIndexedByPromptAudioTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByPromptAudioTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPromptAudioTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByPromptAudioTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByPromptAudioTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByPromptAudioTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByPromptAudioTokens() WriterHandlerCurrentWriterGroupedByPromptAudioTokens {
	result := make(WriterHandlerCurrentWriterGroupedByPromptAudioTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPromptAudioTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByPromptAudioTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCompletionReasoningTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.CompletionReasoningTokens == nil {
		return zero, false
	}
	return *value.CompletionReasoningTokens, true
}

type WriterHandlerCurrentWriterIndexedByCompletionReasoningTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCompletionReasoningTokens() (WriterHandlerCurrentWriterIndexedByCompletionReasoningTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCompletionReasoningTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionReasoningTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCompletionReasoningTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCompletionReasoningTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCompletionReasoningTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCompletionReasoningTokens() WriterHandlerCurrentWriterGroupedByCompletionReasoningTokens {
	result := make(WriterHandlerCurrentWriterGroupedByCompletionReasoningTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionReasoningTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCompletionReasoningTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCompletionAudioTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.CompletionAudioTokens == nil {
		return zero, false
	}
	return *value.CompletionAudioTokens, true
}

type WriterHandlerCurrentWriterIndexedByCompletionAudioTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCompletionAudioTokens() (WriterHandlerCurrentWriterIndexedByCompletionAudioTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCompletionAudioTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionAudioTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCompletionAudioTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCompletionAudioTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCompletionAudioTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCompletionAudioTokens() WriterHandlerCurrentWriterGroupedByCompletionAudioTokens {
	result := make(WriterHandlerCurrentWriterGroupedByCompletionAudioTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionAudioTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCompletionAudioTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCompletionAcceptedPredictionTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.CompletionAcceptedPredictionTokens == nil {
		return zero, false
	}
	return *value.CompletionAcceptedPredictionTokens, true
}

type WriterHandlerCurrentWriterIndexedByCompletionAcceptedPredictionTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCompletionAcceptedPredictionTokens() (WriterHandlerCurrentWriterIndexedByCompletionAcceptedPredictionTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCompletionAcceptedPredictionTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionAcceptedPredictionTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCompletionAcceptedPredictionTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCompletionAcceptedPredictionTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCompletionAcceptedPredictionTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCompletionAcceptedPredictionTokens() WriterHandlerCurrentWriterGroupedByCompletionAcceptedPredictionTokens {
	result := make(WriterHandlerCurrentWriterGroupedByCompletionAcceptedPredictionTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionAcceptedPredictionTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCompletionAcceptedPredictionTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCompletionRejectedPredictionTokensKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.CompletionRejectedPredictionTokens == nil {
		return zero, false
	}
	return *value.CompletionRejectedPredictionTokens, true
}

type WriterHandlerCurrentWriterIndexedByCompletionRejectedPredictionTokens map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCompletionRejectedPredictionTokens() (WriterHandlerCurrentWriterIndexedByCompletionRejectedPredictionTokens, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCompletionRejectedPredictionTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionRejectedPredictionTokensKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCompletionRejectedPredictionTokens")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCompletionRejectedPredictionTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCompletionRejectedPredictionTokens map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCompletionRejectedPredictionTokens() WriterHandlerCurrentWriterGroupedByCompletionRejectedPredictionTokens {
	result := make(WriterHandlerCurrentWriterGroupedByCompletionRejectedPredictionTokens)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletionRejectedPredictionTokensKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCompletionRejectedPredictionTokens) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByStartedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.StartedAt == nil {
		return zero, false
	}
	return *value.StartedAt, true
}

type WriterHandlerCurrentWriterIndexedByStartedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByStartedAt() (WriterHandlerCurrentWriterIndexedByStartedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByStartedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStartedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByStartedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByStartedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByStartedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByStartedAt() WriterHandlerCurrentWriterGroupedByStartedAt {
	result := make(WriterHandlerCurrentWriterGroupedByStartedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStartedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByStartedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByCompletedAtKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.CompletedAt == nil {
		return zero, false
	}
	return *value.CompletedAt, true
}

type WriterHandlerCurrentWriterIndexedByCompletedAt map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByCompletedAt() (WriterHandlerCurrentWriterIndexedByCompletedAt, error) {
	result := make(WriterHandlerCurrentWriterIndexedByCompletedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByCompletedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByCompletedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByCompletedAt map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByCompletedAt() WriterHandlerCurrentWriterGroupedByCompletedAt {
	result := make(WriterHandlerCurrentWriterGroupedByCompletedAt)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByCompletedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByCompletedAt) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByLatencyMsKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.LatencyMs == nil {
		return zero, false
	}
	return *value.LatencyMs, true
}

type WriterHandlerCurrentWriterIndexedByLatencyMs map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByLatencyMs() (WriterHandlerCurrentWriterIndexedByLatencyMs, error) {
	result := make(WriterHandlerCurrentWriterIndexedByLatencyMs)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLatencyMsKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByLatencyMs")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByLatencyMs) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByLatencyMs map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByLatencyMs() WriterHandlerCurrentWriterGroupedByLatencyMs {
	result := make(WriterHandlerCurrentWriterGroupedByLatencyMs)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLatencyMsKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByLatencyMs) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByTraceIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.TraceId == nil {
		return zero, false
	}
	return *value.TraceId, true
}

type WriterHandlerCurrentWriterIndexedByTraceId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByTraceId() (WriterHandlerCurrentWriterIndexedByTraceId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByTraceId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTraceIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByTraceId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByTraceId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByTraceId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByTraceId() WriterHandlerCurrentWriterGroupedByTraceId {
	result := make(WriterHandlerCurrentWriterGroupedByTraceId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByTraceIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByTraceId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexBySpanIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.SpanId == nil {
		return zero, false
	}
	return *value.SpanId, true
}

type WriterHandlerCurrentWriterIndexedBySpanId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexBySpanId() (WriterHandlerCurrentWriterIndexedBySpanId, error) {
	result := make(WriterHandlerCurrentWriterIndexedBySpanId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexBySpanIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexBySpanId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedBySpanId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedBySpanId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupBySpanId() WriterHandlerCurrentWriterGroupedBySpanId {
	result := make(WriterHandlerCurrentWriterGroupedBySpanId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexBySpanIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedBySpanId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByRequestPayloadIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RequestPayloadId == nil {
		return zero, false
	}
	return *value.RequestPayloadId, true
}

type WriterHandlerCurrentWriterIndexedByRequestPayloadId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByRequestPayloadId() (WriterHandlerCurrentWriterIndexedByRequestPayloadId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByRequestPayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRequestPayloadIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByRequestPayloadId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByRequestPayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByRequestPayloadId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByRequestPayloadId() WriterHandlerCurrentWriterGroupedByRequestPayloadId {
	result := make(WriterHandlerCurrentWriterGroupedByRequestPayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRequestPayloadIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByRequestPayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByResponsePayloadIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ResponsePayloadId == nil {
		return zero, false
	}
	return *value.ResponsePayloadId, true
}

type WriterHandlerCurrentWriterIndexedByResponsePayloadId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByResponsePayloadId() (WriterHandlerCurrentWriterIndexedByResponsePayloadId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByResponsePayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByResponsePayloadIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByResponsePayloadId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByResponsePayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByResponsePayloadId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByResponsePayloadId() WriterHandlerCurrentWriterGroupedByResponsePayloadId {
	result := make(WriterHandlerCurrentWriterGroupedByResponsePayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByResponsePayloadIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByResponsePayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByProviderRequestPayloadIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ProviderRequestPayloadId == nil {
		return zero, false
	}
	return *value.ProviderRequestPayloadId, true
}

type WriterHandlerCurrentWriterIndexedByProviderRequestPayloadId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByProviderRequestPayloadId() (WriterHandlerCurrentWriterIndexedByProviderRequestPayloadId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByProviderRequestPayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByProviderRequestPayloadIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByProviderRequestPayloadId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByProviderRequestPayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByProviderRequestPayloadId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByProviderRequestPayloadId() WriterHandlerCurrentWriterGroupedByProviderRequestPayloadId {
	result := make(WriterHandlerCurrentWriterGroupedByProviderRequestPayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByProviderRequestPayloadIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByProviderRequestPayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByProviderResponsePayloadIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ProviderResponsePayloadId == nil {
		return zero, false
	}
	return *value.ProviderResponsePayloadId, true
}

type WriterHandlerCurrentWriterIndexedByProviderResponsePayloadId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByProviderResponsePayloadId() (WriterHandlerCurrentWriterIndexedByProviderResponsePayloadId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByProviderResponsePayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByProviderResponsePayloadIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByProviderResponsePayloadId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByProviderResponsePayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByProviderResponsePayloadId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByProviderResponsePayloadId() WriterHandlerCurrentWriterGroupedByProviderResponsePayloadId {
	result := make(WriterHandlerCurrentWriterGroupedByProviderResponsePayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByProviderResponsePayloadIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByProviderResponsePayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByStreamPayloadIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.StreamPayloadId == nil {
		return zero, false
	}
	return *value.StreamPayloadId, true
}

type WriterHandlerCurrentWriterIndexedByStreamPayloadId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByStreamPayloadId() (WriterHandlerCurrentWriterIndexedByStreamPayloadId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByStreamPayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStreamPayloadIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByStreamPayloadId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByStreamPayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByStreamPayloadId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByStreamPayloadId() WriterHandlerCurrentWriterGroupedByStreamPayloadId {
	result := make(WriterHandlerCurrentWriterGroupedByStreamPayloadId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByStreamPayloadIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByStreamPayloadId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByRunIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return *value.RunId, true
}

type WriterHandlerCurrentWriterIndexedByRunId map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByRunId() (WriterHandlerCurrentWriterIndexedByRunId, error) {
	result := make(WriterHandlerCurrentWriterIndexedByRunId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByRunId map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByRunId() WriterHandlerCurrentWriterGroupedByRunId {
	result := make(WriterHandlerCurrentWriterGroupedByRunId)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByIterationKey(value *CurrentWriterView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Iteration == nil {
		return zero, false
	}
	return *value.Iteration, true
}

type WriterHandlerCurrentWriterIndexedByIteration map[int]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByIteration() (WriterHandlerCurrentWriterIndexedByIteration, error) {
	result := make(WriterHandlerCurrentWriterIndexedByIteration)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByIterationKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByIteration")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByIteration) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByIteration map[int][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByIteration() WriterHandlerCurrentWriterGroupedByIteration {
	result := make(WriterHandlerCurrentWriterGroupedByIteration)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByIterationKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByIteration) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerReadIndexes struct {
	CurrentWriter            WriterHandlerCurrentWriterSlice
	CurrentWriterByMessageId WriterHandlerCurrentWriterIndexedByMessageId
}

func BuildWriterHandlerReadIndexes(ctx context.Context, input *Input) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &WriterHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentWriter")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentWriter")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*Input)(nil)).Elem()).Accessor("CurrentWriter")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentWriterView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentWriterView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentWriterView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("MessageId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.MessageId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Provider") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Provider")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Model") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Model")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ModelKind") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ModelKind")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Status") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Status")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Cost") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Cost")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("TurnId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.TurnId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ErrorCode") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ErrorCode")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ErrorMessage") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ErrorMessage")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("FinishReason") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.FinishReason")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PromptTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.PromptTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PromptCachedTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.PromptCachedTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CompletionTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CompletionTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("TotalTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.TotalTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PromptAudioTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.PromptAudioTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CompletionReasoningTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CompletionReasoningTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CompletionAudioTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CompletionAudioTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CompletionAcceptedPredictionTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CompletionAcceptedPredictionTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CompletionRejectedPredictionTokens") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CompletionRejectedPredictionTokens")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("StartedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.StartedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CompletedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.CompletedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("LatencyMs") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.LatencyMs")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("TraceId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.TraceId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("SpanId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.SpanId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RequestPayloadId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.RequestPayloadId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ResponsePayloadId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ResponsePayloadId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ProviderRequestPayloadId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ProviderRequestPayloadId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ProviderResponsePayloadId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.ProviderResponsePayloadId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("StreamPayloadId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.StreamPayloadId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.RunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Iteration") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Iteration")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentWriter = WriterHandlerCurrentWriterSlice(cloned.([]*CurrentWriterView))
		result.CurrentWriterByMessageId, err = result.CurrentWriter.IndexByMessageId()
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func (input *Input) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._writerHandlerReadIndexes = nil
	indexes, err := BuildWriterHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._writerHandlerReadIndexes = indexes
	return nil
}
func (input *Input) ReadIndexes(ctx context.Context) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._writerHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._writerHandlerReadIndexes, nil
}
