// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

func (entity *MutableConversationView) GetShouldDelete() bool {
	return entity.ShouldDelete
}
func (entity *MutableConversationView) SetShouldDelete(value bool) {
	entity.ShouldDelete = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ShouldDelete = true
}
func (entity *MutableConversationView) GetId() string {
	return entity.Id
}
func (entity *MutableConversationView) SetId(value string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.Id = true
}
func (entity *MutableConversationView) GetShareable() int {
	return entity.Shareable
}
func (entity *MutableConversationView) SetShareable(value int) {
	entity.Shareable = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.Shareable = true
}
func (entity *MutableConversationView) GetSummary() *string {
	return entity.Summary
}
func (entity *MutableConversationView) SetSummary(value *string) {
	entity.Summary = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.Summary = true
}
func (entity *MutableConversationView) GetLastActivity() *time.Time {
	return entity.LastActivity
}
func (entity *MutableConversationView) SetLastActivity(value *time.Time) {
	entity.LastActivity = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.LastActivity = true
}
func (entity *MutableConversationView) GetUsageInputTokens() *int {
	return entity.UsageInputTokens
}
func (entity *MutableConversationView) SetUsageInputTokens(value *int) {
	entity.UsageInputTokens = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.UsageInputTokens = true
}
func (entity *MutableConversationView) GetUsageOutputTokens() *int {
	return entity.UsageOutputTokens
}
func (entity *MutableConversationView) SetUsageOutputTokens(value *int) {
	entity.UsageOutputTokens = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.UsageOutputTokens = true
}
func (entity *MutableConversationView) GetUsageEmbeddingTokens() *int {
	return entity.UsageEmbeddingTokens
}
func (entity *MutableConversationView) SetUsageEmbeddingTokens(value *int) {
	entity.UsageEmbeddingTokens = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.UsageEmbeddingTokens = true
}
func (entity *MutableConversationView) GetCreatedAt() *time.Time {
	return entity.CreatedAt
}
func (entity *MutableConversationView) SetCreatedAt(value *time.Time) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *MutableConversationView) GetUpdatedAt() *time.Time {
	return entity.UpdatedAt
}
func (entity *MutableConversationView) SetUpdatedAt(value *time.Time) {
	entity.UpdatedAt = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.UpdatedAt = true
}
func (entity *MutableConversationView) GetCreatedByUserId() *string {
	return entity.CreatedByUserId
}
func (entity *MutableConversationView) SetCreatedByUserId(value *string) {
	entity.CreatedByUserId = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.CreatedByUserId = true
}
func (entity *MutableConversationView) GetAgentId() *string {
	return entity.AgentId
}
func (entity *MutableConversationView) SetAgentId(value *string) {
	entity.AgentId = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.AgentId = true
}
func (entity *MutableConversationView) GetDefaultModelProvider() *string {
	return entity.DefaultModelProvider
}
func (entity *MutableConversationView) SetDefaultModelProvider(value *string) {
	entity.DefaultModelProvider = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.DefaultModelProvider = true
}
func (entity *MutableConversationView) GetDefaultModel() *string {
	return entity.DefaultModel
}
func (entity *MutableConversationView) SetDefaultModel(value *string) {
	entity.DefaultModel = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.DefaultModel = true
}
func (entity *MutableConversationView) GetDefaultModelParams() *string {
	return entity.DefaultModelParams
}
func (entity *MutableConversationView) SetDefaultModelParams(value *string) {
	entity.DefaultModelParams = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.DefaultModelParams = true
}
func (entity *MutableConversationView) GetTitle() *string {
	return entity.Title
}
func (entity *MutableConversationView) SetTitle(value *string) {
	entity.Title = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.Title = true
}
func (entity *MutableConversationView) GetConversationParentId() *string {
	return entity.ConversationParentId
}
func (entity *MutableConversationView) SetConversationParentId(value *string) {
	entity.ConversationParentId = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ConversationParentId = true
}
func (entity *MutableConversationView) GetConversationParentTurnId() *string {
	return entity.ConversationParentTurnId
}
func (entity *MutableConversationView) SetConversationParentTurnId(value *string) {
	entity.ConversationParentTurnId = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ConversationParentTurnId = true
}
func (entity *MutableConversationView) GetMetadata() *string {
	return entity.Metadata
}
func (entity *MutableConversationView) SetMetadata(value *string) {
	entity.Metadata = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.Metadata = true
}
func (entity *MutableConversationView) GetVisibility() *string {
	return entity.Visibility
}
func (entity *MutableConversationView) SetVisibility(value *string) {
	entity.Visibility = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.Visibility = true
}
func (entity *MutableConversationView) GetStatus() *string {
	return entity.Status
}
func (entity *MutableConversationView) SetStatus(value *string) {
	entity.Status = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.Status = true
}
func (entity *MutableConversationView) GetScheduled() *int {
	return entity.Scheduled
}
func (entity *MutableConversationView) SetScheduled(value *int) {
	entity.Scheduled = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.Scheduled = true
}
func (entity *MutableConversationView) GetScheduleId() *string {
	return entity.ScheduleId
}
func (entity *MutableConversationView) SetScheduleId(value *string) {
	entity.ScheduleId = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ScheduleId = true
}
func (entity *MutableConversationView) GetScheduleRunId() *string {
	return entity.ScheduleRunId
}
func (entity *MutableConversationView) SetScheduleRunId(value *string) {
	entity.ScheduleRunId = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ScheduleRunId = true
}
func (entity *MutableConversationView) GetScheduleKind() *string {
	return entity.ScheduleKind
}
func (entity *MutableConversationView) SetScheduleKind(value *string) {
	entity.ScheduleKind = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ScheduleKind = true
}
func (entity *MutableConversationView) GetScheduleTimezone() *string {
	return entity.ScheduleTimezone
}
func (entity *MutableConversationView) SetScheduleTimezone(value *string) {
	entity.ScheduleTimezone = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ScheduleTimezone = true
}
func (entity *MutableConversationView) GetScheduleCronExpr() *string {
	return entity.ScheduleCronExpr
}
func (entity *MutableConversationView) SetScheduleCronExpr(value *string) {
	entity.ScheduleCronExpr = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ScheduleCronExpr = true
}
func (entity *MutableConversationView) GetExternalTaskRef() *string {
	return entity.ExternalTaskRef
}
func (entity *MutableConversationView) SetExternalTaskRef(value *string) {
	entity.ExternalTaskRef = value
	if entity.Has == nil {
		entity.Has = &MutableConversationViewHas{}
	}
	entity.Has.ExternalTaskRef = true
}
