// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	predicate "github.com/viant/agently-core/internal/datly/predicate"
	time "time"
)

func (entity *MutableRunView) GetShouldDelete() bool {
	return entity.ShouldDelete
}
func (entity *MutableRunView) SetShouldDelete(value bool) {
	entity.ShouldDelete = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ShouldDelete = true
}
func (entity *MutableRunView) GetCondition() *predicate.RunPatchCondition {
	return entity.Condition
}
func (entity *MutableRunView) SetCondition(value *predicate.RunPatchCondition) {
	entity.Condition = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.Condition = true
}
func (entity *MutableRunView) GetId() string {
	return entity.Id
}
func (entity *MutableRunView) SetId(value string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.Id = true
}
func (entity *MutableRunView) GetRunKind() string {
	return entity.RunKind
}
func (entity *MutableRunView) SetRunKind(value string) {
	entity.RunKind = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.RunKind = true
}
func (entity *MutableRunView) GetStatus() string {
	return entity.Status
}
func (entity *MutableRunView) SetStatus(value string) {
	entity.Status = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.Status = true
}
func (entity *MutableRunView) GetUsageCost() *float64 {
	return entity.UsageCost
}
func (entity *MutableRunView) SetUsageCost(value *float64) {
	entity.UsageCost = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.UsageCost = true
}
func (entity *MutableRunView) GetProtocolKey() *string {
	return entity.ProtocolKey
}
func (entity *MutableRunView) SetProtocolKey(value *string) {
	entity.ProtocolKey = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolKey = true
}
func (entity *MutableRunView) GetProtocolStatus() *string {
	return entity.ProtocolStatus
}
func (entity *MutableRunView) SetProtocolStatus(value *string) {
	entity.ProtocolStatus = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolStatus = true
}
func (entity *MutableRunView) GetProtocolTurnId() *string {
	return entity.ProtocolTurnId
}
func (entity *MutableRunView) SetProtocolTurnId(value *string) {
	entity.ProtocolTurnId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolTurnId = true
}
func (entity *MutableRunView) GetProtocolRunId() *string {
	return entity.ProtocolRunId
}
func (entity *MutableRunView) SetProtocolRunId(value *string) {
	entity.ProtocolRunId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolRunId = true
}
func (entity *MutableRunView) GetProtocolParentRunId() *string {
	return entity.ProtocolParentRunId
}
func (entity *MutableRunView) SetProtocolParentRunId(value *string) {
	entity.ProtocolParentRunId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolParentRunId = true
}
func (entity *MutableRunView) GetProtocolPriorRunId() *string {
	return entity.ProtocolPriorRunId
}
func (entity *MutableRunView) SetProtocolPriorRunId(value *string) {
	entity.ProtocolPriorRunId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolPriorRunId = true
}
func (entity *MutableRunView) GetProtocolClientMessageId() *string {
	return entity.ProtocolClientMessageId
}
func (entity *MutableRunView) SetProtocolClientMessageId(value *string) {
	entity.ProtocolClientMessageId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolClientMessageId = true
}
func (entity *MutableRunView) GetProtocolResumedByRunId() *string {
	return entity.ProtocolResumedByRunId
}
func (entity *MutableRunView) SetProtocolResumedByRunId(value *string) {
	entity.ProtocolResumedByRunId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolResumedByRunId = true
}
func (entity *MutableRunView) GetProtocolSourceKey() *string {
	return entity.ProtocolSourceKey
}
func (entity *MutableRunView) SetProtocolSourceKey(value *string) {
	entity.ProtocolSourceKey = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolSourceKey = true
}
func (entity *MutableRunView) GetProtocolInitialTurnKey() *string {
	return entity.ProtocolInitialTurnKey
}
func (entity *MutableRunView) SetProtocolInitialTurnKey(value *string) {
	entity.ProtocolInitialTurnKey = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolInitialTurnKey = true
}
func (entity *MutableRunView) GetProtocolInputHash() *string {
	return entity.ProtocolInputHash
}
func (entity *MutableRunView) SetProtocolInputHash(value *string) {
	entity.ProtocolInputHash = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolInputHash = true
}
func (entity *MutableRunView) GetProtocolInputJson() *string {
	return entity.ProtocolInputJson
}
func (entity *MutableRunView) SetProtocolInputJson(value *string) {
	entity.ProtocolInputJson = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolInputJson = true
}
func (entity *MutableRunView) GetProtocolPendingJson() *string {
	return entity.ProtocolPendingJson
}
func (entity *MutableRunView) SetProtocolPendingJson(value *string) {
	entity.ProtocolPendingJson = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolPendingJson = true
}
func (entity *MutableRunView) GetProtocolRevision() *int {
	return entity.ProtocolRevision
}
func (entity *MutableRunView) SetProtocolRevision(value *int) {
	entity.ProtocolRevision = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolRevision = true
}
func (entity *MutableRunView) GetProtocolLastSequence() *int {
	return entity.ProtocolLastSequence
}
func (entity *MutableRunView) SetProtocolLastSequence(value *int) {
	entity.ProtocolLastSequence = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolLastSequence = true
}
func (entity *MutableRunView) GetProtocolLeaseOwner() *string {
	return entity.ProtocolLeaseOwner
}
func (entity *MutableRunView) SetProtocolLeaseOwner(value *string) {
	entity.ProtocolLeaseOwner = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolLeaseOwner = true
}
func (entity *MutableRunView) GetProtocolLeaseUntil() *time.Time {
	return entity.ProtocolLeaseUntil
}
func (entity *MutableRunView) SetProtocolLeaseUntil(value *time.Time) {
	entity.ProtocolLeaseUntil = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolLeaseUntil = true
}
func (entity *MutableRunView) GetProtocolLeaseRevision() *int {
	return entity.ProtocolLeaseRevision
}
func (entity *MutableRunView) SetProtocolLeaseRevision(value *int) {
	entity.ProtocolLeaseRevision = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ProtocolLeaseRevision = true
}
func (entity *MutableRunView) GetTurnId() *string {
	return entity.TurnId
}
func (entity *MutableRunView) SetTurnId(value *string) {
	entity.TurnId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.TurnId = true
}
func (entity *MutableRunView) GetScheduleId() *string {
	return entity.ScheduleId
}
func (entity *MutableRunView) SetScheduleId(value *string) {
	entity.ScheduleId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ScheduleId = true
}
func (entity *MutableRunView) GetConversationId() *string {
	return entity.ConversationId
}
func (entity *MutableRunView) SetConversationId(value *string) {
	entity.ConversationId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ConversationId = true
}
func (entity *MutableRunView) GetConversationKind() *string {
	return entity.ConversationKind
}
func (entity *MutableRunView) SetConversationKind(value *string) {
	entity.ConversationKind = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ConversationKind = true
}
func (entity *MutableRunView) GetAttempt() *int {
	return entity.Attempt
}
func (entity *MutableRunView) SetAttempt(value *int) {
	entity.Attempt = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.Attempt = true
}
func (entity *MutableRunView) GetResumedFromRunId() *string {
	return entity.ResumedFromRunId
}
func (entity *MutableRunView) SetResumedFromRunId(value *string) {
	entity.ResumedFromRunId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ResumedFromRunId = true
}
func (entity *MutableRunView) GetErrorCode() *string {
	return entity.ErrorCode
}
func (entity *MutableRunView) SetErrorCode(value *string) {
	entity.ErrorCode = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ErrorCode = true
}
func (entity *MutableRunView) GetErrorMessage() *string {
	return entity.ErrorMessage
}
func (entity *MutableRunView) SetErrorMessage(value *string) {
	entity.ErrorMessage = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ErrorMessage = true
}
func (entity *MutableRunView) GetIteration() *int {
	return entity.Iteration
}
func (entity *MutableRunView) SetIteration(value *int) {
	entity.Iteration = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.Iteration = true
}
func (entity *MutableRunView) GetMaxIterations() *int {
	return entity.MaxIterations
}
func (entity *MutableRunView) SetMaxIterations(value *int) {
	entity.MaxIterations = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.MaxIterations = true
}
func (entity *MutableRunView) GetCheckpointResponseId() *string {
	return entity.CheckpointResponseId
}
func (entity *MutableRunView) SetCheckpointResponseId(value *string) {
	entity.CheckpointResponseId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.CheckpointResponseId = true
}
func (entity *MutableRunView) GetCheckpointMessageId() *string {
	return entity.CheckpointMessageId
}
func (entity *MutableRunView) SetCheckpointMessageId(value *string) {
	entity.CheckpointMessageId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.CheckpointMessageId = true
}
func (entity *MutableRunView) GetCheckpointData() *string {
	return entity.CheckpointData
}
func (entity *MutableRunView) SetCheckpointData(value *string) {
	entity.CheckpointData = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.CheckpointData = true
}
func (entity *MutableRunView) GetAgentId() *string {
	return entity.AgentId
}
func (entity *MutableRunView) SetAgentId(value *string) {
	entity.AgentId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.AgentId = true
}
func (entity *MutableRunView) GetModelProvider() *string {
	return entity.ModelProvider
}
func (entity *MutableRunView) SetModelProvider(value *string) {
	entity.ModelProvider = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ModelProvider = true
}
func (entity *MutableRunView) GetModel() *string {
	return entity.Model
}
func (entity *MutableRunView) SetModel(value *string) {
	entity.Model = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.Model = true
}
func (entity *MutableRunView) GetWorkerId() *string {
	return entity.WorkerId
}
func (entity *MutableRunView) SetWorkerId(value *string) {
	entity.WorkerId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.WorkerId = true
}
func (entity *MutableRunView) GetWorkerPid() *int {
	return entity.WorkerPid
}
func (entity *MutableRunView) SetWorkerPid(value *int) {
	entity.WorkerPid = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.WorkerPid = true
}
func (entity *MutableRunView) GetWorkerHost() *string {
	return entity.WorkerHost
}
func (entity *MutableRunView) SetWorkerHost(value *string) {
	entity.WorkerHost = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.WorkerHost = true
}
func (entity *MutableRunView) GetLeaseOwner() *string {
	return entity.LeaseOwner
}
func (entity *MutableRunView) SetLeaseOwner(value *string) {
	entity.LeaseOwner = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.LeaseOwner = true
}
func (entity *MutableRunView) GetLeaseUntil() *time.Time {
	return entity.LeaseUntil
}
func (entity *MutableRunView) SetLeaseUntil(value *time.Time) {
	entity.LeaseUntil = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.LeaseUntil = true
}
func (entity *MutableRunView) GetLastHeartbeatAt() *time.Time {
	return entity.LastHeartbeatAt
}
func (entity *MutableRunView) SetLastHeartbeatAt(value *time.Time) {
	entity.LastHeartbeatAt = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.LastHeartbeatAt = true
}
func (entity *MutableRunView) GetSecurityContext() *string {
	return entity.SecurityContext
}
func (entity *MutableRunView) SetSecurityContext(value *string) {
	entity.SecurityContext = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.SecurityContext = true
}
func (entity *MutableRunView) GetEffectiveUserId() *string {
	return entity.EffectiveUserId
}
func (entity *MutableRunView) SetEffectiveUserId(value *string) {
	entity.EffectiveUserId = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.EffectiveUserId = true
}
func (entity *MutableRunView) GetAuthAuthority() *string {
	return entity.AuthAuthority
}
func (entity *MutableRunView) SetAuthAuthority(value *string) {
	entity.AuthAuthority = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.AuthAuthority = true
}
func (entity *MutableRunView) GetAuthAudience() *string {
	return entity.AuthAudience
}
func (entity *MutableRunView) SetAuthAudience(value *string) {
	entity.AuthAudience = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.AuthAudience = true
}
func (entity *MutableRunView) GetUserCredUrl() *string {
	return entity.UserCredUrl
}
func (entity *MutableRunView) SetUserCredUrl(value *string) {
	entity.UserCredUrl = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.UserCredUrl = true
}
func (entity *MutableRunView) GetHeartbeatIntervalSec() *int {
	return entity.HeartbeatIntervalSec
}
func (entity *MutableRunView) SetHeartbeatIntervalSec(value *int) {
	entity.HeartbeatIntervalSec = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.HeartbeatIntervalSec = true
}
func (entity *MutableRunView) GetScheduledFor() *time.Time {
	return entity.ScheduledFor
}
func (entity *MutableRunView) SetScheduledFor(value *time.Time) {
	entity.ScheduledFor = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.ScheduledFor = true
}
func (entity *MutableRunView) GetPreconditionRanAt() *time.Time {
	return entity.PreconditionRanAt
}
func (entity *MutableRunView) SetPreconditionRanAt(value *time.Time) {
	entity.PreconditionRanAt = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.PreconditionRanAt = true
}
func (entity *MutableRunView) GetPreconditionPassed() *int {
	return entity.PreconditionPassed
}
func (entity *MutableRunView) SetPreconditionPassed(value *int) {
	entity.PreconditionPassed = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.PreconditionPassed = true
}
func (entity *MutableRunView) GetPreconditionResult() *string {
	return entity.PreconditionResult
}
func (entity *MutableRunView) SetPreconditionResult(value *string) {
	entity.PreconditionResult = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.PreconditionResult = true
}
func (entity *MutableRunView) GetUsagePromptTokens() *int {
	return entity.UsagePromptTokens
}
func (entity *MutableRunView) SetUsagePromptTokens(value *int) {
	entity.UsagePromptTokens = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.UsagePromptTokens = true
}
func (entity *MutableRunView) GetUsageCompletionTokens() *int {
	return entity.UsageCompletionTokens
}
func (entity *MutableRunView) SetUsageCompletionTokens(value *int) {
	entity.UsageCompletionTokens = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.UsageCompletionTokens = true
}
func (entity *MutableRunView) GetUsageTotalTokens() *int {
	return entity.UsageTotalTokens
}
func (entity *MutableRunView) SetUsageTotalTokens(value *int) {
	entity.UsageTotalTokens = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.UsageTotalTokens = true
}
func (entity *MutableRunView) GetCreatedAt() *time.Time {
	return entity.CreatedAt
}
func (entity *MutableRunView) SetCreatedAt(value *time.Time) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *MutableRunView) GetUpdatedAt() *time.Time {
	return entity.UpdatedAt
}
func (entity *MutableRunView) SetUpdatedAt(value *time.Time) {
	entity.UpdatedAt = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.UpdatedAt = true
}
func (entity *MutableRunView) GetStartedAt() *time.Time {
	return entity.StartedAt
}
func (entity *MutableRunView) SetStartedAt(value *time.Time) {
	entity.StartedAt = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.StartedAt = true
}
func (entity *MutableRunView) GetCompletedAt() *time.Time {
	return entity.CompletedAt
}
func (entity *MutableRunView) SetCompletedAt(value *time.Time) {
	entity.CompletedAt = value
	if entity.Has == nil {
		entity.Has = &MutableRunViewHas{}
	}
	entity.Has.CompletedAt = true
}
