// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	predicate "github.com/viant/agently-core/internal/datly/predicate"
	time "time"
)

func (input *Input) SetExecutionRunOnly(value bool) {
	if input == nil {
		return
	}
	input.ExecutionRunOnly = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ExecutionRunOnly = true
}

func (input *Input) SetOrphanDetach(value bool) {
	if input == nil {
		return
	}
	input.OrphanDetach = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanDetach = true
}

func (input *Input) SetOrphanColumn(value string) {
	if input == nil {
		return
	}
	input.OrphanColumn = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanColumn = true
}

func (input *Input) SetLeaseMode(value string) {
	if input == nil {
		return
	}
	input.LeaseMode = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.LeaseMode = true
}

func (input *Input) SetLeaseOwner(value string) {
	if input == nil {
		return
	}
	input.LeaseOwner = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.LeaseOwner = true
}

func (input *Input) SetLeaseNow(value time.Time) {
	if input == nil {
		return
	}
	input.LeaseNow = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.LeaseNow = true
}

func (input *Input) SetExpectations(value []*predicate.RunExpected) {
	if input == nil {
		return
	}
	input.Expectations = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Expectations = true
}

func (input *Input) SetRuns(value []*MutableRunView) {
	if input == nil {
		return
	}
	input.Runs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Runs = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
