// Code generated by Datly for writer; DO NOT EDIT.

package write

func (entity *Run) GetId() *string {
	return entity.Id
}
func (entity *Run) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Id = true
}
func (entity *Run) GetRevision() int64 {
	return entity.Revision
}
func (entity *Run) SetRevision(value int64) {
	entity.Revision = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Revision = true
}
func (entity *Run) GetRunId() string {
	return entity.RunId
}
func (entity *Run) SetRunId(value string) {
	entity.RunId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.RunId = true
}
func (entity *Run) GetParentRunId() string {
	return entity.ParentRunId
}
func (entity *Run) SetParentRunId(value string) {
	entity.ParentRunId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.ParentRunId = true
}
func (entity *Run) GetPriorRunId() string {
	return entity.PriorRunId
}
func (entity *Run) SetPriorRunId(value string) {
	entity.PriorRunId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.PriorRunId = true
}
func (entity *Run) GetClientMessageId() string {
	return entity.ClientMessageId
}
func (entity *Run) SetClientMessageId(value string) {
	entity.ClientMessageId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.ClientMessageId = true
}
func (entity *Run) GetTurnId() string {
	return entity.TurnId
}
func (entity *Run) SetTurnId(value string) {
	entity.TurnId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.TurnId = true
}
func (entity *Run) GetResumedByRunId() string {
	return entity.ResumedByRunId
}
func (entity *Run) SetResumedByRunId(value string) {
	entity.ResumedByRunId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.ResumedByRunId = true
}
func (entity *Run) GetInputJson() []byte {
	return entity.InputJson
}
func (entity *Run) SetInputJson(value []byte) {
	entity.InputJson = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.InputJson = true
}
func (entity *Run) GetPendingJson() []byte {
	return entity.PendingJson
}
func (entity *Run) SetPendingJson(value []byte) {
	entity.PendingJson = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.PendingJson = true
}
func (entity *Run) GetLastSequence() int64 {
	return entity.LastSequence
}
func (entity *Run) SetLastSequence(value int64) {
	entity.LastSequence = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.LastSequence = true
}
func (entity *Run) GetPrincipal() *string {
	return entity.Principal
}
func (entity *Run) SetPrincipal(value *string) {
	entity.Principal = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Principal = true
}
func (entity *Run) GetRunKey() *string {
	return entity.RunKey
}
func (entity *Run) SetRunKey(value *string) {
	entity.RunKey = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.RunKey = true
}
func (entity *Run) GetStatus() *string {
	return entity.Status
}
func (entity *Run) SetStatus(value *string) {
	entity.Status = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Status = true
}
func (entity *Run) GetInputHash() *string {
	return entity.InputHash
}
func (entity *Run) SetInputHash(value *string) {
	entity.InputHash = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.InputHash = true
}
func (entity *Run) GetSourceKey() *string {
	return entity.SourceKey
}
func (entity *Run) SetSourceKey(value *string) {
	entity.SourceKey = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.SourceKey = true
}
func (entity *Run) GetInitialTurnKey() *string {
	return entity.InitialTurnKey
}
func (entity *Run) SetInitialTurnKey(value *string) {
	entity.InitialTurnKey = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.InitialTurnKey = true
}
func (entity *Run) GetConversationId() *string {
	return entity.ConversationId
}
func (entity *Run) SetConversationId(value *string) {
	entity.ConversationId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.ConversationId = true
}
func (entity *Run) GetRunKind() *string {
	return entity.RunKind
}
func (entity *Run) SetRunKind(value *string) {
	entity.RunKind = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.RunKind = true
}
