// Code generated by Datly for writer; DO NOT EDIT.

package write

func (entity *Thread) GetId() *string {
	return entity.Id
}
func (entity *Thread) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.Id = true
}
func (entity *Thread) GetRevision() int64 {
	return entity.Revision
}
func (entity *Thread) SetRevision(value int64) {
	entity.Revision = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.Revision = true
}
func (entity *Thread) GetThreadId() *string {
	return entity.ThreadId
}
func (entity *Thread) SetThreadId(value *string) {
	entity.ThreadId = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.ThreadId = true
}
func (entity *Thread) GetPrincipal() *string {
	return entity.Principal
}
func (entity *Thread) SetPrincipal(value *string) {
	entity.Principal = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.Principal = true
}
func (entity *Thread) GetStateJson() []byte {
	return entity.StateJson
}
func (entity *Thread) SetStateJson(value []byte) {
	entity.StateJson = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.StateJson = true
}
func (entity *Thread) GetMessagesJson() []byte {
	return entity.MessagesJson
}
func (entity *Thread) SetMessagesJson(value []byte) {
	entity.MessagesJson = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.MessagesJson = true
}
func (entity *Thread) GetProtocolOnly() bool {
	return entity.ProtocolOnly
}
func (entity *Thread) SetProtocolOnly(value bool) {
	entity.ProtocolOnly = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.ProtocolOnly = true
}
func (entity *Thread) GetThreadKey() *string {
	return entity.ThreadKey
}
func (entity *Thread) SetThreadKey(value *string) {
	entity.ThreadKey = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.ThreadKey = true
}
func (entity *Thread) GetCreatedByUserId() *string {
	return entity.CreatedByUserId
}
func (entity *Thread) SetCreatedByUserId(value *string) {
	entity.CreatedByUserId = value
	if entity.Has == nil {
		entity.Has = &ThreadHas{}
	}
	entity.Has.CreatedByUserId = true
}
