// Code generated by Datly for writer; DO NOT EDIT.

package write

// Thread is generated canonical view metadata for writer.
type Thread struct {
	Id              *string    `sqlx:"id,primaryKey=true,required=true" json:"id,omitempty"`
	Revision        int64      `sqlx:"protocol_revision,required=true" writer:"concurrency" json:"revision,omitempty"`
	ThreadId        *string    `sqlx:"protocol_thread_id" json:"threadId,omitempty"`
	Principal       *string    `sqlx:"protocol_principal" json:"principal,omitempty"`
	StateJson       []byte     `sqlx:"protocol_state_json" json:"stateJson,omitempty"`
	MessagesJson    []byte     `sqlx:"protocol_messages_json" json:"messagesJson,omitempty"`
	ProtocolOnly    bool       `sqlx:"protocol_only,required=true" json:"protocolOnly,omitempty"`
	ThreadKey       *string    `sqlx:"protocol_thread_key" json:"threadKey,omitempty"`
	CreatedByUserId *string    `sqlx:"created_by_user_id" json:"createdByUserId,omitempty"`
	Has             *ThreadHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"ThreadHas"`
}

type ThreadHas struct {
	Id              bool
	Revision        bool
	ThreadId        bool
	Principal       bool
	StateJson       bool
	MessagesJson    bool
	ProtocolOnly    bool
	ThreadKey       bool
	CreatedByUserId bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	Id              *string `sqlx:"id,primaryKey=true,required=true" json:"id,omitempty"`
	Revision        int64   `sqlx:"protocol_revision,required=true" json:"revision,omitempty"`
	ThreadId        *string `sqlx:"protocol_thread_id" json:"threadId,omitempty"`
	Principal       *string `sqlx:"protocol_principal" json:"principal,omitempty"`
	StateJson       []byte  `sqlx:"protocol_state_json" json:"stateJson,omitempty"`
	MessagesJson    []byte  `sqlx:"protocol_messages_json" json:"messagesJson,omitempty"`
	ProtocolOnly    bool    `sqlx:"protocol_only,required=true" json:"protocolOnly,omitempty"`
	ThreadKey       *string `sqlx:"protocol_thread_key" json:"threadKey,omitempty"`
	CreatedByUserId *string `sqlx:"created_by_user_id" json:"createdByUserId,omitempty"`
}

type WriterKeysRow struct {
	Id *string `sqlx:"id"`
}
