// Code generated by Datly for reader; DO NOT EDIT.

package read

import (
	predicate "github.com/viant/agently-core/internal/datly/predicate"
)

func (input *Input) SetTrusted(value bool) {
	if input == nil {
		return
	}
	input.Trusted = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Trusted = true
}

func (input *Input) SetEventID(value string) {
	if input == nil {
		return
	}
	input.EventID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.EventID = true
}

func (input *Input) SetJobID(value string) {
	if input == nil {
		return
	}
	input.JobID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.JobID = true
}

func (input *Input) SetArtifactID(value string) {
	if input == nil {
		return
	}
	input.ArtifactID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ArtifactID = true
}

func (input *Input) SetActorID(value string) {
	if input == nil {
		return
	}
	input.ActorID = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ActorID = true
}

func (input *Input) SetJobIDs(value []string) {
	if input == nil {
		return
	}
	input.JobIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.JobIDs = true
}

func (input *Input) SetArtifactIDs(value []string) {
	if input == nil {
		return
	}
	input.ArtifactIDs = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.ArtifactIDs = true
}

func (input *Input) SetTechnicalRetention(value *predicate.TechnicalRetention) {
	if input == nil {
		return
	}
	input.TechnicalRetention = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.TechnicalRetention = true
}
