// Code generated by Datly for writer; DO NOT EDIT.

package write

func (input *Input) SetOrphanDetach(value bool) {
	if input == nil {
		return
	}
	input.OrphanDetach = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanDetach = true
}

func (input *Input) SetOrphanColumn(value string) {
	if input == nil {
		return
	}
	input.OrphanColumn = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.OrphanColumn = true
}

func (input *Input) SetQueues(value []*ToolApprovalQueue) {
	if input == nil {
		return
	}
	input.Queues = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.Queues = true
}

func (input *Input) SetWriterKeys(value []WriterKeysRow) {
	if input == nil {
		return
	}
	input.WriterKeys = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.WriterKeys = true
}

func (input *Input) SetCurrentWriter(value []*CurrentWriterView) {
	if input == nil {
		return
	}
	input.CurrentWriter = value
	if input.Has == nil {
		input.Has = &InputHas{}
	}
	input.Has.CurrentWriter = true
}
