// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
	time "time"
)

type WriterHandlerCurrentWriterSlice []*CurrentWriterView

func WriterHandlerCurrentWriterIndexByIdKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type WriterHandlerCurrentWriterIndexedById map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexById() (WriterHandlerCurrentWriterIndexedById, error) {
	result := make(WriterHandlerCurrentWriterIndexedById)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedById map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupById() WriterHandlerCurrentWriterGroupedById {
	result := make(WriterHandlerCurrentWriterGroupedById)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByRevisionKey(value *CurrentWriterView) (int64, bool) {
	var zero int64
	if value == nil {
		return zero, false
	}
	return value.Revision, true
}

type WriterHandlerCurrentWriterIndexedByRevision map[int64]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByRevision() (WriterHandlerCurrentWriterIndexedByRevision, error) {
	result := make(WriterHandlerCurrentWriterIndexedByRevision)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByRevision) Has(key int64) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByRevision map[int64][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByRevision() WriterHandlerCurrentWriterGroupedByRevision {
	result := make(WriterHandlerCurrentWriterGroupedByRevision)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByRevision) Has(key int64) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByOwnerKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Owner == nil {
		return zero, false
	}
	return *value.Owner, true
}

type WriterHandlerCurrentWriterIndexedByOwner map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByOwner() (WriterHandlerCurrentWriterIndexedByOwner, error) {
	result := make(WriterHandlerCurrentWriterIndexedByOwner)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByOwnerKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByOwner")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByOwner) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByOwner map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByOwner() WriterHandlerCurrentWriterGroupedByOwner {
	result := make(WriterHandlerCurrentWriterGroupedByOwner)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByOwnerKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByOwner) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByLeaseUntilKey(value *CurrentWriterView) (time.Time, bool) {
	var zero time.Time
	if value == nil {
		return zero, false
	}
	if value.LeaseUntil == nil {
		return zero, false
	}
	return *value.LeaseUntil, true
}

type WriterHandlerCurrentWriterIndexedByLeaseUntil map[time.Time]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByLeaseUntil() (WriterHandlerCurrentWriterIndexedByLeaseUntil, error) {
	result := make(WriterHandlerCurrentWriterIndexedByLeaseUntil)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseUntilKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByLeaseUntil")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByLeaseUntil) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByLeaseUntil map[time.Time][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByLeaseUntil() WriterHandlerCurrentWriterGroupedByLeaseUntil {
	result := make(WriterHandlerCurrentWriterGroupedByLeaseUntil)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByLeaseUntilKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByLeaseUntil) Has(key time.Time) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByRunKeyKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunKey == nil {
		return zero, false
	}
	return *value.RunKey, true
}

type WriterHandlerCurrentWriterIndexedByRunKey map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByRunKey() (WriterHandlerCurrentWriterIndexedByRunKey, error) {
	result := make(WriterHandlerCurrentWriterIndexedByRunKey)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRunKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByRunKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByRunKey) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByRunKey map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByRunKey() WriterHandlerCurrentWriterGroupedByRunKey {
	result := make(WriterHandlerCurrentWriterGroupedByRunKey)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRunKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByRunKey) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByPrincipalKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Principal == nil {
		return zero, false
	}
	return *value.Principal, true
}

type WriterHandlerCurrentWriterIndexedByPrincipal map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByPrincipal() (WriterHandlerCurrentWriterIndexedByPrincipal, error) {
	result := make(WriterHandlerCurrentWriterIndexedByPrincipal)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPrincipalKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByPrincipal")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByPrincipal) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByPrincipal map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByPrincipal() WriterHandlerCurrentWriterGroupedByPrincipal {
	result := make(WriterHandlerCurrentWriterGroupedByPrincipal)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByPrincipalKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByPrincipal) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func WriterHandlerCurrentWriterIndexByRunKindKey(value *CurrentWriterView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunKind == nil {
		return zero, false
	}
	return *value.RunKind, true
}

type WriterHandlerCurrentWriterIndexedByRunKind map[string]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) IndexByRunKind() (WriterHandlerCurrentWriterIndexedByRunKind, error) {
	result := make(WriterHandlerCurrentWriterIndexedByRunKind)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRunKindKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index WriterHandlerCurrentWriterSlice.IndexByRunKind")
		}
		result[key] = row
	}
	return result, nil
}
func (index WriterHandlerCurrentWriterIndexedByRunKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerCurrentWriterGroupedByRunKind map[string][]*CurrentWriterView

func (rows WriterHandlerCurrentWriterSlice) GroupByRunKind() WriterHandlerCurrentWriterGroupedByRunKind {
	result := make(WriterHandlerCurrentWriterGroupedByRunKind)
	for _, row := range rows {
		key, ok := WriterHandlerCurrentWriterIndexByRunKindKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index WriterHandlerCurrentWriterGroupedByRunKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type WriterHandlerReadIndexes struct {
	CurrentWriter     WriterHandlerCurrentWriterSlice
	CurrentWriterById WriterHandlerCurrentWriterIndexedById
}

func BuildWriterHandlerReadIndexes(ctx context.Context, input *Input) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &WriterHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentWriter")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentWriter")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*Input)(nil)).Elem()).Accessor("CurrentWriter")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentWriterView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentWriterView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentWriterView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Owner") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Owner")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("LeaseUntil") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.LeaseUntil")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunKey") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.RunKey")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Principal") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.Principal")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunKind") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentWriter.RunKind")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentWriter = WriterHandlerCurrentWriterSlice(cloned.([]*CurrentWriterView))
		result.CurrentWriterById, err = result.CurrentWriter.IndexById()
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func (input *Input) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._writerHandlerReadIndexes = nil
	indexes, err := BuildWriterHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._writerHandlerReadIndexes = indexes
	return nil
}
func (input *Input) ReadIndexes(ctx context.Context) (*WriterHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._writerHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._writerHandlerReadIndexes, nil
}
