// Code generated by Datly for writer; DO NOT EDIT.

package write

import (
	time "time"
)

// Lease is generated canonical view metadata for writer.
type Lease struct {
	Id         *string    `sqlx:"id,primaryKey=true,required=true" json:"id"`
	Revision   int64      `sqlx:"protocol_lease_revision,required=true" writer:"concurrency" json:"revision"`
	Owner      *string    `sqlx:"protocol_lease_owner" json:"owner"`
	LeaseUntil *time.Time `sqlx:"protocol_lease_until" json:"leaseUntil"`
	RunKey     *string    `sqlx:"protocol_key" json:"runKey"`
	Principal  *string    `sqlx:"effective_user_id" json:"principal"`
	RunKind    *string    `sqlx:"run_kind,required=true" json:"runKind"`
	Has        *LeaseHas  `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"LeaseHas"`
}

type LeaseHas struct {
	Id         bool
	Revision   bool
	Owner      bool
	LeaseUntil bool
	RunKey     bool
	Principal  bool
	RunKind    bool
}

// CurrentWriterView is generated canonical view metadata for writer.
type CurrentWriterView struct {
	Id         *string    `sqlx:"id,primaryKey=true,required=true" json:"id"`
	Revision   int64      `sqlx:"protocol_lease_revision,required=true" json:"revision"`
	Owner      *string    `sqlx:"protocol_lease_owner" json:"owner"`
	LeaseUntil *time.Time `sqlx:"protocol_lease_until" json:"leaseUntil"`
	RunKey     *string    `sqlx:"protocol_key" json:"runKey"`
	Principal  *string    `sqlx:"effective_user_id" json:"principal"`
	RunKind    *string    `sqlx:"run_kind,required=true" json:"runKind"`
}

type WriterKeysRow struct {
	Id *string `sqlx:"id"`
}
